'use strict';
/* Banque de cas — deuxième série « à l'aveugle » : écrite après la deuxième passe d'enrichissement,
 * jouée une première fois telle quelle. C'est ce premier passage qui donne le chiffre de généralisation
 * consigné dans PROGRESS.md ; les cas servent ensuite de non-régression. */
module.exports = function (cas) {
  const A = function (id, titre, description, o) { return cas(id, 'aveugle2', titre, description, Object.assign({ aveugle2: true }, o)); };
  return [
    A('av2-01', 'Différentiel général qui saute avec le départ clim', 'armoire TD étage 3 : le différentiel 300 mA général saute dès qu on remet le départ de la clim de la salle de réunion',
      { faits: [[/combien de temps/, 'immédiatement']],
        controles: [[/un par un/, 'c est le départ de la clim de la salle de réunion qui fait sauter : pas bon'], [/recepteurs debranches/, 'ligne seule : > 200 MΩ', 'c'], [/appareil identifie/, 'unité extérieure : 0,02 MΩ, compresseur à la masse']],
        attendu: /recepteur defectueux|defaut d.isolement/ }),
    A('av2-02', 'Moteur de broyeur qui fume', 'moteur du broyeur a fumé et disjoncte direct quand on relance',
      { faits: [[/combien de temps/, 'immédiatement'], [/differentiel/, 'oui'], [/plaque/, '15 kW 29 A']],
        controles: [[/resistance de chaque enroulement/, 'U : 0,8 Ω · V : 0,1 Ω · W : 0,8 Ω'], [/ensemble cable \+ moteur/, '0,3 MΩ'], [/moteur deconnecte/, '0,2 MΩ, bobinage noirci']],
        attendu: /enroulement|isolement du bobinage/ }),
    A('av2-03', 'Forage qui ne donne plus d’eau', 'pompe de forage : plus d eau au robinet, la pompe tourne mais ampérage très faible',
      { controles: [[/niveau de la reserve/, 'niveau de la nappe descendu sous la pompe, les sondes de niveau sont entartrées et ne coupent plus : pas bon']],
        attendu: /marche a sec/ }),
    A('av2-04', 'Split qui ne répond plus à la télécommande', 'split de la chambre 12 ne démarre plus, il ne répond pas à la télécommande, aucun voyant de défaut',
      { faits: [[/code/, 'non']],
        controles: [[/mode, consigne, programmation/, 'piles de la télécommande à plat ; avec des piles neuves ça démarre : pas bon']],
        attendu: /pas de demande/ }),
    A('av2-05', 'Compresseur de chambre froide qui claque sans démarrer', 'groupe de la chambre froide positive : le compresseur claque, ne démarre pas, et la protection coupe',
      { faits: [[/code/, 'non'], [/combien de temps/, 'tout de suite'], [/differentiel/, 'non']],
        controles: [[/capacite du condensateur/, '35 µF mesurés pour 35 marqués, ok', 'c'], [/resistances des enroulements/, 'C-S en circuit ouvert, enroulement coupé']],
        attendu: /compresseur en defaut/ }),
    A('av2-06', 'CTA en alarme filtre', 'CTA du restaurant : alarme pressostat filtre et débit d air faible dans la salle',
      { faits: [[/code/, 'non']],
        controles: [[/etat des filtres/, 'filtres à poches complètement colmatés']],
        attendu: /filtres ou echangeurs/ }),
    A('av2-07', 'Table tournante bloquée, distributeur commandé', 'table tournante pneumatique sur automate : elle ne tourne plus, le voyant du distributeur est allumé à la commande, il y a de l air',
      { faits: [[/code/, 'non']],
        controles: [[/etape active/, 'l automate attend le capteur table en position : pas bon'], [/borne de sortie de l.automate/, '24 V partout, ok', 'c'], [/resistance de la bobine/, 'bobine bonne', 'c'],
          [/commande manuelle/, 'même à la commande manuelle rien ne bouge alors qu il y a de l air : pas bon'], [/presenter la piece/, 'capteur bon', 'c']],
        attendu: /distributeur/ }),
    A('av2-08', 'Barrière levante qui reste levée', 'barrière levante du parking reste levée en permanence après le passage d une voiture',
      { faits: [[/code/, 'non']],
        controles: [[/boucle/, 'la boucle magnétique au sol reste en détection, câble de boucle abîmé par les travaux de voirie']],
        attendu: /boucle/ }),
    A('av2-09', 'Ventouse du hall qui ne colle plus', 'porte du hall : la ventouse ne colle plus du tout, la porte est libre, le lecteur est éteint aussi',
      { faits: [[/code/, 'non']],
        controles: [[/sortie de l.alimentation/, 'aucune tension en sortie de l alimentation : pas bon'], [/son fusible/, 'fusible secteur de l alimentation fondu']],
        attendu: /alimentation/ }),
    A('av2-10', 'ECS qui bipe en défaut batterie', 'ECS : défaut batterie affiché et ça bipe, le reste est normal',
      { faits: [[/code/, 'non']],
        controles: [[/tension secteur a l.arrivee/, 'secteur présent, charge à 27 V, ok', 'c'], [/date des batteries/, 'batteries de 2017 gonflées, la tension tombe à 18 V secteur coupé']],
        attendu: /batteries/ }),
    A('av2-11', 'Alarmes de nuit sur le détecteur de la chaufferie', 'alarme incendie qui part toute seule la nuit, toujours le détecteur de la chaufferie, pas de feu',
      { faits: [[/code/, 'non']],
        controles: [[/niveau d.encrassement/, 'toujours le détecteur de la chaufferie, encrassement à 85 % : pas bon'], [/chambre/, 'chambre pleine de suie'], [/heures des alarmes/, 'pas de lien avec une activité', 'c']],
        attendu: /detecteur encrasse/ }),
    A('av2-12', 'Tous les blocs de secours d’un couloir éteints', 'tous les blocs de secours du couloir du 2e sont éteints, voyant de charge éteint, les autres étages sont bons',
      { faits: [[/code/, 'non']],
        controles: [[/couper l.alimentation du bloc/, 'ils ne s allument pas'], [/presence du secteur aux bornes du bloc/, 'pas de secteur aux bornes des blocs : le disjoncteur du circuit est déclenché']],
        attendu: /non aliment|secteur|alimentation/ }),
    A('av2-13', 'Compresseur à vis qui s’arrête en température', 'compresseur d air à vis : il s arrête en défaut température haute l après-midi',
      { controles: [[/refroidisseur|radiateur|ventilation/, 'radiateur d huile colmaté par la poussière']],
        attendu: /refroid|radiateur/ }),
    A('av2-14', 'Vérin qui tape en fin de course', 'le vérin pneumatique du poussoir tape fort en fin de course depuis quelques jours, ça fait vibrer le bâti',
      { controles: [[/amortissement|limiteur/, 'vis d amortissement de fin de course déréglée, joint d amortisseur usé']],
        attendu: /amortissement|limiteur/ }),
    A('av2-15', 'Chaîne de convoyeur qui claque', 'convoyeur à rouleaux : la chaîne d entraînement claque et saute par moments',
      { controles: [[/fleche de la chaine/, 'chaîne très détendue, pignon aux dents crochues']],
        attendu: /chaine de transmission/ }),
    A('av2-16', 'Presse lente à froid', 'presse hydraulique très lente le matin, ça va mieux après une heure de marche',
      { controles: [[/viscosite|temperature d.huile|rechauff/, 'huile trop visqueuse à froid, le réchauffeur du réservoir ne fonctionne plus']],
        attendu: /viscosite|rechauffeur|huile froide/ }),
    A('av2-17', 'Disjoncteur de la cuisine qui saute au bout de 20 minutes', 'tableau de la cuisine : le disjoncteur 32 A saute au bout de 20 min quand tout est allumé, pas le différentiel',
      { controles: [[/courant absorbe/, '36 A mesurés quand tout est allumé'], [/recenser les recepteurs/, 'plaque et four ajoutés sur le même circuit : puissance trop élevée']],
        attendu: /surcharge du circuit/ }),
    A('av2-18', 'Éclairage extérieur allumé en plein jour', 'l éclairage extérieur du site reste allumé toute la journée',
      { controles: [[/forcer la marche/, 'la cellule crépusculaire est recouverte de peinture, elle voit toujours la nuit : pas bon']],
        attendu: /eclairage non commande/ }),
    A('av2-19', 'Ventilateur d’extraction bruyant', 'ventilateur d extraction de la cuisine : gros bruit de roulement et ça chauffe côté turbine',
      { controles: [[/ecouter chaque palier/, 'bruit sec côté turbine, palier chaud : pas bon'], [/tourner l.arbre a la main|faire tourner l.arbre/, 'jeu important et point dur']],
        attendu: /roulement/ }),
    A('av2-20', 'Variateur en défaut de terre', 'variateur du ventilateur de la tour : défaut F0021 défaut de terre en sortie, il ne démarre plus',
      { faits: [[/quel code/, 'F0021'], [/code/, 'oui F0021 défaut de terre']],
        controles: [[/code defaut affiche par le variateur/, 'F0021 défaut de terre à chaque démarrage : pas bon'], [/ensemble cable \+ moteur/, 'câble débranché du variateur : 0,01 MΩ'],
          [/cable debranche aux deux/, 'câble seul : 0,01 MΩ, il est écrasé dans le chemin de câbles'], [/moteur deconnecte/, 'moteur seul : > 500 MΩ', 'c'], [/separement/, 'câble seul : 0,01 MΩ, écrasé dans le chemin de câbles']],
        attendu: /isolement du cable|defaut de terre en sortie/ }),
    A('av2-21', 'Surpresseur qui ne s’arrête plus', 'surpresseur : la pompe tourne sans jamais s arrêter, pourtant la pression monte bien',
      { controles: [[/pressions reelles d.enclenchement/, 'le manomètre monte à 5 bar mais le pressostat réglé à 4 ne coupe pas : pas bon'], [/contacts du pressostat/, 'prise de pression du pressostat bouchée par le tartre']],
        attendu: /pressostat/ }),
    A('av2-22', 'Gainable qui disjoncte depuis l’orage', 'gainable du plateau : le disjoncteur saute direct à la mise sous tension depuis l orage',
      { faits: [[/code/, 'non'], [/combien de temps/, 'immédiatement'], [/differentiel/, 'non']],
        controles: [[/resistance entre phase et neutre/, '0,2 Ω entre phase et neutre côté unité extérieure'], [/parcours du cable/, 'varistance et carte de puissance de l unité extérieure éclatées']],
        attendu: /court.circuit/ }),
    A('av2-23', 'Four de boulangerie qui fait sauter le différentiel', 'four de la boulangerie fait sauter le différentiel quand il chauffe',
      { faits: [[/combien de temps/, 'après quelques minutes de chauffe']],
        controles: [[/un par un/, 'c est le four qui fait sauter'], [/appareil identifie/, 'résistance de sole : 0,01 MΩ à la masse'], [/recepteurs debranches/, '> 100 MΩ', 'c']],
        attendu: /recepteur defectueux|defaut d.isolement/ }),
    A('av2-24', 'Station déportée muette après l’orage', 'automate : défaut sur la station d entrées sorties déportée 2 après l orage, led rouge sur le coupleur, la ligne est arrêtée',
      { faits: [[/code/, 'non']],
        controles: [[/led de diagnostic reseau/, 'le coupleur de la station 2 ne répond plus, LED rouge fixe : pas bon'], [/connecteurs du participant absent/, 'câbles bons mais le coupleur n est plus alimenté, son alimentation interne est grillée : pas bon']],
        attendu: /communication reseau/ }),
    A('av2-25', 'Température de four figée', 'la température du four de traitement affiche 850 degrés fixe alors qu il est froid, la régulation est bloquée',
      { faits: [[/code/, 'non']],
        controles: [[/thermocouple|sonde/, 'thermocouple coupé dans sa gaine']],
        attendu: /thermocouple|sonde/ }),
    A('av2-26', 'Porte qui s’ouvre pour tous les badges', 'contrôle d accès du local serveur : la porte s ouvre pour tout le monde, même les badges qui n ont pas le droit',
      { faits: [[/code/, 'non']],
        controles: [[/motif du refus/, 'aucun refus au journal : la porte est en plage de libre accès permanente dans le logiciel, mauvais horaire']],
        attendu: /droits ou parametrage/ }),
    A('av2-27', 'Interphone du bâtiment C muet', 'interphone du bâtiment C : plus personne n entend sonner quand on appelle de la platine',
      { faits: [[/code/, 'non']],
        controles: [[/appeler plusieurs logements/, 'aucun poste ne sonne dans le bâtiment : pas bon'], [/tension du bus/, 'aucune tension sur le bus, l alimentation de la colonne est HS']],
        attendu: /interphonie/ }),
    A('av2-28', 'Exutoire qui ne se referme pas', 'désenfumage : l exutoire de la cage d escalier ne se referme pas après l essai',
      { faits: [[/code/, 'non']],
        controles: [[/commander le das/, 'l ordre de fermeture arrive mais l exutoire reste ouvert : pas bon'], [/declencheur du das/, 'vérin de l exutoire grippé, tige oxydée']],
        attendu: /das qui ne change pas/ }),
    A('av2-29', 'Malaxeur qui s’arrête dès qu’on lâche le bouton', 'le malaxeur démarre quand j appuie sur marche et s arrête dès que je lâche le bouton',
      { controles: [[/auto-maintien/, 'contact 13-14 oxydé, pas de continuité']],
        attendu: /auto-maintien/ }),
    A('av2-30', 'Radiateurs du dernier étage froids', 'chauffage : les radiateurs du dernier étage sont froids avec des bruits d eau, en bas ça chauffe',
      { faits: [[/code/, 'non']],
        controles: [[/purger les radiateurs/, 'beaucoup d air à la purge des radiateurs du haut, pression à 0,6 bar : pas bon'], [/bouchon de degommage/, 'le circulateur tourne librement mais il y a beaucoup d air à la purge : pas bon'], [/tuyauteries d.arrivee/, 'arrivée tiède, plein d air dans les radiateurs du haut : pas bon']],
        attendu: /air|purge/ })
  ];
};
