'use strict';
/* Banque de cas — série « à l'aveugle » : écrite après la mise au point, jouée une première fois telle quelle
 * pour mesurer ce que le moteur local sait faire sur des pannes qu'il n'a jamais vues. Le résultat de ce premier
 * passage est consigné dans PROGRESS.md. Les cas restent ensuite dans la banque comme non-régression. */
module.exports = function (cas) {
  const A = function (id, titre, description, o) { return cas(id, 'aveugle', titre, description, Object.assign({ aveugle: true }, o)); };
  return [
    A('avg-01', 'Compresseur d’air qui disjoncte au démarrage par temps froid', 'Le compresseur d air de l atelier disjoncte au démarrage le matin quand il fait froid, l après-midi il démarre',
      { faits: [[/combien de temps/, 'tout de suite au démarrage'], [/differentiel/, 'non'], [/plaque/, '7,5 kW 15 A étoile triangle']],
        controles: [[/decharge d.air a la tete/, 'pas de décharge à l arrêt, il redémarre contre la pression : pas normal'], [/clapet de decharge de la tete/, 'électrovanne de mise à vide bloquée fermée']],
        attendu: /mise a vide|demarrage en charge/ }),
    A('avg-02', 'Disjoncteur général chaud', 'TGBT : le disjoncteur général est chaud au toucher côté gauche, légère odeur, rien ne déclenche',
      { controles: [[/thermographie/, 'plage amont L1 à 120 °C, les deux autres à 50 °C'], [/serrage au couple/, 'vis de plage desserrée, cuivre bleui']],
        attendu: /connexion desserree/ }),
    A('avg-03', 'Prises d’un bureau hors service', 'les prises du bureau 12 ne marchent plus, le reste de l étage marche, aucun disjoncteur tombé',
      { controles: [[/amont et en aval/, '230 V en amont et en aval du disjoncteur des prises, ok', 'c'], [/prise|repiquage|boite/, 'fil de phase sorti de la borne dans la première prise du bureau, repiquage brûlé']],
        attendu: /connexion|repiquage|coupure/ }),
    A('avg-04', 'Moteur de convoyeur qui claque', 'moteur du convoyeur 2 vibre fort depuis hier avec un bruit de claquement régulier',
      { controles: [[/alignement moteur/, 'élastomère de l accouplement détruit, les doigts cognent métal contre métal'], [/ecouter chaque palier/, 'paliers normaux, le bruit vient de l accouplement', 'c']],
        attendu: /accouplement/ }),
    A('avg-05', 'Pompe à chaleur en défaut U4', 'PAC air air : l unité intérieure affiche U4 et rien ne démarre, depuis ce week-end',
      { faits: [[/quel code/, 'U4'], [/code/, 'oui U4']],
        controles: [[/bornier de liaison/, 'pas de signal sur la borne 3 côté unité extérieure, présent côté intérieure : pas bon'], [/cable de liaison/, 'fil 3 coupé, rongé dans le comble']],
        attendu: /communication/ }),
    A('avg-06', 'Ventilo-convecteur qui souffle froid', 'ventilo-convecteur salle de réunion : ça souffle bien mais pas chaud, les autres pièces chauffent',
      { faits: [[/code/, 'non']],
        controles: [[/filtre/, 'filtre propre', 'c'], [/tuyauteries d.arrivee/, 'tuyau chaud avant la vanne, froid après et retour froid : pas bon'], [/vanne de regulation/, 'la vanne 2 voies ne s ouvre pas, sa tête thermique est grillée']],
        attendu: /vanne/ }),
    A('avg-07', 'Chaudière gaz en sécurité, pas d’étincelle', 'chaudière gaz se met en sécurité à chaque demande, on entend pas l étincelle',
      { faits: [[/code/, 'non']],
        controles: [[/observer la sequence/, 'préventilation ok mais pas d étincelle, mise en sécurité : pas bon'], [/electrodes/, 'électrode d allumage fêlée, câble haute tension percé']],
        attendu: /bruleur en securite/ }),
    A('avg-08', 'Pompe de relevage qui fait sauter disjoncteur et différentiel', 'pompe de relevage du parking : le disjoncteur et le différentiel sautent dès qu elle démarre',
      { faits: [[/combien de temps/, 'immédiatement'], [/plaque/, '1,5 kW 3,5 A']],
        controles: [[/ensemble cable \+ moteur/, '0,05 MΩ depuis le coffret'], [/moteur deconnecte/, 'pompe seule : 0,04 MΩ, de l eau est entrée par le presse-étoupe du câble'], [/isolement/, '0,05 MΩ']],
        attendu: /isolement/ }),
    A('avg-09', 'Pompe de piscine qui fait un bruit de gravier', 'la pompe de filtration de la piscine fait un bruit de gravier et le débit a baissé',
      { controles: [[/depression a l.aspiration/, 'vacuomètre à -0,7 bar, beaucoup trop'], [/crepine/, 'panier du préfiltre plein de feuilles'], [/npsh|pression a l.aspiration/, 'dépression de -0,7 bar à l aspiration, pas bon']],
        attendu: /crepine|cavitation/ }),
    A('avg-10', 'Portail qui s’ouvre seul la nuit', 'le portail du site s ouvre tout seul la nuit, 2 ou 3 fois par semaine',
      { faits: [[/code/, 'non']],
        controles: [[/cellule/, 'cellules ok', 'c'], [/entrees de commande/, 'les ouvertures s arrêtent quand je débranche le contacteur à clé extérieur : pas normal'], [/inspecter l.organe designe/, 'le contacteur à clé extérieur est plein d eau, contact oxydé']],
        attendu: /contacteur a cle|commande|bouton/ }),
    A('avg-11', 'Gâche du portillon muette, badge accepté', 'gâche du portillon fait plus rien au badge, pourtant led verte au lecteur',
      { faits: [[/code/, 'non']],
        controles: [[/tension aux bornes de la gache/, 'aucune tension à la gâche à l ordre'], [/sortie du relais/, '12 V en sortie du relais de la centrale mais fil coupé au passage de porte'], [/resistance de sa bobine/, 'bobine bonne, 22 Ω', 'c']],
        attendu: /commande de deverrouillage/ }),
    A('avg-12', 'Volet de désenfumage qui ne s’ouvre pas à l’essai', 'SSI : le volet de désenfumage de la cage B n a pas ouvert à l essai annuel, défaut au CMSI',
      { faits: [[/code/, 'non']],
        controles: [[/position reelle/, 'le volet reste fermé à la commande, pas normal'], [/contacts de debut et de fin de course/, 'contacts bons', 'c'], [/declencheur|ventouse|commande du das/, 'déclencheur électromagnétique du volet grippé, il ne libère pas']],
        attendu: /declencheur|das/ }),
    A('avg-13', 'Point absent sur une boucle adressable', 'ECS adressable : dérangement point absent sur le détecteur 2.14 depuis le ménage de printemps',
      { faits: [[/code/, 'non']],
        controles: [[/socle par socle/, 'détecteur 2.14 mal verrouillé dans son socle'], [/point en alarme|niveau d.encrassement/, 'le 2.14 est vu absent, mal verrouillé dans son socle, pas normal'], [/chambre/, 'détecteur mal verrouillé dans son socle']],
        attendu: /detecteur|ligne de detection/ }),
    A('avg-14', 'Robot arrêté en défaut pression d’air', 'robot palettiseur s arrête en défaut pression air plusieurs fois par heure',
      { faits: [[/code/, 'non']],
        controles: [[/pression au reseau/, '4,2 bar à la machine en cycle pour 6 demandés, pas bon'], [/filtre du groupe de conditionnement/, 'grosse fuite sur un raccord du préhenseur']],
        attendu: /pression d.air/ }),
    A('avg-15', 'Pupitre qui s’éteint par moments', 'l écran du pupitre de la ligne 3 devient noir par moments puis revient, l automate continue de tourner',
      { faits: [[/code/, 'non']],
        controles: [[/en sortie d.alimentation/, '24,1 V stable, ok', 'c'], [/connecteur|pupitre|ecran/, 'connecteur d alimentation de l écran desserré à l arrière']],
        attendu: /connecteur|pupitre|ecran/ }),
    A('avg-16', 'Cellule de comptage qui rate des pièces', 'la cellule de comptage en sortie de ligne rate des pièces, le compteur est faux',
      { faits: [[/code/, 'non']],
        controles: [[/etape active/, 'rien de bloqué', 'c'], [/presenter la piece/, 'lentille de la cellule encrassée de poussière, détection irrégulière']],
        attendu: /capteur deregle/ }),
    A('avg-17', 'Variateur de pompe en surintensité au démarrage', 'variateur de la pompe de reprise : défaut surintensité dès le démarrage, depuis l arrêt de 3 semaines',
      { faits: [[/quel code/, 'OC1'], [/code/, 'oui OC1 surintensité']],
        controles: [[/code defaut affiche par le variateur/, 'OC1 surintensité à l accélération à chaque essai, pas bon'], [/rampe d.acceleration/, 'désaccouplé le moteur démarre bien : la pompe est bloquée par le calcaire']],
        attendu: /surintensite/ }),
    A('avg-18', 'Un tube sur deux éteint', 'éclairage atelier : dans la rangée 3 deux luminaires restent éteints, les autres s allument',
      { controles: [[/source neuve/, 'avec un tube neuf ça ne s allume pas non plus, ballast HS']],
        attendu: /lampe, luminaire/ }),
    A('avg-19', 'Différentiel qui saute au démarrage du poste à souder', 'le différentiel de l atelier soudure saute dès que le poste TIG démarre',
      { faits: [[/combien de temps/, 'immédiatement']],
        controles: [[/un par un/, 'c est le poste TIG qui fait sauter, sans lui tout tient'], [/recepteurs debranches/, 'circuit seul : > 100 MΩ', 'c'], [/appareil identifie/, 'poste TIG : 0,1 MΩ à la masse']],
        attendu: /recepteur defectueux/ }),
    A('avg-20', 'Plus d’eau chaude au chauffe-eau', 'chauffe-eau électrique 300 L des vestiaires : plus d eau chaude depuis hier, le disjoncteur est enclenché',
      { controles: [[/intensite/, '0 A en chauffe sur les 3 phases, pas bon'], [/element chauffant/, 'thermostat de sécurité déclenché, résistance entartrée et coupée'], [/amont et en aval/, '400 V en amont et en aval, ok', 'c']],
        attendu: /element chauffant/ }),
    A('avg-21', 'Réducteur du tapis qui perd son huile', 'réducteur du tapis d alimentation : flaque d huile dessous et il chauffe',
      { controles: [[/huile du reducteur/, 'niveau très bas, joint d arbre de sortie qui fuit']],
        attendu: /reducteur/ }),
    A('avg-22', 'Flexible de presse qui fuit', 'presse à balles : de l huile gicle au niveau du vérin principal quand elle monte en pression',
      { controles: [[/flexibles/, 'flexible du vérin principal avec une hernie, il fuit au sertissage']],
        attendu: /fuite hydraulique/ }),
    A('avg-23', 'Moteur de ventilation de parking qui ne démarre pas', 'moteur de ventilation du parking ne démarre pas, le contacteur colle bien, ça bourdonne',
      { faits: [[/differentiel/, 'non'], [/combien de temps/, 'il ne démarre pas du tout']],
        controles: [[/trois tensions entre phases/, 'L1-L2 : 400 V · L2-L3 : 0 V · L1-L3 : 230 V'], [/continuite de chaque phase/, 'pôle L3 du contacteur brûlé, plus de continuité']],
        attendu: /perte de phase/ }),
    A('avg-24', 'Clim murale qui coule', 'clim murale de la chambre 8 : de l eau coule le long du mur sous l unité intérieure',
      { faits: [[/code/, 'non']],
        controles: [[/pente de l.evacuation/, 'bac plein, évacuation bouchée par des algues']],
        attendu: /evacuation des condensats/ }),
    A('avg-25', 'Évaporateur givré, ventilateur à l’arrêt', 'vitrine réfrigérée : ça ne fait plus de froid, l évaporateur est tout givré et on n entend plus le ventilateur',
      { faits: [[/code/, 'non']],
        controles: [[/rotation du ventilateur/, 'ventilateur de l évaporateur à l arrêt alors qu il est alimenté, pas bon'], [/helice a la main/, 'moteur du ventilateur bloqué, enroulement coupé'], [/pressions hp/, 'pas mesuré'], [/filtres/, 'propre', 'c']],
        attendu: /moto-ventilateur/ }),
    A('avg-26', 'Pompe qui marche en manuel mais pas en automatique', 'coffret de relevage : la pompe ne démarre pas en auto, elle marche en manu, fosse pleine',
      { controles: [[/basculer le flotteur/, 'aucun changement d état quand je bascule le flotteur : fil coupé dans le câble'], [/liberte du flotteur/, 'flotteur libre', 'c']],
        attendu: /flotteur/ }),
    A('avg-27', 'Pompe jockey qui démarre toutes les deux minutes', 'surpresseur incendie RIA : la pompe jockey démarre toutes les 2 minutes sans que personne ne tire d eau',
      { controles: [[/pression de gonflage/, 'ok', 'c'], [/vanne de refoulement vers le reseau fermee/, 'vanne fermée la pression tient, donc ça fuit sur le réseau', 'c'], [/vannes de sectionnement/, 'quand je ferme la vanne du sous-sol la pression tient : pas normal'], [/sur le troncon designe/, 'un RIA du sous-sol goutte en permanence, robinet mal fermé']],
        attendu: /fuite|reseau/ }),
    A('avg-28', 'Fusibles de commande qui fondent à répétition', 'armoire de la station : le transformateur de commande grille son fusible à répétition, plus aucune commande',
      { controles: [[/secondaire du transformateur/, '0 V au secondaire, pas bon'], [/fusibles primaire et secondaire/, 'fusible secondaire fondu ; un fil de commande dénudé touche la porte de l armoire']],
        attendu: /absence de tension de commande/ }),
    A('avg-29', 'Badge refusé pour un salarié de retour de congé', 'le badge de M. Roux est refusé partout depuis son retour de congé, les autres badges passent',
      { faits: [[/code/, 'non']],
        controles: [[/motif du refus/, 'journal : badge expiré, date de validité dépassée']],
        attendu: /droits ou parametrage/ }),
    A('avg-30', 'Bande qui patine sur le tambour', 'convoyeur à bande : la bande patine sur le tambour moteur quand elle est chargée, le moteur tourne',
      { controles: [[/proprete des tambours/, 'bande détendue, tambour moteur lisse et gras : pas bon'], [/tension de la courroie/, 'courroie du moteur bonne', 'c']],
        attendu: /bande|tension/ })
  ];
};
