'use strict';
/* Banque de cas — troisième série « à l'aveugle » : écrite après la troisième passe d'enrichissement,
 * jouée une première fois telle quelle (résultat consigné dans PROGRESS.md), puis conservée comme non-régression. */
module.exports = function (cas) {
  const A = function (id, titre, description, o) { return cas(id, 'aveugle3', titre, description, Object.assign({ aveugle3: true }, o)); };
  return [
    A('av3-01', 'Prise d’atelier fondue', 'une prise de courant de l atelier chauffe, le plastique a fondu autour d une broche',
      { controles: [[/thermographie/, 'la prise à 85 °C, les autres à 30 °C'], [/serrage au couple/, 'borne de la prise desserrée, plastique fondu']],
        attendu: /connexion desserree/ }),
    A('av3-02', 'Onduleur qui bipe et passe en bypass', 'onduleur de la salle serveur : il bipe et passe en bypass plusieurs fois par jour',
      { controles: [[/batterie/, 'batteries de l onduleur de 6 ans, test batterie en échec']],
        attendu: /batterie|onduleur/ }),
    A('av3-03', 'Pompe doseuse qui ne débite plus', 'pompe doseuse de chlore : elle bat mais n injecte plus rien',
      { controles: [[/niveau du liquide/, 'bidon vide, la crépine est hors du liquide : pas bon'], [/etancheite de la conduite d.aspiration/, 'rien d autre', 'c']],
        attendu: /desamorcage/ }),
    A('av3-04', 'Sèche-mains qui souffle froid', 'sèche-mains des sanitaires : il souffle mais l air est froid',
      { controles: [[/intensite/, '0,4 A seulement, le ventilateur seul : pas bon'], [/element chauffant/, 'résistance coupée']],
        attendu: /element chauffant/ }),
    A('av3-05', 'Batterie de condensateurs en défaut', 'TGBT : la batterie de condensateurs est en défaut, le cos phi est mauvais et on paie du réactif',
      { controles: [[/condensateur|gradin/, 'deux gradins sur six ont leurs fusibles fondus, condensateurs gonflés']],
        attendu: /condensateur|gradin/ }),
    A('av3-06', 'Moteur qui tourne à l’envers après travaux', 'tous les moteurs de l armoire tournent à l envers depuis le remplacement du câble d alimentation de l armoire',
      { controles: [[/sens de rotation/, 'ils tournent à l envers de la flèche : pas bon'], [/ordre des phases/, 'ordre des phases inversé à l arrivée : pas bon']],
        attendu: /sens de rotation|controle de phases/ }),
    A('av3-07', 'Clim réversible qui souffle froid en mode chaud', 'clim réversible du bureau : en mode chaud elle souffle froid, en mode froid elle marche',
      { faits: [[/code/, 'non']],
        controles: [[/bobine de la vanne 4 voies/, '230 V présents à la bobine en demande de chaud, ok', 'c'], [/tubulures/, 'aucune bascule, les tubulures ne changent pas de température : vanne bloquée, pas bon']],
        attendu: /vanne 4 voies/ }),
    A('av3-08', 'Groupe d’eau glacée en défaut débit', 'groupe d eau glacée : défaut débit d eau au démarrage, il ne part pas',
      { faits: [[/code/, 'oui défaut débit'], [/quel code/, 'défaut débit eau']],
        controles: [[/ecart de temperature entre depart et retour/, '11 K d écart, beaucoup trop : pas bon'], [/filtre a tamis/, 'tamis colmaté par la boue']],
        attendu: /debit d.eau/ }),
    A('av3-09', 'Soupape de chaudière qui crache', 'chaudière du gymnase : la pression monte à 3 bar en chauffe et la soupape crache',
      { faits: [[/code/, 'non']],
        controles: [[/a froid puis a chaud/, '1 bar à froid, 3 bar à chaud : pas bon'], [/pression de gonflage/, '0 bar à la valve, vase dégonflé']],
        attendu: /vase d.expansion/ }),
    A('av3-10', 'VMC double flux bruyante', 'VMC double flux : gros bruit et vibrations dans le caisson depuis une semaine',
      { faits: [[/code/, 'non']],
        controles: [[/rotation du ventilateur/, 'il tourne mais avec un gros bruit de roulement : pas bon'], [/helice a la main/, 'roulement du moteur d extraction rugueux, jeu important'],
          [/ecouter chaque palier/, 'bruit de roulement net sur le moteur d extraction : pas bon'], [/tourner l.arbre a la main|faire tourner l.arbre/, 'roulement rugueux, jeu important']],
        attendu: /moto-ventilateur|roulement/ }),
    A('av3-11', 'Bouton départ cycle sans effet', 'machine sur automate : le bouton départ cycle ne fait plus rien, pas de défaut affiché',
      { faits: [[/code/, 'non']],
        controles: [[/etape active/, 'l automate attend le bouton départ cycle : pas bon'], [/borne d.entree de l.automate/, 'aucune tension à la borne d entrée quand on appuie'],
          [/continuite de chaque fil/, 'fil du bouton coupé au passage de la porte du pupitre'], [/presenter la piece/, 'rien à signaler', 'c']],
        attendu: /liaison capteur|capteur deregle|bouton/ }),
    A('av3-12', 'Recettes perdues après une coupure', 'ligne de dosage : toutes les recettes sont à zéro après la coupure de courant de cette nuit, voyant BATT allumé sur l automate',
      { faits: [[/code/, 'non']],
        controles: [[/voyants de l.automate/, 'voyant BATT allumé, données perdues : pas bon'], [/pile ou la carte memoire/, 'pile à plat']],
        attendu: /automate en stop/ }),
    A('av3-13', 'Badge accepté mais porte qui reste collée', 'porte de la réserve : le lecteur passe au vert mais la porte ne s ouvre pas, la ventouse reste collée',
      { faits: [[/code/, 'non']],
        controles: [[/a l.ordre d.ouverture/, 'la ventouse reste alimentée à l ordre d ouverture : pas bon'], [/sortie du relais/, 'le relais de la centrale ne commute plus, contact collé']],
        attendu: /commande de deverrouillage/ }),
    A('av3-14', 'Portail dont le moteur tourne dans le vide', 'portail coulissant : on entend le moteur tourner mais le portail ne bouge pas',
      { faits: [[/code/, 'non']],
        controles: [[/a la main/, 'à la main il coulisse bien', 'c'], [/debray|pignon|cremaillere/, 'le moteur est resté débrayé, la clé de déverrouillage n a pas été remise']],
        attendu: /debray|pignon|cremaillere/ }),
    A('av3-15', 'Visiophone sans image', 'visiophone de la résidence : plus d image sur les postes, le son et l ouverture marchent',
      { faits: [[/code/, 'non']],
        controles: [[/appeler plusieurs logements/, 'pas d image sur aucun poste : pas bon'], [/tension du bus/, 'tension correcte sur le bus', 'c']],
        attendu: /interphonie/ }),
    A('av3-16', 'Ligne de sirènes en dérangement après travaux', 'SSI : dérangement sur la ligne des sirènes du 1er depuis la pose du faux plafond',
      { faits: [[/code/, 'non']],
        controles: [[/ligne de diffuseurs deconnectee/, 'court-circuit sur la ligne, 2 Ω : pas bon'], [/diffuseurs un par un/, 'câble pincé par une ossature du faux plafond']],
        attendu: /diffuseurs/ }),
    A('av3-17', 'Détecteur du réfectoire en alarme à chaque service', 'le détecteur de la cuisine du réfectoire part en alarme à chaque service',
      { faits: [[/code/, 'non']],
        controles: [[/heures des alarmes/, 'à chaque service, midi et soir : pas bon'], [/environnement du detecteur/, 'détecteur optique juste au-dessus du four mixte : pas bon'],
          [/niveau d.encrassement/, 'toujours le même, encrassement normal', 'c']],
        attendu: /detecteur inadapte/ }),
    A('av3-18', 'Défaut de ligne de télécommande d’une porte coupe-feu', 'CMSI : défaut ligne de télécommande sur la porte coupe-feu n°3 du sous-sol',
      { faits: [[/code/, 'non']],
        controles: [[/ventouse de porte/, 'aucune tension à la ventouse, la porte ne tient plus ouverte'], [/observer sa fermeture complete/, 'elle se ferme bien', 'c'],
          [/commander le das/, 'aucun ordre n arrive à la porte : pas bon'], [/declencheur du das/, 'fil de la ligne de télécommande coupé dans une boîte de dérivation']],
        attendu: /das|porte coupe-feu/ }),
    A('av3-19', 'Soupape du compresseur qui crache', 'compresseur d air : la soupape de sécurité de la cuve crache, il ne s arrête pas à 10 bar',
      { controles: [[/pressostat/, 'le pressostat ne coupe plus, contacts collés']],
        attendu: /pressostat/ }),
    A('av3-20', 'Convoyeur bloqué, thermique qui saute', 'convoyeur de sortie : le moteur grogne et le relais thermique saute au bout d une minute',
      { faits: [[/plaque/, '4 kW 8,5 A direct, thermique réglé à 8,5 A'], [/differentiel/, 'non']],
        controles: [[/intensite sur chaque phase/, 'L1 : 18 A · L2 : 18,3 A · L3 : 17,9 A, très au-dessus de la plaque'], [/tourner l.arbre a la main/, 'impossible de tourner à la main, réducteur bloqué']],
        attendu: /surcharge mecanique|reducteur/ }),
    A('av3-21', 'Vérin de presse qui fuit à la tige', 'presse hydraulique : de l huile coule le long de la tige du vérin principal',
      { controles: [[/flexibles/, 'joint de tige du vérin qui fuit, tige rayée']],
        attendu: /fuite hydraulique/ }),
    A('av3-22', 'Machine qui s’arrête quand on claque la porte', 'machine d usinage : elle s arrête de façon aléatoire, le relais de sécurité retombe quand on ferme fort la porte',
      { controles: [[/module de securite/, 'le canal 2 s ouvre par moments : pas bon'], [/protecteur designe/, 'interrupteur de porte mal fixé, il bouge'], [/continuite de chaque canal/, 'interrupteur de porte mal fixé, contact instable : pas bon']],
        attendu: /securite/ }),
    A('av3-23', 'Pompe à vide qui ne fait plus le vide', 'pompe à vide de la thermoformeuse : elle tourne mais le vide ne descend plus',
      { controles: [[/palette|huile de la pompe a vide|filtre/, 'palettes usées et huile noire']],
        attendu: /palette|pompe a vide/ }),
    A('av3-24', 'Différentiel impossible à réarmer', 'un interrupteur différentiel du tableau refuse de se réarmer, même avec tous les disjoncteurs en dessous coupés',
      { faits: [[/combien de temps/, 'immédiatement']],
        controles: [[/rearmer hors charge/, 'même avec l aval déconnecté il ne se réarme pas : pas bon'], [/circuits un par un/, 'il ne se réarme même pas tout coupé : pas bon']],
        attendu: /appareil de protection/ }),
    A('av3-25', 'Luminaire LED qui clignote', 'bureau 4 : un des luminaires LED clignote, les autres sont normaux',
      { controles: [[/source neuve/, 'driver LED HS']],
        attendu: /lampe, luminaire/ }),
    A('av3-26', 'Disjoncteur moteur qui saute une fois sur trois au démarrage', 'le disjoncteur du ventilateur saute au démarrage une fois sur trois, sinon il tourne normalement toute la journée',
      { faits: [[/combien de temps/, 'immédiatement, au démarrage'], [/differentiel/, 'non'], [/plaque/, '11 kW 21 A démarrage direct']],
        controles: [[/courant d.appel/, 'pointe à 9 fois l intensité nominale, au-dessus du seuil magnétique : pas bon'], [/absence de court-circuit du recepteur/, 'moteur et câble bons', 'c']],
        attendu: /protection inadaptee/ }),
    A('av3-27', 'Pompe de relevage qui tourne sans vider', 'relevage : la pompe tourne mais le niveau de la fosse ne baisse pas',
      { controles: [[/pression au refoulement en marche/, 'pression au maximum, débit nul : pas bon'], [/suivre le refoulement/, 'clapet anti-retour bloqué fermé par un chiffon']],
        attendu: /refoulement obstrue/ }),
    A('av3-28', 'Clim en défaut haute pression en plein soleil', 'clim du local technique : défaut haute pression l après-midi quand le soleil tape sur l unité extérieure',
      { faits: [[/code/, 'oui haute pression'], [/quel code/, 'HP']],
        controles: [[/temperature de condensation/, '62 °C de condensation pour 34 °C dehors : pas bon'], [/batterie du condenseur/, 'ventilateur du condenseur à l arrêt']],
        attendu: /condenseur/ }),
    A('av3-29', 'Contacteurs qui collent mal le matin', 'armoire de la station : les voyants sont faibles et les contacteurs collent mal le matin',
      { controles: [[/a1-a2 de sa bobine/, '18 V pour une bobine 24 V : pas bon'], [/a vide puis avec tous/, '21 V à vide seulement, le transformateur est fatigué : pas bon']],
        attendu: /tension de commande trop faible/ }),
    A('av3-30', 'Porte automatique de magasin qui reste ouverte', 'porte automatique coulissante du magasin : elle reste ouverte en permanence',
      { faits: [[/code/, 'non']],
        controles: [[/radar|detecteur de presence|cellule/, 'le radar de détection reste activé par une affiche qui bouge devant']],
        attendu: /radar|detecteur de presence|porte automatique/ })
  ];
};
