'use strict';
/* Banque de cas — « terrain » : descriptions courtes, écrites comme sur un bon d'intervention ou un SMS,
 * sans se soucier des mots de la base de pannes. Les réponses sont rangées par type de mesure
 * (« si on me demande un isolement… »), pas par contrôle précis. Une partie des causes n'était pas
 * dans la base au moment de l'écriture : cette série sert à mesurer honnêtement, puis à enrichir. */
module.exports = function (cas) {
  const T = function (id, titre, description, o) { return cas(id, 'terrain', titre, description, Object.assign({ terrain: true }, o)); };
  return [
    T('ter-01', 'Clim qui souffle tiède', 'clim bureau direction souffle plus froid, ça tourne mais air tiède. unité ext tourne. le client dit que ça fait 2 semaines',
      { faits: [[/code/, 'non'], [/reference/, 'Daikin RXS35']],
        controles: [[/pression|manifold/, 'BP 3 bar, HP 14 bar, surchauffe 22 K, c est pas bon'], [/fuite/, 'huile sur la vanne de service et ça bulle au produit moussant'], [/filtre/, 'filtres ok', 'c']],
        attendu: /manque de fluide/ }),
    T('ter-02', 'Différentiel de la chambre froide qui saute la nuit', 'le différentiel de la chambre froide saute la nuit vers 2h, pas toutes les nuits. le matin on réarme et ça tient la journée',
      { faits: [[/code/, 'non'], [/combien de temps/, 'aléatoire, la nuit vers 2h, c est l heure du dégivrage']],
        controles: [[/un par un/, 'ça saute quand je lance le dégivrage, donc le départ des résistances de dégivrage'], [/isolement/, 'résistance de dégivrage du bas : 0,03 MΩ à la masse'],
          [/degivrage manuel/, 'dès que je lance le dégivrage le différentiel saute'], [/chaque resistance/, 'résistance du bas à la masse, 0,03 MΩ, les autres bonnes']],
        attendu: /isolement|recepteur defectueux|degivrage/ }),
    T('ter-03', 'Moteur de pompe brûlant qui disjoncte', 'Moteur pompe piscine municipale disjoncte au bout de 10 min, il est brulant. pompe changée l an dernier',
      { faits: [[/plaque/, '3 kW 6,5 A direct, relais réglé 6,5 A'], [/differentiel/, 'non']],
        controles: [[/intensite/, 'L1 : 6,1 A · L2 : 6,0 A · L3 : 6,2 A, c est sous la plaque, conforme', 'c'], [/capot|ailette/, 'le ventilateur plastique en bout d arbre est cassé, plus de pales']],
        attendu: /ventilation du moteur/ }),
    T('ter-04', 'Portail qui ne ferme pas à fond', 'portail battant motorisé ferme pas a fond, il reste entrouvert de 20 cm coté droit',
      { faits: [[/code/, 'non']],
        controles: [[/cellule/, 'cellules ok voyant allumé', 'c'], [/a la main|debraye/, 'à la main il va jusqu au bout sans forcer', 'c'], [/fin de course|butee|course/, 'la butée de fermeture du vantail droit a glissé sur le bras, la course est trop courte']],
        attendu: /fin de course|butee|course/ }),
    T('ter-05', 'Plus de lumière dans les communs', 'plus de lumière dans les communs de la résidence B, les boutons poussoirs font rien, le disjoncteur est enclenché',
      { controles: [[/amont et en aval/, '230 V en amont et en aval du disjoncteur, ok', 'c'], [/minuterie|telerupteur/, 'la minuterie ne colle plus quand on appuie, bobine grillée']],
        attendu: /minuterie|telerupteur/ }),
    T('ter-06', 'Variateur en défaut au freinage', 'Défaut variateur F0003 sur convoyeur 4, souvent quand il s arrête chargé',
      { faits: [[/quel code/, 'F0003'], [/code/, 'oui F0003']],
        controles: [[/code defaut|historique/, 'F0003 surtension, toujours à l arrêt du convoyeur chargé, pas bon'], [/deceleration|freinage/, 'rampe de décélération à 0,5 s, trop court, et pas de résistance de freinage']],
        attendu: /surtension du bus/ }),
    T('ter-07', 'Pompe de relevage qui tourne en permanence', 'pompe de relevage eaux pluviales tourne en permanence fosse vide, elle va griller',
      { controles: [[/flotteur/, 'la poire est coincée entre le tuyau et la paroi, en position haute']],
        attendu: /flotteur/ }),
    T('ter-08', 'Tous les badges refusés depuis ce matin', 'Badgeuse entrée personnel : bip rouge pour tout le monde depuis ce matin 6h, hier ça marchait',
      { faits: [[/code/, 'non'], [/observation complementaire/, 'les deux autres lecteurs du batiment refusent aussi tout le monde']],
        controles: [[/led de communication|en ligne/, 'le contrôleur de porte est hors ligne dans le logiciel, LED réseau éteinte, pas normal'], [/bus|ethernet/, 'câble réseau débranché du switch dans la baie'],
          [/badge de reference|journal|motif/, 'aucun événement dans le journal depuis 5h58, pas normal'], [/aux bornes du lecteur/, '12 V au lecteur, ok', 'c']],
        attendu: /communication/ }),
    T('ter-09', 'SSI en dérangement alimentation depuis l’orage', 'SSI : dérangement alimentation sur le tableau depuis l orage de mardi, sinon tout marche',
      { faits: [[/code/, 'non']],
        controles: [[/secteur|charge/, 'secteur 230 V présent à l arrivée mais 0 V en sortie du chargeur, batteries à 22 V : pas bon'], [/date des batteries/, 'batteries de 2 ans, elles tiennent', 'c']],
        attendu: /alimentation/ }),
    T('ter-10', 'Détecteur du local poubelles toujours en alarme', 'detecteur local poubelle en alarme feu 3 fois cette semaine, pas de feu, SSI adressable',
      { faits: [[/code/, 'non']],
        controles: [[/historique|point/, 'toujours le DI 34 local poubelles, encrassement à 92 %, pas bon'], [/chambre|aerosol/, 'plein de poussière et de toiles d araignée dedans'], [/environnement/, 'rien de spécial, local fermé', 'c']],
        attendu: /detecteur encrasse/ }),
    T('ter-11', 'Sectionneur général qui chauffe', 'armoire machine : le sectionneur général chauffe, traces noires sur un fil, odeur',
      { controles: [[/thermograph/, '110 °C sur la borne L2 aval du sectionneur, 40 °C sur les autres'], [/inspecter bornes|serrage au couple/, 'cosse mal sertie et noircie sur L2'], [/intensite sur chaque phase|courant absorbe/, 'L1 : 31 A · L2 : 30 A · L3 : 31 A, normal', 'c']],
        attendu: /connexion desserree/ }),
    T('ter-12', 'Vérin de presse qui redescend seul', 'vérin de la presse hydraulique redescend tout seul quand on lache la commande, 5 cm en 1 minute',
      { controles: [[/niveau|huile/, 'niveau ok huile propre', 'c'], [/pression/, '160 bar en butée comme au schéma', 'c'], [/derive/, 'il dérive de 5 cm par minute ; isolé à la vanne il tient, donc le clapet anti-retour piloté fuit : pas bon']],
        attendu: /clapet|fuite interne/ }),
    T('ter-13', 'Extracteur qui tourne à l’envers', 'moteur extracteur cuisine aspire plus rien depuis le changement du disjoncteur hier, il tourne pourtant',
      { controles: [[/sens/, 'il tourne à l envers de la flèche, pas bon']],
        attendu: /sens de rotation/ }),
    T('ter-14', 'Chaudière en manque d’eau tous les deux jours', 'chaudière en défaut manque d eau, pression 0,3 bar, je remets à 1,5 et 2 jours après pareil',
      { faits: [[/code/, 'manque d eau']],
        controles: [[/a froid puis a chaud/, '1,5 bar à froid, 1,7 à chaud, normal', 'c'], [/gonflage/, '1 bar au vase, ok', 'c'], [/fuite|reseau|radiateur|soupape/, 'purgeur automatique en chaufferie qui goutte en continu, flaque dessous']],
        attendu: /fuite|purgeur/ }),
    T('ter-15', 'Automate en STOP après une coupure', 'API en stop led SF rouge après la coupure edf de cette nuit, toute la ligne est à l arrêt',
      { faits: [[/code/, 'non']],
        controles: [[/voyants de l.automate|diagnostic/, 'SF rouge, STOP, le tampon dit programme perdu'], [/pile|carte memoire/, 'pile à plat, 1,2 V']],
        attendu: /automate en stop/ }),
    T('ter-16', 'Groupe hydraulique qui chauffe', 'groupe hydraulique chauffe à 80° et les mouvements ralentissent en fin de poste',
      { controles: [[/indicateur/, 'indicateur de colmatage dans le rouge à chaud'], [/niveau|aspect/, 'niveau ok', 'c']],
        attendu: /filtre hydraulique/ }),
    T('ter-17', 'Disjoncteur moteur de la CTA qui saute', 'disjoncteur moteur du ventilateur de soufflage de la CTA saute au bout de 5 min, réarmé 3 fois',
      { faits: [[/code/, 'non'], [/differentiel/, 'non'], [/plaque/, '4 kW 8 A, réglé 8 A']],
        controles: [[/intensite/, 'L1 : 9,8 A · L2 : 9,9 A · L3 : 9,7 A, au-dessus des 8 A de la plaque'], [/a la main|courroie/, 'la turbine est dure à tourner à la main, palier du ventilateur grippé']],
        attendu: /surcharge mecanique|roulement|palier|moto-ventilateur/ }),
    T('ter-18', 'Éclairage du parking qui saute quand il pleut', 'l éclairage extérieur du parking fait sauter le différentiel quand il pleut',
      { faits: [[/combien de temps/, 'aléatoire quand il pleut']],
        controles: [[/un par un/, 'c est le départ candélabres qui fait sauter'], [/isolement/, '0,02 MΩ sur le départ candélabres'], [/inspecter/, 'pied du candélabre 3 plein d eau, boîte de raccordement noyée']],
        attendu: /defaut d.isolement/ }),
    T('ter-19', 'Contacteur qui grille ses bobines', 'Contacteur KM2 du coffret de la station claque et grille ses bobines, 3e en 2 mois',
      { controles: [[/a1-a2|bornes de la bobine/, '19 V mesurés pour une bobine 24 V, trop faible'], [/secondaire|transformateur/, '24 V stable au transfo même en charge, ok', 'c'], [/resistance de la bobine/, 'bobine neuve, bonne', 'c'], [/faces polaires/, 'propre', 'c']],
        attendu: /tension de commande trop faible/ }),
    T('ter-20', 'Mesure de niveau incohérente', 'capteur de niveau de la cuve affiche n importe quoi sur l automate, ça saute de 10 à 90 %',
      { faits: [[/code/, 'non']],
        controles: [[/transmetteur/, 'de l eau dans la tête du capteur, bornes oxydées'], [/courant de la boucle/, 'ça varie entre 3 et 22 mA sans raison, pas normal']],
        attendu: /signal analogique/ }),
    T('ter-21', 'Sirène du 2e étage muette à l’essai', 'la sirène incendie du 2e étage ne sonne pas à l essai, les autres étages oui',
      { faits: [[/code/, 'non']],
        controles: [[/fin de ligne/, 'ligne ouverte, résistance infinie'], [/diffuseurs un par un/, 'fil débranché dans le 3e diffuseur']],
        attendu: /diffuseurs/ }),
    T('ter-22', 'Issue de secours qui reste verrouillée à l’alarme', 'ventouse de l issue de secours du hall ne lache pas quand l alarme incendie se déclenche, vu à l essai mensuel',
      { faits: [[/code/, 'non']],
        controles: [[/bornes du verrouillage|tension aux bornes de la ventouse/, '24 V toujours présent même en alarme, pas normal'], [/asservissement|relais|cmsi/, 'le relais d asservissement du SSI n a jamais été raccordé sur l alimentation de la ventouse']],
        attendu: /asservissement|non raccorde|relais/ }),
    T('ter-23', 'Moteur qui grogne et sent le chaud', 'Le moteur du compacteur grogne et sent le chaud, le thermique saute au bout de 5 min',
      { faits: [[/plaque/, '11 kW 21 A direct, thermique réglé 21 A'], [/differentiel/, 'non']],
        controles: [[/intensite sur chaque phase/, 'L1 : 14 A · L2 : 22 A · L3 : 15 A'], [/thermograph/, 'rien de spécial dans l armoire', 'c'], [/chute de tension/, 'pareil sur les 3 pôles, ok', 'c'],
          [/resistance de chaque enroulement/, 'U : 1,2 Ω · V : 0,6 Ω · W : 1,2 Ω'], [/tensions entre phases/, '400 V sur les 3, ok', 'c']],
        attendu: /enroulement/ }),
    T('ter-24', 'Plus de pression au dernier étage', 'surpresseur : plus de pression au 4e étage aux heures de pointe, la pompe tourne tout le temps',
      { controles: [[/courbe/, '2,1 bar vanne fermée pour 4,5 bar sur la courbe, pas bon'], [/roue/, 'roue érodée, bagues usées'], [/gonflage/, 'ok', 'c'], [/enclenchement/, 'réglages ok', 'c']],
        attendu: /roue usee/ }),
    T('ter-25', 'VMC qui n’aspire plus au rez-de-chaussée', 'VMC : les bouches n aspirent plus au RDC, le caisson tourne, moisissures dans la salle de bain',
      { faits: [[/code/, 'non']],
        controles: [[/bouches/, 'gaine déboîtée du caisson dans les combles']],
        attendu: /reseau de ventilation/ }),
    T('ter-26', 'Arrêt d’urgence impossible à réarmer', 'machine à l arrêt, impossible de réarmer après un arrêt d urgence, voyant défaut sécurité',
      { controles: [[/module de securite/, 'canal 1 ouvert, pas normal'], [/continuite de chaque canal|protecteur/, 'contact de l arrêt d urgence du pupitre cassé, il reste ouvert']],
        attendu: /securite/ }),
    T('ter-27', 'Four qui ne chauffe plus qu’à moitié', 'four industriel électrique : il chauffe plus qu à moitié, il met 2 fois plus de temps à monter',
      { controles: [[/intensite/, 'L1 : 32 A · L2 : 0 A · L3 : 32 A'], [/tension/, '400 V entre les 3 phases en amont, ok', 'c'], [/resistance|fusible|continuite/, 'fusible de la phase 2 fondu, une résistance coupée']],
        attendu: /phase|resistance|fusible/ }),
    T('ter-28', 'Lecteur de badge qui lit une fois sur trois', 'lecteur badge entrée parking lit 1 fois sur 3, faut repasser le badge plusieurs fois',
      { faits: [[/code/, 'non']],
        controles: [[/badge de reference/, 'lecture aléatoire, un événement une fois sur trois, pas normal'], [/aux bornes du lecteur/, '9,5 V au lecteur pour du 12 V, câble très long : trop faible'], [/sortie de l.alimentation/, '12,3 V en sortie, 9,5 V au lecteur : trop faible']],
        attendu: /lecteur/ })
  ];
};
