/* DIAG-MAINT — base de pannes : contrôle d'accès, interphonie, portails et barrières. */
(function (DM) {
  'use strict';
  const K = DM.kbTools, C = K.C, H = K.H;

  DM.kbRegister('acces', [
    H('Défaut d’alimentation de la centrale ou du lecteur', 'Un lecteur éteint, une centrale muette ou des redémarrages évoquent une alimentation absente, trop faible ou surchargée.',
      ['rien', 'eteint', 'ne fonctionne', 'coupure', 'led', 'hors service', 'plus rien', 'tout est eteint', 'aucun voyant', 'redemarre'],
      [C('sous_tension', 'Mesurer la tension d’alimentation en sortie de l’alimentation puis aux bornes de la centrale ou du lecteur, installation en service.', 'Tension nominale (12 ou 24 V DC, ±10 %) en sortie comme à l’arrivée.',
         'Savoir si l’alimentation est présente et si elle arrive.'),
       C('hors_tension', 'Alimentation consignée : contrôler son fusible, son raccordement secteur et le serrage des bornes de sortie.', 'Fusible passant, secteur présent en amont, bornes serrées.',
         'Trouver pourquoi la tension manque.')],
      'Consigné : remplacer le fusible ou l’alimentation (même tension, courant suffisant pour ventouses et lecteurs), resserrer les bornes, puis contrôler la tension en charge.'),
    H('Batterie de secours hors service', 'Une installation qui redémarre ou déverrouille à chaque microcoupure, ou qui signale un défaut batterie, a une batterie en fin de vie.',
      ['+batterie', 'coupure secteur', 'microcoupure', 'redemarre', 'reboot', 'perd l heure', 'defaut batterie', 'orage', 'coupure de courant'],
      [C('sous_tension', 'Secteur coupé quelques minutes : mesurer la tension de la batterie pendant qu’elle alimente l’installation.', 'Tension supérieure à 12 V (système 12 V) et stable ; batterie de moins de 4 ans.',
         'Une batterie usée s’écroule dès qu’elle doit débiter.')],
      'Remplacer la batterie par un modèle de même tension et de même capacité, noter la date de pose, vérifier la tension de charge et faire un essai secteur coupé.'),
    H('Ventouse électromagnétique qui ne tient plus', 'Une porte qui s’ouvre en tirant alors qu’elle devrait être verrouillée a une ventouse sous-alimentée ou une contre-plaque mal alignée ou sale.',
      ['+ventouse', '+ne tient', 'en tirant', 'ne verrouille', 'ne se verrouille', 'contre plaque', 'porte s ouvre', 'force'],
      [C('sous_tension', 'Porte fermée et verrouillée : mesurer la tension aux bornes de la ventouse.', 'Tension nominale de la ventouse (12 ou 24 V DC, ±10 %).',
         'Une ventouse sous-alimentée perd l’essentiel de sa force.',
         { localize: true, onConform: 'Ventouse correctement alimentée : voir le contact avec la contre-plaque.' }),
       C('visuel', 'Contrôler l’alignement, la propreté et la liberté de la contre-plaque (elle doit pouvoir s’orienter), et l’état de la surface de la ventouse.', 'Contre-plaque plaquée sur toute sa surface, propre, articulée.',
         'Un mauvais contact suffit à faire lâcher la porte.',
         { localize: true, onConform: 'Contre-plaque correcte : c’est l’alimentation de la ventouse qui est en cause.' })],
      'Rétablir la tension à la ventouse (section du câble, alimentation, connexion), nettoyer et réaligner la contre-plaque sans la brider, puis vérifier la tenue de la porte.'),
    H('Bobine de gâche coupée', 'Une porte qui ne se déverrouille pas à l’ordre, sans aucun bruit à la gâche alors qu’elle est bien commandée, a une bobine de gâche coupée.',
      ['+gache', 'ne s ouvre', 'reste verrouille', 'aucun bruit', 'pas de clac', 'porte', 'badge accepte', 'ne se deverrouille'],
      [C('sous_tension', 'À l’ordre d’ouverture (badge accepté ou bouton), mesurer la tension aux bornes de la gâche.', 'Tension de commande présente pendant la temporisation.',
         'Savoir si la gâche est commandée.',
         { localize: true, onConform: 'Commande présente : la gâche elle-même est en cause.' }),
       C('hors_tension', 'Gâche débranchée : mesurer la résistance de sa bobine.', 'Résistance finie conforme (ni 0 Ω, ni circuit ouvert).',
         'Une bobine coupée se mesure directement.')],
      'Remplacer la gâche (même tension, même fonction : à émission ou à rupture), puis vérifier plusieurs ouvertures.'),
    H('Commande de déverrouillage absente (relais de la centrale, câblage)', 'Le badge est accepté mais aucune tension n’arrive à l’organe de verrouillage : relais de sortie de la centrale hors service, fil coupé ou borne desserrée.',
      ['+gache', 'badge accepte', 'led verte', 'fait plus rien', 'ne s ouvre', 'reste verrouille', 'aucun bruit', 'relais', 'porte', 'ne se deverrouille', 'apres travaux'],
      [C('sous_tension', 'À l’ordre d’ouverture (badge accepté ou bouton), mesurer la tension aux bornes de la gâche.', 'Tension de commande présente pendant la temporisation.',
         'Savoir si la gâche est commandée.'),
       C('sous_tension', 'À l’ordre d’ouverture, mesurer la tension en sortie du relais de la centrale, puis contrôler la continuité du câble jusqu’à la porte.', 'Tension présente en sortie de centrale et câble continu.',
         'Savoir si la commande se perd dans la centrale ou dans le câble.')],
      'Remplacer le relais ou la carte de sortie de la centrale, ou refaire le câble jusqu’à la porte, puis vérifier plusieurs ouvertures.'),
    H('Gâche en contrainte mécanique (porte désalignée)', 'Une gâche qui bourdonne ou claque sans libérer la porte est bloquée par le pêne qui force : porte affaissée, joint trop épais, gâche mal positionnée.',
      ['+gache', '+bourdonn', 'clac', 'force', 'il faut pousser', 'il faut tirer', 'frott', 'affaisse', 'hiver', 'ne s ouvre', 'grippe'],
      [C('fonctionnel', 'Commander la gâche porte ouverte, puis porte fermée en soulageant le battant (pousser ou tirer légèrement).', 'La gâche libère le pêne de la même façon dans les deux cas.',
         'Si la gâche fonctionne porte ouverte mais pas porte fermée, c’est la mécanique de la porte.')],
      'Régler la porte (paumelles, ferme-porte) et la position de la gâche pour supprimer la contrainte sur le pêne, lubrifier le pêne, puis vérifier l’ouverture sans effort.'),
    H('Lecteur défectueux ou mal raccordé', 'Si tous les badges sont refusés ou ignorés sur un seul lecteur, sans événement dans le journal, c’est le lecteur ou son câble.',
      ['+lecteur', 'tous les badges', 'ne lit', 'bip', 'aucun evenement', 'ne reagit pas', 'led', 'plus de bip'],
      [C('fonctionnel', 'Présenter un badge de référence valide et consulter le journal d’événements de la centrale.', 'Lecture signalée par le lecteur et événement enregistré.',
         'Savoir si la lecture arrive jusqu’à la centrale.'),
       C('sous_tension', 'Mesurer l’alimentation aux bornes du lecteur et contrôler le raccordement des fils de données (repérage, serrage).', 'Alimentation nominale, fils de données raccordés et serrés.',
         'Départager le lecteur de son câblage.')],
      'Refaire le raccordement ou remplacer le lecteur par un modèle compatible (même technologie de badge, même protocole), puis tester avec plusieurs badges.'),
    H('Droits ou paramétrage incorrects', 'Un refus ciblé — une personne, un horaire, une porte — vient du paramétrage : droits, plage horaire, validité du badge.',
      ['+refuse', 'acces refuse', '+horaire', '+droit', 'certain', 'utilisateur', 'un seul badge', 'nouveau', 'week end', 'le soir', 'une personne'],
      [C('fonctionnel', 'Relever dans le journal le motif du refus, puis vérifier les droits, les plages horaires et la validité du badge dans le logiciel.', 'Droits conformes à la demande, badge valide.',
         'Le journal donne le motif exact du refus.',
         { signe: ['plage', 'horaire', 'droit', 'profil', 'expire', 'invalide', 'inconnu', 'autoris', 'refus', 'groupe', 'validite', 'desactive', 'perime'] })],
      'Corriger les droits, la plage horaire ou la validité du badge, puis faire un essai avec la personne concernée.'),
    H('Perte de communication avec la centrale', 'Un contrôleur de porte hors ligne ne reçoit plus les droits ni ne remonte les événements.',
      ['+hors ligne', '+communication', '+tout le monde', 'tous les badges', 'tous les lecteurs', 'les autres lecteurs', 'reseau', 'bus', 'offline', 'rs485', 'ne remonte', 'deconnecte', 'superviseur'],
      [C('visuel', 'Relever les LED de communication du contrôleur et l’état des équipements dans le logiciel.', 'Équipement en ligne, échanges visibles.',
         'Savoir quel équipement a décroché.',
         { localize: true, onConform: 'Équipement en ligne au moment du relevé : la perte est intermittente, contrôler le bus.' }),
       C('hors_tension', 'Contrôler le bus (RS485 ou Ethernet) : polarité, serrage, continuité, résistance de terminaison, adresse.', 'Bus continu, polarité respectée, terminaison aux deux extrémités, adresse unique.',
         'Trouver la cause physique de la perte de liaison.')],
      'Refaire la connexion du bus (polarité, terminaison aux deux extrémités seulement), corriger l’adressage, puis vérifier le retour en ligne et la remontée des événements.'),
    H('Contact de porte déréglé ou défaillant', 'Des alarmes « porte forcée » ou « porte restée ouverte » sans effraction viennent du contact de position : aimant trop éloigné, porte qui a du jeu.',
      ['+porte forcee', '+porte ouverte', 'alarme', 'fausse alarme', 'contact', 'aimant', 'intempestive', 'vent'],
      [C('fonctionnel', 'Ouvrir et fermer la porte en observant l’état du contact dans le logiciel ; mesurer l’écart entre le contact et son aimant.', 'Changement d’état franc à chaque manœuvre, écart dans la tolérance du contact.',
         'Un contact à la limite déclenche au moindre jeu de la porte.')],
      'Rapprocher et refixer l’aimant et le contact, reprendre le jeu de la porte, remplacer le contact s’il reste instable.'),
    H('Bouton poussoir de sortie bloqué ou en court-circuit', 'Une porte qui reste déverrouillée en permanence a souvent sa demande de sortie maintenue : bouton coincé ou fil en court-circuit.',
      ['+bouton', '+poussoir', '+reste deverrouille', 'reste ouverte', 'ne se verrouille pas', 'ne se reverrouille', 'sortie', 'en permanence'],
      [C('fonctionnel', 'Débrancher le bouton de sortie à la centrale et observer la porte.', 'La porte reste déverrouillée même bouton débranché (sinon : le bouton ou son câble maintient la demande).',
         'Isoler le bouton en une manœuvre.',
         { localize: true, onConform: 'Le bouton n’est pas en cause : voir la temporisation et la sortie de la centrale.' }),
       C('hors_tension', 'Bouton débranché : mesurer son contact à l’ohmmètre, au repos puis appuyé.', 'Contact ouvert au repos, fermé appuyé.',
         'Départager le bouton de son câble.')],
      'Remplacer le bouton poussoir ou le fil en court-circuit, puis vérifier le verrouillage après la temporisation.'),
    H('Photocellules de sécurité désalignées ou encrassées', 'Un portail qui s’ouvre mais refuse de se fermer, ou se rouvre aussitôt, voit un obstacle permanent : cellules désalignées, sales, ou coupées.',
      ['+portail', '+cellule', '+photocellule', '+ne se ferme pas', 'se rouvre', 'barriere', 'clignot', 'reste ouvert', 'soleil'],
      [C('visuel', 'Contrôler l’alignement, la propreté et les voyants des photocellules (émetteur alimenté, récepteur qui voit le faisceau).', 'Faisceau reçu, voyant du récepteur à l’état normal, optiques propres.',
         'Le voyant du récepteur dit si le faisceau passe.')],
      'Nettoyer et réaligner les cellules, refixer les supports, remplacer la cellule ou le câble défectueux, puis vérifier la fermeture et l’arrêt sur obstacle. Ne jamais shunter les cellules.'),
    H('Portail qui force (point dur, détection d’obstacle)', 'Un portail qui s’arrête en cours de course ou repart en arrière détecte un effort anormal : galets, rail ou gonds grippés, vantail qui frotte, surtout par temps froid.',
      ['+portail', 's arrete en cours', '+repart en arriere', 'force', 'obstacle', 'hiver', 'dur', 'frott', 'gel', 'a mi course', 'inverse'],
      [C('visuel', 'Motorisation consignée et débrayée : manœuvrer le vantail à la main sur toute sa course.', 'Vantail libre, sans point dur ni frottement.',
         'Séparer la mécanique du portail de sa motorisation.')],
      'Débrayé et consigné : nettoyer le rail, remplacer ou graisser galets et gonds, supprimer le frottement, puis refaire l’apprentissage de course et vérifier la détection d’obstacle. Ne pas augmenter la force pour passer le point dur.'),

    H('Fin de course ou butée de portail déréglée', 'Un portail qui s’arrête avant la fermeture complète, ou qui force en fin de course, a une butée ou un fin de course déplacé, ou une course apprise qui ne correspond plus.',
      ['+portail', '+pas a fond', '+entrouvert', 's arrete avant', 'butee', 'fin de course', 'course', 'ne ferme pas completement', 'reste un jour', 'vantail'],
      [C('visuel', 'Contrôler la position des butées mécaniques et des fins de course, et comparer la course réelle du vantail à la course apprise par la motorisation.', 'Le vantail arrive en butée, fins de course à leur place, course apprise complète.',
         'Voir si la motorisation s’arrête là où elle le doit.')],
      'Motorisation consignée : repositionner et bloquer la butée ou le fin de course, puis refaire l’apprentissage de course et vérifier la fermeture complète et la détection d’obstacle.'),
    DM.kbTools.emergencyExitLock(),

    H('Ordre d’ouverture intempestif (contacteur à clé, bouton, récepteur radio)', 'Un portail ou une porte qui s’ouvre sans que personne ne le commande reçoit un ordre parasite : contacteur à clé ou bouton plein d’eau, fil de commande en court-circuit, récepteur radio qui capte une autre télécommande.',
      ['+s ouvre tout seul', '+s ouvre seul', 'tout seul', 'la nuit', 'sans raison', 'intempesti', 'personne', 'pluie'],
      [C('fonctionnel', 'Débrancher une à une les entrées de commande de l’armoire (contacteur à clé, bouton, interphone, récepteur radio) et surveiller les ouvertures intempestives.', 'Les ouvertures continuent quelle que soit l’entrée débranchée.',
         'L’entrée dont le débranchement supprime les ouvertures porte l’ordre parasite.'),
       C('visuel', 'Inspecter l’organe désigné et son câble : eau, oxydation, contact collé, fil blessé.', 'Organe sec, contact ouvert au repos, câble intact.',
         'Constater la cause de l’ordre parasite.')],
      'Remplacer l’organe de commande ou le câble en cause (matériel étanche adapté à l’extérieur), ou effacer et reprogrammer les télécommandes du récepteur radio, puis surveiller quelques jours.'),
    H('Télécommande ou récepteur radio (pile, mémorisation, antenne)', 'Des télécommandes qui ne commandent plus, ou seulement de très près, viennent de leur pile, d’une mémoire de récepteur effacée ou d’une antenne débranchée.',
      ['+telecommande', '+bip', 'emetteur', 'recepteur radio', 'portee', 'de pres', 'plus aucune telecommande', 'antenne'],
      [C('fonctionnel', 'Essayer plusieurs télécommandes à courte distance et observer le voyant du récepteur radio.', 'Le récepteur réagit à chaque télécommande, à distance normale.',
         'Départager une télécommande isolée d’un problème de récepteur.')],
      'Remplacer la pile de la télécommande, la reprogrammer dans le récepteur, rebrancher ou remplacer l’antenne ; remplacer le récepteur s’il ne réagit à aucune télécommande.'),
    H('Poste intérieur ou platine d’interphonie défaillant', 'Un défaut d’interphonie limité à un logement désigne le poste intérieur ou son raccordement ; un défaut commun à tous désigne la platine de rue ou son alimentation.',
      ['+interphone', '+visiophone', 'platine', 'combine', 'n entend', 'ne sonne pas', 'un seul appartement', 'tous les appartements', 'pas d image', 'appel'],
      [C('fonctionnel', 'Appeler plusieurs logements depuis la platine pour savoir si le défaut touche un seul poste ou tous, puis essayer un poste de remplacement sur le logement en défaut.', 'Appel, phonie et ouverture corrects sur tous les postes.',
         'Savoir si le défaut est au poste, sur sa ligne ou à la platine.'),
       C('sous_tension', 'Mesurer la tension du bus ou de la ligne aux bornes du poste en défaut et en sortie d’alimentation.', 'Tension conforme à la notice aux deux endroits.',
         'Départager le poste de son câblage.',
         { localize: true, onConform: 'Ligne correcte : le poste intérieur lui-même est en cause.' })],
      'Remplacer le poste intérieur ou refaire son raccordement ; si tous les logements sont touchés, contrôler l’alimentation et remplacer la platine ou son module audio.'),

    H('Boucle magnétique de détection de véhicule en défaut', 'Une barrière qui reste levée, ne se referme pas après le passage ou ne s’ouvre pas à l’approche d’un véhicule a sa boucle au sol en défaut : câble de boucle coupé ou abîmé, détecteur de boucle déréglé.',
      ['+barriere', '+boucle', 'reste levee', 'reste ouverte', 'vehicule', 'voiture', 'ne se referme pas', 'ne redescend pas', 'voirie', 'enrobe'],
      [C('visuel', 'Relever l’état du détecteur de boucle (voyant de présence, voyant de défaut) sans véhicule sur la boucle.', 'Aucune présence détectée, aucun défaut signalé.',
         'Le détecteur dit s’il voit un véhicule en permanence ou si la boucle est coupée.'),
       C('hors_tension', 'Boucle débranchée du détecteur : mesurer sa résistance et son isolement par rapport à la terre.', 'Résistance de quelques ohms, isolement > 1 MΩ.',
         'Confirmer que le câble de boucle est coupé ou blessé.',
         { localize: true, onConform: 'Boucle saine : régler ou remplacer le détecteur de boucle.' })],
      'Refaire la boucle (saignée, câble adapté, torsadage des queues de boucle) ou régler la sensibilité et la fréquence du détecteur, puis vérifier ouverture et refermeture au passage d’un véhicule.',
      { requis: ['barriere', 'portail', 'boucle'] }),
    H('Serrure ou béquille électronique autonome : piles ou mécanisme', 'Une serrure électronique à piles qui ne réagit plus au badge, clignote rouge ou bipe a ses piles faibles ; plus rarement son embrayage est bloqué.',
      ['+serrure', '+bequille', '+cylindre', 'piles', 'bip', 'clignot', 'autonome', 'chambre', 'hotel'],
      [C('fonctionnel', 'Présenter un badge valide et observer la signalisation de la serrure ; mesurer ou remplacer les piles.', 'Signalisation normale, piles à leur tension nominale.',
         'La plupart des pannes de serrures autonomes sont des piles.')],
      'Remplacer toutes les piles par des piles neuves du type prescrit, remettre la serrure à l’heure si nécessaire, puis tester plusieurs badges ; remplacer la serrure si elle reste inerte avec des piles neuves.'),

    H('Motorisation de portail débrayée ou transmission rompue', 'Si le moteur tourne sans entraîner le portail, la motorisation est restée débrayée après une manœuvre manuelle, ou la transmission est rompue : pignon, crémaillère, clavette, bras.',
      ['+portail', '+moteur tourne', 'ne bouge pas', 'dans le vide', 'debray', 'cremaillere', 'pignon', 'on entend le moteur'],
      [C('visuel', 'Contrôler le dispositif de débrayage (levier, clé de déverrouillage) puis l’engrènement pignon / crémaillère ou l’accouplement du bras.', 'Motorisation embrayée, pignon engrené sur la crémaillère, transmission intacte.',
         'Voir pourquoi le moteur n’entraîne plus le portail.')],
      'Réembrayer la motorisation, régler le jeu pignon / crémaillère ou remplacer la pièce de transmission rompue, puis refaire l’apprentissage de course.',
      { requis: ['portail', 'barriere'] }),
    H('Porte automatique : détecteur d’ouverture ou de sécurité activé en permanence', 'Une porte automatique qui reste ouverte voit en permanence une présence : radar d’ouverture trop sensible ou perturbé (affiche, reflet, plante), ou cellule de sécurité occultée ou encrassée.',
      ['+porte automatique', '+reste ouverte', 'coulissante', 'radar', 'magasin', 'ne se referme pas', 's ouvre toute seule'],
      [C('fonctionnel', 'Observer les voyants des détecteurs (radar d’ouverture, cellules de sécurité) sans personne dans le passage, et dégager la zone de détection.', 'Aucun détecteur activé quand le passage est libre.',
         'Le détecteur qui reste activé maintient la porte ouverte.')],
      'Dégager ce qui perturbe le détecteur, régler son champ et sa sensibilité, nettoyer ou remplacer la cellule de sécurité ; ne jamais neutraliser une sécurité de porte automatique.',
      { requis: ['porte automatique', 'coulissante', 'radar'] })
  ]);
})(window.DM);
