/* DIAG-MAINT — base de pannes : automatisme, automates programmables, capteurs et actionneurs. */
(function (DM) {
  'use strict';
  const K = DM.kbTools, C = K.C, H = K.H, CYCLE_STEP = K.CYCLE_STEP;

  DM.kbRegister('automatisme', [
    H('Capteur déréglé, encrassé ou défectueux', 'Un capteur mal positionné, sale ou en fin de vie donne une détection absente ou instable : le cycle attend une information qui n’arrive pas.',
      ['+capteur', '+detecteur', 'intermitten', 'parfois', '+cellule', 'rate', 'comptage', 'compteur faux', 'fin de course', 'aleatoire', 'cycle bloque', 'attente', 'ne detecte', 'inductif', 'photoelectrique', 'bloqu', 'vibr'],
      [CYCLE_STEP,
       C('fonctionnel', 'Présenter la pièce ou la cible devant le capteur désigné et observer sa LED et la LED d’entrée de l’automate ; contrôler distance, alignement et propreté.', 'Détection franche et répétable à la distance nominale, LED du capteur et LED d’entrée allumées ensemble.',
         'Vérifier le capteur là où il travaille.')],
      'Nettoyer, repositionner et bloquer le capteur à sa distance nominale (ou le remplacer par un modèle identique), puis valider plusieurs cycles.'),
    H('Liaison capteur – automate coupée (câble, connecteur, bornier)', 'Le capteur détecte (sa LED s’allume) mais l’automate ne voit rien : fil coupé dans une chaîne porte-câbles, connecteur desserré, borne.',
      ['+chaine porte cable', '+cable', '+connecteur', 'm12', 'intermitten', 'en mouvement', 'led du capteur allumee', 'entree', 'ne voit pas', 'led d entree eteinte', 'fil'],
      [CYCLE_STEP,
       C('sous_tension', 'Capteur actionné (sa LED allumée) : mesurer la tension à la borne d’entrée de l’automate.', '24 V DC à la borne et LED d’entrée allumée.',
         'Voir si le signal du capteur arrive jusqu’à l’automate.'),
       C('hors_tension', 'Machine consignée : contrôler la continuité de chaque fil du câble du capteur en le manipulant sur tout son parcours (chaîne porte-câbles, connecteurs).', 'Continuité stable pendant la manipulation.',
         'Trouver la coupure, souvent intermittente.')],
      'Machine consignée : remplacer le câble ou le connecteur (câble souple adapté aux chaînes porte-câbles, rayon de courbure respecté), puis valider plusieurs cycles.'),
    H('Défaut d’alimentation 24 V', 'Une alimentation faible ou surchargée provoque des redémarrages de l’automate, des capteurs qui décrochent et des défauts aléatoires.',
      ['+24', '+alimentation', 'api', 'automate', 'eteint', '+reset', '+redemarre', 'stop', 'aleatoire', 'plusieurs defauts', 'ecran clignote'],
      [C('sous_tension', 'Mesurer la tension 24 V DC en sortie d’alimentation, à vide puis en charge (machine en cycle).', '24 V DC ±5 %, stable en charge.',
         'Une alimentation qui s’écroule en charge se voit au voltmètre.'),
       C('sous_tension', 'Mesurer le courant débité par l’alimentation et le comparer à son courant nominal ; isoler les départs un par un si elle est surchargée.', 'Courant débité inférieur au nominal de l’alimentation.',
         'Savoir si l’alimentation est fatiguée ou si un départ la surcharge.',
         { localize: true, onConform: 'Courant débité normal : l’alimentation elle-même est fatiguée.' })],
      'Remplacer l’alimentation par un modèle de puissance suffisante, ou supprimer la surcharge (départ en court-circuit, ajout de consommateurs) ; contrôler ensuite la tension en charge.'),
    H('Sortie automate défaillante ou non transmise', 'La sortie est commandée (LED allumée) mais la tension n’arrive pas à l’actionneur : sortie à relais ou à transistor détruite, fusible de carte, commun non alimenté, fil coupé.',
      ['+sortie', 'led allumee', 'led de sortie', 'ne bouge', 'carte', 'relais', 'pas de tension', 'actionneur'],
      [C('sous_tension', 'Sortie commandée (LED allumée) : mesurer la tension à la borne de sortie de l’automate, puis aux bornes de l’actionneur.', '24 V présents à la borne de sortie et aux bornes de l’actionneur.',
         'Savoir où la tension se perd.'),
       C('hors_tension', 'Armoire consignée : contrôler le fusible de la carte de sorties, l’alimentation de son commun et la continuité du fil jusqu’à l’actionneur.', 'Fusible passant, commun alimenté, fil continu.',
         'Trouver l’élément en cause avant de toucher au programme.',
         { localize: true, onConform: 'Fusible, commun et fil corrects : la sortie elle-même ne commute plus.' })],
      'Consigné : remplacer le fusible, le fil ou la carte de sorties ; si une sortie de réserve est utilisée, modifier le programme et documenter le changement. Chercher la cause (court-circuit de l’actionneur, absence de diode de roue libre).'),
    H('Actionneur ou bobine défaillant (électrovanne, distributeur, relais)', 'La sortie est active et la tension arrive bien à l’actionneur, mais il ne réagit pas : bobine coupée ou organe bloqué.',
      ['+electrovanne', '+verin', 'actionneur', 'ne bouge', '+distributeur', '+bobine', 'ne sort pas', 'ne rentre pas', 'sortie active'],
      [CYCLE_STEP,
       C('hors_tension', 'Machine consignée, énergie purgée : mesurer la résistance de la bobine de l’actionneur et la comparer à sa plaque.', 'Résistance finie conforme (ni 0 Ω, ni circuit ouvert).',
         'Une bobine coupée se mesure directement.')],
      'Machine consignée et énergies purgées : remplacer la bobine (même tension) ou l’actionneur bloqué, puis valider le mouvement en manuel et en cycle.'),
    H('Défaut de communication réseau', 'Une perte de liaison bloque les échanges entre automate, pupitre, variateurs ou entrées/sorties déportées.',
      ['+communication', 'reseau', 'bus', 'profinet', 'profibus', 'modbus', 'ethernet', 'hmi', 'ihm', 'timeout', 'perte', 'bf', 'station', 'deporte', 'esclave'],
      [C('visuel', 'Relever les LED de diagnostic réseau et le diagnostic de l’automate : quel participant est absent.', 'Tous les participants présents, aucune erreur de bus.',
         'Savoir quel appareil a quitté le réseau.',
         { localize: true, onConform: 'Tous les participants répondent : la perte est fugitive, contrôler câbles et connecteurs.' }),
       C('hors_tension', 'Contrôler le câble et les connecteurs du participant absent (enfichage, blindage, résistance de terminaison), son alimentation et son adresse.', 'Connecteurs enfichés et verrouillés, câble intact, terminaison et adresse correctes, participant alimenté.',
         'Trouver la cause physique de la coupure.')],
      'Remplacer le connecteur ou le câble défectueux (même type de câble, blindage repris), rétablir terminaison et adressage, puis vérifier l’absence d’erreurs dans le diagnostic.'),
    H('Programme ou paramètre modifié', 'Une modification récente (programme, recette, paramètre de variateur ou de temporisation) peut avoir introduit un comportement anormal.',
      ['+depuis la mise a jour', '+modif', 'mise a jour', '+parametre', 'recette', 'apres intervention', 'apres l intervention', 'changement de format', 'depuis le changement'],
      [C('fonctionnel', 'Comparer le programme et les paramètres avec la dernière sauvegarde de référence.', 'Aucune différence non documentée.',
         'Retrouver ce qui a changé.')],
      'Rétablir la valeur ou la version de référence (ou valider la modification avec son auteur), refaire une sauvegarde et documenter le changement.'),
    H('Automate en STOP ou en défaut système', 'Un automate en STOP avec un voyant de défaut ne déroule plus son programme : module défaillant, perte de programme (pile, carte mémoire), erreur de programme.',
      ['+stop', '+sf', 'led rouge', 'defaut cpu', 'api en defaut', '+pile', 'batterie', 'apres coupure', 'perte programme', 'automate', 'plus rien ne marche'],
      [C('visuel', 'Relever l’état des voyants de l’automate et lire son tampon de diagnostic à la console.', 'Automate en RUN, aucun défaut système.',
         'Le tampon de diagnostic donne la cause de l’arrêt.'),
       C('visuel', 'Contrôler la pile ou la carte mémoire de l’automate et l’état de chaque module (voyants de défaut).', 'Pile bonne, carte mémoire en place, aucun module en défaut.',
         'Trouver l’élément matériel en cause.')],
      'Remplacer la pile (automate sous tension pour ne pas perdre le programme) ou le module défaillant, recharger le programme depuis la sauvegarde de référence, puis remettre en RUN.'),
    H('Signal analogique hors plage (capteur 4-20 mA, câblage)', 'Une mesure aberrante, figée ou à zéro vient d’une boucle 4-20 mA interrompue, d’un transmetteur non alimenté ou hors service.',
      ['+4 20', '+analogique', '+n importe quoi', 'capteur de niveau', 'incoherent', 'mesure fausse', 'aberrant', 'rupture de fil', '+transmetteur', 'affiche 0', 'hors plage', 'fige', 'sonde de niveau', 'capteur de pression'],
      [C('sous_tension', 'Mesurer le courant de la boucle (multimètre en série ou pince mA) et le comparer à la grandeur réelle.', 'Courant entre 4 et 20 mA, cohérent avec la grandeur mesurée.',
         'Un courant nul signe une boucle coupée ; un courant figé, un transmetteur en défaut.'),
       C('sous_tension', 'Mesurer la tension d’alimentation aux bornes du transmetteur et contrôler la continuité de la boucle.', 'Tension suffisante aux bornes du transmetteur (selon notice), boucle continue.',
         'Départager le câblage du transmetteur.')],
      'Refaire le câblage de la boucle ou remplacer le transmetteur, puis vérifier la mesure en deux points (bas et haut d’échelle).'),

    H('Pupitre ou écran : alimentation ou connexion défaillante', 'Un écran qui s’éteint, se fige ou redémarre seul alors que l’automate continue de tourner a un problème propre : connecteur d’alimentation desserré, alimentation de l’écran, câble de liaison.',
      ['+ecran', '+pupitre', 'ihm', 'noir', 'fige', 's eteint', 'redemarre', 'tactile', 'par moments', 'l automate continue'],
      [C('sous_tension', 'Mesurer la tension d’alimentation directement sur le connecteur de l’écran, au moment du défaut si possible.', 'Tension nominale stable sur le connecteur de l’écran.',
         'Savoir si l’écran est correctement alimenté.'),
       C('hors_tension', 'Contrôler le connecteur d’alimentation de l’écran (serrage, verrouillage), son câble et le câble de liaison avec l’automate.', 'Connecteurs verrouillés, câbles intacts.',
         'Trouver la connexion qui lâche.',
         { localize: true, onConform: 'Connexions correctes et alimentation stable : l’écran lui-même est à remplacer.' })],
      'Refaire la connexion ou remplacer le câble ; si l’alimentation et les connexions sont bonnes, remplacer l’écran et recharger son application depuis la sauvegarde.'),

    H('Sonde de température coupée ou hors service (thermocouple, sonde Pt100)', 'Une température affichée fixe, au maximum ou incohérente, alors que le procédé est froid, vient de la sonde ou de son câble : thermocouple coupé, sonde Pt100 en circuit ouvert, câble de compensation abîmé.',
      ['+thermocouple', '+pt100', '+temperature', 'affiche', 'fixe', 'fige', 'four', 'regulateur', 'regulation', 'degres', 'sonde'],
      [C('hors_tension', 'Sonde débranchée du régulateur ou de la carte : mesurer la sonde (continuité d’un thermocouple, résistance d’une Pt100 : environ 110 Ω à 25 °C).', 'Thermocouple continu, ou Pt100 de résistance conforme à la température.',
         'Une sonde coupée se mesure directement.'),
       C('hors_tension', 'Contrôler le câble de la sonde jusqu’au régulateur (continuité, polarité du câble de compensation, bornes).', 'Câble continu, polarité respectée, bornes serrées.',
         'Départager la sonde de son câble.',
         { localize: true, onConform: 'Câble correct : la sonde elle-même est à remplacer.' })],
      'Remplacer la sonde par un modèle de même type (thermocouple K, J… ou Pt100) et de même longueur, respecter la polarité du câble de compensation, puis vérifier l’affichage à température connue.'),

    H('Bouton ou organe de commande du pupitre défaillant', 'Un bouton qui ne produit plus aucun effet alors que l’automate tourne et n’affiche aucun défaut a son contact hors service, ou son fil coupé — souvent au passage de la porte du pupitre.',
      ['+bouton', 'depart cycle', 'ne fait plus rien', 'sans effet', 'pupitre', 'selecteur', 'commutateur', 'poussoir', 'pas de defaut'],
      [CYCLE_STEP,
       C('sous_tension', 'Bouton actionné : mesurer la tension à la borne d’entrée correspondante de l’automate et observer la LED d’entrée.', '24 V DC à la borne et LED d’entrée allumée pendant l’appui.',
         'Savoir si l’ordre du bouton arrive à l’automate.'),
       C('hors_tension', 'Pupitre consigné : mesurer le contact du bouton à l’ohmmètre et la continuité de son fil jusqu’au bornier.', 'Contact qui se ferme à l’appui, fil continu.',
         'Départager le bouton de son câblage.')],
      'Consigné : remplacer le bloc de contact du bouton ou refaire le fil coupé (gaine de protection au passage de la porte), puis valider la commande.')
  ]);
})(window.DM);
