/* DIAG-MAINT — base de pannes : électricité / distribution. */
(function (DM) {
  'use strict';
  const K = DM.kbTools, C = K.C, H = K.H, FEEDER_TEST = K.FEEDER_TEST;

  DM.kbRegister('electricite', [
    /* ----- régime IT : alarme du contrôleur permanent d'isolement ----- */
    K.isolationFault(),
    H('Courants de fuite capacitifs d’un variateur (filtre CEM)', 'Le filtre CEM d’un variateur (condensateurs vers la terre) crée des fuites capacitives qui abaissent la valeur lue par le CPI ; un variateur récent est souvent soupçonné.',
      ['+variateur', 'cem', 'filtre', 'recent', 'installe', '+cpi', 'isolement'],
      [FEEDER_TEST,
       C('visuel', 'Vérifier dans la notice du variateur si le filtre CEM doit être déconnecté en régime IT (cavalier / vis de mise à la terre du filtre).', 'Filtre CEM configuré pour un réseau IT.',
         'En IT, un filtre CEM raccordé à la terre fausse la surveillance d’isolement.')],
      'Variateur consigné (bus continu déchargé) : configurer le filtre CEM pour un réseau IT selon la notice (retrait du cavalier ou de la vis de mise à la terre), puis relever la valeur du CPI variateur en service.'),
    H('Défaut d’isolement de résistances chauffantes', 'Les résistances chauffantes (chauffage, antigel) sont une cause classique de défaut d’isolement, surtout après une période d’arrêt humide.',
      ['+chauffage', 'resistance', 'radiateur', 'antigel', 'isolement', '+cpi'],
      [FEEDER_TEST,
       C('hors_tension', 'Départ du chauffage consigné : mesurer l’isolement des résistances au mégohmmètre.', 'Isolement > 1 MΩ.',
         'Écarter ou confirmer les résistances chauffantes.')],
      'Départ consigné : remplacer la résistance dont l’isolement est insuffisant (le séchage ne tient que provisoirement), puis refaire la mesure d’isolement du départ.'),

    /* ----- déclenchements ----- */
    H('Surcharge du circuit', 'Un courant absorbé supérieur au calibre provoque le déclenchement thermique de la protection : le disjoncteur tient un moment puis coupe, sans que le différentiel ne bouge.',
      ['disjonct', 'saute', 'declench', '+surcharge', 'chauffe', 'apres un moment', 'quelques minutes', 'radiateur', 'appoint', 'multiprise', 'rallonge', 'plusieurs appareils', 'hiver', 'chaud'],
      [C('sous_tension', 'Mesurer le courant absorbé sur le circuit à la pince ampèremétrique, en charge, tous les récepteurs habituels en service.', 'Courant inférieur au calibre du disjoncteur (In).',
         'Savoir si le circuit consomme réellement plus que ce que sa protection autorise.'),
       C('visuel', 'Recenser les récepteurs raccordés sur ce circuit et additionner leurs puissances (plaques signalétiques).', 'Puissance totale compatible avec le calibre de la protection et la section du câble.',
         'Identifier ce qui a été ajouté sur le circuit.',
         { localize: true, onConform: 'Récepteurs prévus pour ce circuit : chercher un récepteur qui consomme anormalement.' })],
      'Répartir les récepteurs sur plusieurs circuits ou créer un circuit dédié (protection et section adaptées). Ne jamais remplacer le disjoncteur par un calibre supérieur sans vérifier la section du câble.',
      { diff: false }),
    H('Défaut d’isolement', 'Un courant de fuite vers la terre (humidité, câble ou récepteur endommagé) fait déclencher le différentiel.',
      ['+differentiel', 'disjonct', 'humid', 'eau', 'pluie', 'fuit', 'declench', 'terre', 'exterieur', 'lavage', 'orage', 'interrupteur differentiel', '30 ma'],
      [C('fonctionnel', 'Ouvrir tous les disjoncteurs divisionnaires placés sous le différentiel, réarmer le différentiel, puis refermer les circuits un par un.', 'Le différentiel tient quel que soit le circuit refermé (sinon : le circuit qui le fait déclencher porte le défaut).',
         'Trouver le circuit en défaut sans rien démonter.',
         { signe: ['circuit', 'depart', 'c est', 'celui', 'ligne', 'quand je', 'des que', 'prise', 'eclairage', 'retombe'], localize: true, onConform: 'Aucun circuit ne fait déclencher seul : défaut intermittent ou cumul de petites fuites.' }),
       C('hors_tension', 'Circuit en défaut consigné, récepteurs débranchés : mesurer la résistance d’isolement entre conducteurs actifs et terre (mégohmmètre 500 V DC).', '≥ 0,5 MΩ (NF C 15-100), idéalement > 1 MΩ.',
         'Savoir si le défaut est dans le câblage fixe ou dans un récepteur.',
         { localize: true, onConform: 'Câblage fixe sain : le défaut est dans un récepteur, à rebrancher un par un.' }),
       C('visuel', 'Circuit consigné : inspecter les points exposés du circuit en défaut (prises et luminaires extérieurs, boîtes de dérivation, traversées de mur, appareil raccordé).', 'Appareillage sec, étanche, sans trace d’humidité ni d’échauffement.',
         'Constater la cause physique avant de réparer.',
         { localize: true, onConform: 'Rien de visible : le défaut est dans une partie cachée du circuit, à isoler tronçon par tronçon.' })],
      'Circuit consigné : remplacer ou remettre en état l’élément atteint (appareillage étanche adapté à l’extérieur, boîte, câble, récepteur), sécher, puis refaire la mesure d’isolement du circuit avant de réalimenter. Ne jamais ponter ni supprimer le différentiel.',
      { diff: true }),
    H('Récepteur défectueux sur le circuit', 'Quand la protection ne déclenche que si un appareil précis fonctionne, c’est l’appareil qui est en cause, pas l’installation.',
      ['+quand', '+des que', 'lave', 'four', 'chauffe eau', 'ballon', 'machine', 'appareil', 'branche', 'allume', 'se met en route', 'differentiel', 'disjonct'],
      [C('fonctionnel', 'Débrancher tous les récepteurs du circuit, réarmer, puis les rebrancher et les mettre en marche un par un.', 'La protection tient avec chacun des récepteurs (sinon : celui qui la fait déclencher est en défaut).',
         'Identifier l’appareil en cause.'),
       C('hors_tension', 'Appareil identifié débranché : mesurer son isolement entre conducteurs actifs reliés et la masse (mégohmmètre).', 'Isolement > 1 MΩ.',
         'Confirmer le défaut de l’appareil avant de le réparer ou de le remplacer.')],
      'Réparer ou remplacer l’appareil en défaut (résistance percée, moteur humide, cordon abîmé) ; ne le rebrancher qu’après une mesure d’isolement correcte.'),
    H('Cumul de courants de fuite (déclenchements intempestifs du différentiel)', 'De nombreux appareils électroniques (informatique, éclairage LED, variateurs) créent chacun une petite fuite permanente : leur somme approche le seuil du différentiel, qui déclenche sans défaut franc, souvent à la mise sous tension.',
      ['+intempestif', '+aleatoire', '+sans raison', 'informatique', 'ordinateur', 'pc', 'led', 'onduleur', 'bureau', 'serveur', '+differentiel', 'le matin', 'allumage'],
      [C('sous_tension', 'Mesurer le courant de fuite permanent à la pince de fuite (mA), en enserrant ensemble tous les conducteurs actifs du départ, installation en service.', 'Inférieur à 30 % du seuil du différentiel (environ 10 mA pour un 30 mA).',
         'Savoir si les fuites normales des appareils suffisent à approcher le seuil.'),
       C('fonctionnel', 'Tester le différentiel à l’appareil de contrôle : courant et temps de déclenchement.', 'Déclenchement entre 0,5 et 1 × IΔn, dans le temps normalisé.',
         'Écarter un différentiel devenu trop sensible.',
         { localize: true, onConform: 'Différentiel dans ses tolérances : c’est bien le cumul des fuites qui est en cause.' })],
      'Répartir les circuits sur plusieurs différentiels et utiliser des différentiels à immunité renforcée (type A-SI / HPI) pour l’informatique. Ne jamais remplacer un 30 mA par une sensibilité plus faible sur des circuits de prises.',
      { diff: true }),
    H('Court-circuit', 'Un déclenchement immédiat à la mise sous tension oriente vers un court-circuit franc (câble percé, appareillage détruit, récepteur en court-circuit).',
      ['+court circuit', '+immediat', 'instantane', 'flash', 'etincel', 'arc', 'brul', 'des qu on rearme', 'rearme', 'ne tient pas', 'perce', 'vis', 'clou', 'travaux'],
      [C('hors_tension', 'Circuit consigné, récepteurs débranchés : mesurer la résistance entre phase et neutre et entre phases (ohmmètre).', 'Résistance élevée (circuit ouvert), aucune valeur proche de 0 Ω.',
         'Savoir si le court-circuit est dans le câblage fixe ou dans un récepteur.',
         { localize: true, onConform: 'Câblage fixe sain : le court-circuit est dans un récepteur.' }),
       C('visuel', 'Circuit consigné : inspecter le parcours du câble et l’appareillage (travaux récents, percement, boîte de dérivation, prise ou douille noircie).', 'Câble et appareillage intacts.',
         'Trouver le point de court-circuit.')],
      'Circuit consigné : remplacer le tronçon de câble ou l’appareillage détruit, contrôler l’isolement et la continuité du circuit, vérifier que la protection n’a pas souffert (un disjoncteur ayant coupé plusieurs courts-circuits se remplace).',
      { diff: false }),
    H('Connexion desserrée / échauffement', 'Un mauvais serrage crée une résistance de contact, un échauffement et des coupures aléatoires.',
      ['chauffe', '+odeur', 'brul', '+noirci', 'intermitten', '+gresill', 'clignot', 'vacill', 'scintill', 'aleatoire', 'baisse', 'chaud', 'fondu'],
      [C('sous_tension', 'Réaliser une thermographie infrarouge des connexions en charge (tableau, borniers, appareillage).', 'Écart < 10 °C entre connexions comparables.',
         'Repérer la connexion qui chauffe sans rien démonter.'),
       C('visuel', 'Consigner puis inspecter bornes et connexions (traces d’échauffement, isolant fondu) et contrôler le serrage au couple.', 'Aucune trace d’échauffement, serrage conforme au couple constructeur.',
         'Constater l’état réel de la connexion.')],
      'Circuit consigné : couper la partie de conducteur chauffée, refaire la connexion (embout si nécessaire), remplacer l’appareil dont la borne est marquée, serrer au couple, puis contrôler par thermographie en charge.',
      { diff: false }),
    H('Rupture ou desserrage du neutre', 'En triphasé, un neutre coupé ou desserré déplace le point neutre : certaines phases montent bien au-dessus de 230 V, d’autres chutent. Les appareils monophasés grillent ou fonctionnent mal selon la charge.',
      ['+neutre', '+surtension', '+grille', 'lampes qui claquent', 'eclairage trop fort', 'eclairage faible', 'baisse', 'varie', 'tension anormale', 'triphase', 'plusieurs appareils', 'ampoules'],
      [C('sous_tension', 'Mesurer les tensions entre chaque phase et le neutre, installation en charge.', 'Trois tensions proches de 230 V (±10 %).',
         'Un neutre interrompu se voit immédiatement : tensions phase-neutre très différentes et qui varient avec la charge.'),
       C('hors_tension', 'Installation consignée : contrôler la continuité et le serrage du neutre, de l’arrivée jusqu’au répartiteur (bornes, barrette de neutre, pôle de neutre des appareils).', 'Neutre continu, connexions serrées, sans trace d’échauffement.',
         'Trouver l’endroit de la coupure.')],
      'Couper l’installation tant que le neutre n’est pas rétabli. Consignée : refaire la connexion du neutre (borne ou appareil à remplacer si marqué), serrer au couple, puis contrôler les trois tensions phase-neutre en charge et vérifier les appareils qui ont subi la surtension. Si la coupure est en amont du point de livraison, appeler le gestionnaire du réseau.',
      { diff: false }),
    H('Chute de tension en ligne (câble trop long ou de section insuffisante)', 'Une tension correcte au tableau mais trop basse au récepteur en charge signe une chute de tension dans la ligne : démarrages difficiles, éclairage qui baisse, échauffement du câble.',
      ['+chute de tension', '+bout de ligne', 'longueur', 'loin', 'demarre mal', 'peine', 'tension faible', 'baisse de tension', 'au demarrage', 'rallonge', 'section'],
      [C('sous_tension', 'Mesurer la tension au départ (tableau) puis aux bornes du récepteur, récepteur en fonctionnement.', 'Chute inférieure à 5 % de la tension nominale (3 % pour l’éclairage).',
         'Mesurer la chute de tension réelle de la ligne.'),
       C('visuel', 'Relever la section du câble, sa longueur et le courant absorbé ; comparer à la chute de tension admissible.', 'Section cohérente avec la longueur et le courant.',
         'Vérifier que la ligne est correctement dimensionnée.',
         { localize: true, onConform: 'Ligne correctement dimensionnée : chercher une connexion résistante sur le parcours.' })],
      'Remplacer la ligne par une section adaptée à la longueur et au courant (ou rapprocher le point d’alimentation), puis remesurer la tension au récepteur en charge.',
      { diff: false }),
    H('Absence de tension en amont', 'L’équipement n’est peut-être simplement pas alimenté (protection amont ouverte, fusible fondu, coupure réseau).',
      ['plus de courant', 'pas de courant', '+pas de tension', 'aucun', 'eteint', 'coupure', 'ne fonctionne', 'hors service', 'fusible', 'plus rien'],
      [C('sous_tension', 'Mesurer la tension en amont et en aval de la protection (multimètre CAT III), sur chaque phase.', '230 V ph-N / 400 V ph-ph ±10 % en amont comme en aval.',
         'Situer le point où la tension disparaît.')],
      'Remonter vers l’amont jusqu’au point où la tension est présente ; traiter la cause de l’ouverture (fusible fondu, protection ouverte) avant de réalimenter, et remplacer un fusible par un fusible de même calibre et de même type.'),
    H('Appareil de protection défectueux', 'Une protection vieillissante peut déclencher sans défaut réel ou refuser de se réarmer.',
      ['disjonct', 'rearm', 'bloqu', 'differentiel', 'ne tient pas', 'ancien', 'vieux', 'manette'],
      [C('fonctionnel', 'Réarmer hors charge (aval déconnecté) puis tester le bouton test du différentiel ; si possible, mesurer le seuil et le temps de déclenchement.', 'Réarmement possible ; déclenchement au bouton test ; seuil entre 0,5 et 1 × IΔn.',
         'Vérifier l’appareil lui-même, circuit aval hors de cause.')],
      'Remplacer l’appareil par un modèle de mêmes caractéristiques (calibre, courbe, pouvoir de coupure, sensibilité et type de différentiel), puis vérifier le serrage et faire un essai.'),

    /* ----- éclairage ----- */
    H('Minuterie ou télérupteur défaillant', 'Un éclairage commandé par boutons poussoirs qui ne s’allume plus du tout (ou ne s’éteint plus), disjoncteur enclenché, désigne l’appareil de commande : minuterie ou télérupteur.',
      ['+minuterie', '+telerupteur', '+bouton', 'poussoir', 'communs', 'cage d escalier', 'escalier', 'couloir', 'lumiere', 'eclairage', 'ne s allume', 'reste allume', 'font rien'],
      [C('sous_tension', 'À l’appui sur un bouton poussoir, mesurer la tension de commande aux bornes de la minuterie ou du télérupteur, puis la tension en sortie vers les lampes.', 'Commande présente à l’appui, l’appareil colle et la tension apparaît en sortie.',
         'Savoir si l’ordre arrive et si l’appareil y répond.')],
      'Circuit consigné : remplacer la minuterie ou le télérupteur par un modèle de mêmes caractéristiques (tension de commande, calibre, compatibilité avec les lampes LED et les boutons lumineux), puis faire un essai depuis chaque bouton.',
      { diff: false }),
    H('Bouton poussoir ou interrupteur de commande défaillant', 'Si l’éclairage s’allume depuis certains points de commande et pas depuis d’autres, ou reste allumé en permanence, un bouton poussoir est hors service ou resté collé.',
      ['+bouton', 'poussoir', 'interrupteur', 'un seul', 'depuis un etage', 'reste allume', 'en permanence', 'lumiere', 'eclairage'],
      [C('hors_tension', 'Circuit consigné : mesurer à l’ohmmètre le contact de chaque bouton poussoir ou interrupteur du circuit, au repos puis actionné.', 'Contact ouvert au repos, fermé actionné, sur chaque point de commande.',
         'Trouver le point de commande défaillant ou resté collé.')],
      'Circuit consigné : remplacer le bouton poussoir ou l’interrupteur en cause, puis vérifier la commande depuis chaque point.',
      { diff: false }),
    H('Lampe, luminaire ou alimentation de luminaire hors service', 'Quand un seul point lumineux est éteint, clignote ou s’allume faiblement, c’est le luminaire lui-même : source, alimentation électronique (driver), ballast ou douille.',
      ['+clignot', '+un seul', 'neon', 'tube', 'luminaire', 'spot', 'led', 'driver', 'ballast', 'scintill', 'faiblement', 'lampe', 'ampoule'],
      [C('visuel', 'Luminaire consigné : essayer une source neuve, contrôler l’alimentation électronique ou le ballast et l’état des douilles.', 'Source, alimentation et douilles en état.',
         'Trouver l’élément du luminaire à remplacer.')],
      'Luminaire consigné : remplacer la source, l’alimentation électronique ou le luminaire complet (même flux, même indice de protection), puis faire un essai.',
      { diff: false }),
    H('Éclairage non commandé (horloge, interrupteur crépusculaire, détecteur de présence)', 'Un éclairage automatique qui ne s’allume plus, ou qui reste allumé en plein jour, vient de son organe de commande : horloge déréglée, cellule crépusculaire encrassée, détecteur de présence hors service.',
      ['+horloge', '+crepusculaire', '+detecteur de presence', 'exterieur', 'parking', 'la nuit', 'en plein jour', 'reste allume', 'ne s allume', 'eclairage', 'programmation', 'heure d ete'],
      [C('fonctionnel', 'Forcer la marche sur l’organe de commande (horloge, interrupteur crépusculaire ou détecteur) et observer l’éclairage ; relever son réglage.', 'L’éclairage suit l’organe de commande, qui est à l’heure et correctement réglé.',
         'Savoir si le défaut vient de la commande automatique.')],
      'Remettre à l’heure et reprogrammer l’horloge, nettoyer ou remplacer la cellule crépusculaire, régler ou remplacer le détecteur de présence, puis vérifier un cycle complet.',
      { diff: false }),
    /* ----- chauffage électrique ----- */
    H('Élément chauffant coupé ou phase manquante sur un appareil de chauffage', 'Un four, une étuve ou une batterie électrique qui chauffe moins vite ou moins fort a perdu une partie de sa puissance : résistance coupée, fusible fondu, contacteur ou relais statique qui n’alimente plus une phase.',
      ['+four', '+resistance', '+a moitie', '+seche', '+souffle froid', 'air froid', 'ne chauffe plus', 'chauffe moins', 'plus de temps', 'etuve', 'chauffe eau', 'aerotherme', 'batterie electrique', 'monte moins vite'],
      [C('sous_tension', 'Appareil en chauffe : mesurer l’intensité sur chaque phase (ou sur chaque élément chauffant) à la pince ampèremétrique.', 'Intensités équilibrées, conformes à la puissance de l’appareil.',
         'Une phase ou un élément sans courant se voit immédiatement.'),
       C('hors_tension', 'Appareil consigné : mesurer la résistance de chaque élément chauffant et la continuité des fusibles et des pôles du contacteur de chauffe.', 'Éléments de résistances identiques, fusibles et pôles passants.',
         'Trouver l’élément coupé ou l’organe qui n’alimente plus une phase.')],
      'Appareil consigné : remplacer l’élément chauffant coupé (même puissance, même tension), le fusible ou le contacteur en cause, contrôler l’isolement des éléments, puis vérifier les intensités en chauffe.',
      { diff: false }),

    H('Conducteur coupé ou sorti de sa borne en aval (prise, repiquage, boîte de dérivation)', 'Quand une partie seulement d’un circuit n’est plus alimentée alors que la protection est enclenchée et la tension présente au tableau, un conducteur est coupé ou sorti de sa borne entre le dernier point alimenté et le premier point mort.',
      ['+ne marchent plus', 'ne marche plus', 'prises', 'une partie', 'le reste marche', 'aucun disjoncteur', 'plus de courant', 'plus rien', 'bureau', 'piece', 'enclenche'],
      [C('sous_tension', 'Mesurer la tension point par point le long du circuit (prises, boîtes de dérivation) pour situer le dernier point alimenté et le premier point sans tension.', 'Tension présente sur tous les points du circuit.',
         'La coupure est entre le dernier point alimenté et le premier point mort.'),
       C('hors_tension', 'Circuit consigné : ouvrir le dernier point alimenté et le premier point sans tension, contrôler les bornes, les repiquages et la continuité du tronçon entre les deux.', 'Conducteurs serrés dans leurs bornes, repiquages sains, continuité du tronçon.',
         'Trouver le conducteur sorti, coupé ou brûlé.')],
      'Circuit consigné : refaire la connexion (conducteur recoupé, borne ou appareillage remplacé s’il a chauffé), supprimer les repiquages douteux, puis contrôler la tension à chaque point et la continuité du conducteur de protection.',
      { diff: false }),
    H('Protection inadaptée au courant d’appel (calibre ou courbe)', 'Un disjoncteur qui déclenche à l’instant où l’on enclenche un moteur, un transformateur ou une rangée de luminaires, puis tient s’il passe ce cap, réagit au courant d’appel : courbe ou calibre inadapté au récepteur.',
      ['+a l enclenchement', '+au demarrage', 'transformateur', 'courbe', 'appel', 'une fois sur', 'parfois', 'allumage', 'led', 'moteur', 'disjonct'],
      [C('sous_tension', 'Mesurer le courant d’appel à la mise sous tension (pince ampèremétrique en mode crête) et le comparer au seuil magnétique du disjoncteur (courbe B, C ou D).', 'Courant d’appel inférieur au seuil magnétique du disjoncteur.',
         'Savoir si c’est la pointe de démarrage qui fait déclencher.'),
       C('hors_tension', 'Circuit consigné : contrôler l’isolement et l’absence de court-circuit du récepteur et de sa ligne.', 'Isolement correct, pas de court-circuit.',
         'Écarter un vrai défaut avant de conclure à une protection inadaptée.',
         { localize: true, onConform: 'Récepteur et ligne sains : c’est bien la pointe de courant qui fait déclencher.' })],
      'Remplacer le disjoncteur par une courbe adaptée au récepteur (courbe D pour fort courant d’appel), à calibre égal si la section du câble ne permet pas plus, ou limiter l’appel (démarreur, mise sous tension échelonnée). Toute augmentation de calibre se justifie par la section du câble.',
      { diff: false }),
    H('Défaut de mise à la terre (masse sous tension, picotements)', 'Des picotements au toucher d’une carcasse ou d’une robinetterie signalent une masse portée à un potentiel dangereux : conducteur de protection interrompu, conjugué à un défaut d’isolement d’un appareil.',
      ['+picot', '+chatouill', 'prend le courant', 'carcasse', 'masse', 'terre', 'decharge', 'en touchant', 'robinet'],
      [C('sous_tension', 'Mesurer la tension entre la masse concernée et une terre de référence (autre masse reliée, borne de terre).', 'Tension nulle entre la masse et la terre.',
         'Constater et chiffrer le danger.'),
       C('hors_tension', 'Installation consignée : mesurer la continuité du conducteur de protection entre la masse et la barrette de terre, puis l’isolement de l’appareil.', 'Continuité du conducteur de protection (quelques dixièmes d’ohm), isolement de l’appareil > 1 MΩ.',
         'Trouver où la terre est interrompue et quel appareil fuit.')],
      'Mettre l’appareil hors service tant que le défaut subsiste. Consigné : rétablir la continuité du conducteur de protection, réparer ou remplacer l’appareil dont l’isolement est insuffisant, vérifier la présence et le fonctionnement du différentiel, puis recontrôler la tension de contact.',
      { diff: null }),

    H('Onduleur : batteries en fin de vie', 'Un onduleur qui bipe, passe en dérivation (bypass) ou tient à peine quelques secondes à la coupure a ses batteries usées ; elles se remplacent tous les 3 à 5 ans.',
      ['+onduleur', '+bypass', 'bip', 'autonomie', 'batterie', 'coupure', 'salle serveur', 'ups'],
      [C('fonctionnel', 'Lancer l’autotest de l’onduleur et relever l’âge des batteries, leur tension et l’autonomie annoncée.', 'Autotest réussi, batteries de moins de 4 ans, autonomie conforme.',
         'L’onduleur sait tester lui-même ses batteries.')],
      'Remplacer le jeu complet de batteries par le modèle prescrit (onduleur en dérivation manuelle si la charge ne peut pas être coupée), noter la date, puis refaire l’autotest. Tension continue dangereuse : intervention réservée à une personne habilitée.',
      { requis: ['onduleur', 'ups'] }),
    H('Batterie de condensateurs : gradin hors service', 'Un mauvais facteur de puissance et une facturation d’énergie réactive, avec la batterie de compensation en défaut, viennent de gradins hors service : fusibles fondus, condensateurs gonflés, contacteurs usés, ou régulateur déréglé.',
      ['+batterie de condensateurs', '+cos phi', '+reactif', 'compensation', 'gradin', 'varmetrique', 'facteur de puissance'],
      [C('sous_tension', 'Mesurer à la pince l’intensité absorbée par chaque gradin enclenché et la comparer à sa puissance.', 'Chaque gradin absorbe l’intensité correspondant à sa puissance, équilibrée sur les trois phases.',
         'Un gradin sans courant ou déséquilibré est hors service.'),
       C('hors_tension', 'Batterie consignée, condensateurs déchargés (attendre le temps prescrit et vérifier) : contrôler fusibles, contacteurs et état des condensateurs de chaque gradin.', 'Fusibles passants, condensateurs non gonflés, contacteurs en état.',
         'Trouver l’élément du gradin à remplacer.')],
      'Consigné et condensateurs déchargés : remplacer les condensateurs, fusibles et contacteurs du gradin en défaut, vérifier la ventilation de l’armoire et le réglage du régulateur, puis contrôler le facteur de puissance.',
      { requis: ['condensateur', 'cos phi', 'reactif', 'compensation'] })
  ]);
})(window.DM);
