/* DIAG-MAINT — base de pannes : électrotechnique / armoires de commande. */
(function (DM) {
  'use strict';
  const K = DM.kbTools, C = K.C, H = K.H;

  DM.kbRegister('electrotechnique', [
    K.contactDegrade(),
    H('Absence de tension de commande (fusible, transformateur, alimentation)', 'Sans tension de commande, aucun organe ne peut être piloté : voyants éteints, aucun contacteur ne colle, rien ne réagit aux boutons.',
      ['ne demarre', '+commande', 'voyant', '+rien ne se passe', '+aucune reaction', 'pas de reaction', 'eteint', 'plus rien', 'transformateur', 'fusible', 'aucun voyant'],
      [C('sous_tension', 'Mesurer la tension au secondaire du transformateur de commande (ou en sortie de l’alimentation) et en aval des fusibles de commande.', 'Tension nominale (ex. 24 V AC/DC ou 230 V AC) au secondaire comme en aval des fusibles.',
         'Savoir si le circuit de commande est alimenté.'),
       C('hors_tension', 'Armoire consignée : contrôler à l’ohmmètre les fusibles primaire et secondaire, les enroulements du transformateur et l’absence de court-circuit sur le circuit de commande.', 'Fusibles passants, enroulements continus, pas de court-circuit en aval.',
         'Trouver l’élément ouvert et la raison pour laquelle il a fondu.')],
      'Consigné : remplacer le fusible par un fusible de même calibre et de même type, après avoir cherché la cause (bobine en court-circuit, fil à la masse, transformateur). Un fusible de commande ne se surcalibre pas.'),
    H('Chaîne de commande ouverte (bouton, contact, relais thermique, verrouillage)', 'La tension de commande est présente mais n’arrive pas à la bobine : un élément en série est ouvert (bouton d’arrêt, contact 95-96 du relais thermique, verrouillage, fil).',
      ['ne demarre', '+ne colle pas', 'contacteur', 'bouton', 'marche', 'voyant sous tension', 'ordre de marche', 'pas de reaction', 'apres declenchement', 'rearme'],
      [C('sous_tension', 'À l’ordre de marche, suivre la tension point par point le long de la chaîne de commande jusqu’à la borne A1 de la bobine (arrêt d’urgence, bouton arrêt, contact 95-96 du relais thermique, verrouillages, bouton marche).', 'Tension présente jusqu’à la bobine.',
         'Trouver l’élément après lequel la tension disparaît.'),
       C('hors_tension', 'Armoire consignée : contrôler à l’ohmmètre l’élément repéré (contact, bouton, fil, borne).', 'Continuité franche, contact fermé.',
         'Confirmer l’élément ouvert avant de le remplacer.')],
      'Consigné : remplacer l’élément ouvert (contact, bouton, fil) ou réarmer le relais thermique après avoir trouvé la raison du déclenchement. Ne jamais ponter un contact de sécurité pour redémarrer.'),
    H('Bobine de contacteur coupée ou inadaptée', 'La bobine reçoit bien sa tension à l’ordre de marche, mais le contacteur ne colle pas : bobine coupée, grillée, ou d’une tension différente de celle du circuit de commande.',
      ['+ne colle pas', 'contacteur', '+bobine', 'ne s enclenche', 'ne demarre', 'tension presente', 'odeur', 'remplace'],
      [C('hors_tension', 'Contacteur consigné, bobine débranchée : mesurer la résistance de la bobine et lire sa tension nominale.', 'Résistance finie conforme au constructeur (ni 0 Ω, ni circuit ouvert) ; tension de bobine égale à la tension de commande.',
         'Une bobine coupée se mesure directement.')],
      'Consigné : remplacer la bobine (ou le contacteur) par un modèle de même tension de commande et de même calibre ; chercher la cause d’une bobine grillée (tension trop basse, circuit magnétique qui ne ferme pas, commutations trop fréquentes).'),
    H('Contacts de puissance usés ou soudés', 'Des contacts soudés empêchent l’arrêt (le moteur continue de tourner à l’ordre d’arrêt) ; des contacts usés laissent une phase mal alimentée.',
      ['+ne s arrete', '+soude', '+continue de tourner', 'colle', 'reste enclenche', 'contacteur', 'arret', 'crateres', 'usure'],
      [C('hors_tension', 'Contacteur consigné, au repos : mesurer la continuité de chaque pôle de puissance (1-2, 3-4, 5-6).', 'Trois pôles ouverts au repos.',
         'Un pôle passant au repos est soudé.'),
       C('visuel', 'Contacteur consigné : déposer le capot et contrôler l’état des contacts de puissance (cratères, perles, soudure).', 'Contacts propres, sans soudure ni usure prononcée.',
         'Constater l’état réel des contacts.')],
      'Consigné : remplacer le contacteur (calibre et catégorie d’emploi adaptés, AC-3 pour un moteur) ; chercher ce qui a soudé les contacts : court-circuit en aval, commutations trop fréquentes, tension de commande trop basse.',
      { diff: false }),
    H('Tension de commande trop faible aux bornes de la bobine', 'Un contacteur qui vibre, broute ou retombe est souvent sous-alimenté : transformateur surchargé, ligne de commande trop longue, alimentation qui s’écroule.',
      ['+vibr', '+broute', '+bourdonn', 'claqu', 'retomb', 'gresill', 'contacteur', 'bruit', 'intermitten'],
      [C('sous_tension', 'Contacteur collé : mesurer la tension aux bornes A1-A2 de sa bobine.', 'Au moins 85 % de la tension nominale de la bobine.',
         'Un contacteur ne tient franchement qu’au-dessus de 85 % de sa tension.'),
       C('sous_tension', 'Mesurer la tension au secondaire du transformateur de commande à vide puis avec tous les contacteurs collés.', 'Tension stable en charge (chute de quelques % au plus).',
         'Savoir si la source de commande s’écroule ou si la chute est dans la ligne.',
         { localize: true, onConform: 'Source de commande stable : la chute de tension est dans la ligne jusqu’à la bobine.' })],
      'Remplacer le transformateur de commande par une puissance adaptée (somme des puissances d’appel et de maintien) ou réduire la chute en ligne (section, longueur, relayage). Contrôler ensuite la tension bobine contacteurs collés.'),
    H('Circuit magnétique du contacteur encrassé ou spire de Frager cassée', 'Un contacteur bruyant alors que sa tension de bobine est correcte a un circuit magnétique qui ferme mal : faces polaires encrassées ou rouillées, corps étranger, spire de déphasage cassée.',
      ['+vibr', '+bourdonn', 'bruit', 'ronfl', 'contacteur', 'chauffe', 'poussiere'],
      [C('visuel', 'Contacteur consigné : contrôler les faces polaires du circuit magnétique (propreté, rouille, corps étranger) et la spire de Frager.', 'Faces propres et planes, spire intacte.',
         'Constater la cause du mauvais collage.')],
      'Consigné : nettoyer les faces polaires (sans les limer) ; si la spire est cassée ou les faces marquées, remplacer le contacteur.'),
    K.thermalSetting(),
    H('Chaîne de sécurité ouverte', 'Un arrêt d’urgence, une fin de course ou un contact de porte ouvert interrompt la commande ; le module de sécurité attend parfois seulement son réarmement.',
      ['+arret d urgence', '+securite', 'ne demarre', 'defaut', 'porte', 'fin de course', 'relais de securite', 'module de securite', 'rearmement', 'carter'],
      [C('visuel', 'Relever l’état du module de sécurité (voyants des canaux, sorties, attente de réarmement) et de chaque arrêt d’urgence.', 'Les deux canaux fermés, module réarmé.',
         'Savoir quel canal est ouvert avant de mesurer.',
         { localize: true, onConform: 'Module de sécurité réarmé, canaux fermés : la sécurité n’est pas en cause.' }),
       C('hors_tension', 'Armoire consignée : contrôler la continuité de chaque canal de la chaîne de sécurité, élément par élément (arrêts d’urgence, interrupteurs de porte, fins de course).', 'Continuité sur chaque canal, tous les éléments fermés.',
         'Trouver l’élément ouvert ou le contact défaillant.')],
      'Consigné : remplacer le contact ou l’organe défaillant par un modèle équivalent, vérifier les deux canaux, réarmer et faire un essai de chaque arrêt d’urgence. Ne jamais shunter un dispositif de sécurité.'),
    H('Défaut de câblage / bornier', 'Un défaut intermittent, sensible aux vibrations ou aux manœuvres de porte, évoque un conducteur desserré ou blessé.',
      ['+intermitten', 'aleatoire', 'parfois', '+vibr', 'de temps en temps', 'quand on tape', 'porte', 'bornier', 'fil'],
      [C('hors_tension', 'Armoire consignée : contrôler le serrage des borniers et la tenue de chaque conducteur de commande (traction légère), en particulier au passage des portes.', 'Serrage correct, aucun conducteur qui se dégage, continuité stable en manipulant.',
         'Trouver le conducteur qui fait le défaut intermittent.')],
      'Consigné : refaire la connexion (embout serti, serrage au couple), remplacer le conducteur blessé, puis faire un essai en sollicitant le câblage.'),
    H('Auto-maintien défaillant (contact auxiliaire)', 'Le moteur ne tourne que tant qu’on appuie sur le bouton marche : le contact auxiliaire d’auto-maintien (13-14) ne se ferme plus ou son fil est coupé.',
      ['+tant qu on appuie', '+retomb', '+maintien', '+relache', '+lache', 'quand j appuie', 'bouton marche', 'ne reste pas', 's arrete des qu on lache'],
      [C('hors_tension', 'Armoire consignée : actionner le contacteur à la main et mesurer la continuité du contact d’auto-maintien (13-14) et de son câblage jusqu’au bouton marche.', 'Contact fermé et continuité franche quand le contacteur est actionné.',
         'Vérifier directement le contact qui doit maintenir la bobine.')],
      'Consigné : remplacer le bloc de contacts auxiliaires (ou refaire son câblage), puis vérifier marche, maintien et arrêt.'),
    H('Séquence de démarrage étoile-triangle défaillante', 'Un démarreur qui reste en étoile, ou dont le passage en triangle se fait mal (temporisation, verrouillage, contacteur triangle), fait déclencher la protection ou laisse le moteur sans couple.',
      ['etoile', 'triangle', 'demarrage', '+reste en etoile', '+ne passe pas', 'tempo', 'a coup', 'au passage', 'ne monte pas en vitesse', 'pas de couple'],
      [C('fonctionnel', 'Observer la séquence de démarrage : contacteur de ligne et contacteur étoile, puis passage au contacteur triangle après la temporisation ; relever la durée.', 'Passage étoile → triangle franc, une fois le moteur lancé (quelques secondes selon la charge).',
         'Voir à quel moment la séquence s’écarte de la normale.'),
       C('hors_tension', 'Armoire consignée : contrôler le relais temporisé, le verrouillage entre contacteurs étoile et triangle, et la bobine du contacteur triangle.', 'Temporisation réglée et fonctionnelle, verrouillage correct, bobine continue.',
         'Trouver l’organe qui empêche le passage.')],
      'Consigné : remplacer l’organe défaillant (relais temporisé, contact de verrouillage, contacteur triangle) et régler la temporisation sur la durée réelle de mise en vitesse.',
      { diff: false }),

    H('Relais de contrôle de phases en défaut (ordre ou absence de phase)', 'Après une intervention sur le réseau ou sur l’alimentation, une machine qui refuse de démarrer sans aucun défaut apparent a parfois son relais de contrôle de phases qui interdit la marche : phases inversées, phase absente, tension hors plage.',
      ['+ordre des phases', '+relais de phase', 'controle de phase', 'apres coupure', 'travaux enedis', 'groupe electrogene', 'changement de transformateur', 'ne demarre', 'depuis la coupure'],
      [C('visuel', 'Relever l’état du relais de contrôle de phases (voyants) et vérifier l’ordre des phases à l’entrée de l’armoire avec un contrôleur de rotation.', 'Relais enclenché, ordre des phases direct, trois phases présentes.',
         'Le relais dit lui-même pourquoi il interdit la marche.')],
      'Consigné : rétablir l’ordre des phases en croisant deux phases à l’arrivée de l’armoire (jamais en trompant le relais), ou rétablir la phase absente ; vérifier ensuite le sens de rotation de chaque moteur.',
      { diff: false })
  ]);
})(window.DM);
