/* DIAG-MAINT — base de pannes : climatisation, pompes à chaleur, froid, ventilation, chauffage. */
(function (DM) {
  'use strict';
  const K = DM.kbTools, C = K.C, H = K.H;

  DM.kbRegister('hvac', [
    H('Surintensité : consommation excessive de l’unité extérieure', 'Un déclenchement de la protection magnétothermique seule (sans le différentiel) après quelques minutes de fonctionnement oriente vers une intensité absorbée trop élevée (compresseur en difficulté, haute pression, ventilateur).',
      ['disjonct', 'declench', 'saute', 'surintensit', 'minutes', 'apres quelques', 'c16', 'c20', 'c25', 'c32', 'protection'],
      [C('sous_tension', 'Mesurer l’intensité absorbée par l’unité extérieure pendant son fonctionnement (pince ampèremétrique sur la phase d’alimentation).', 'Inférieure ou égale à l’intensité maximale indiquée sur la plaque signalétique / la notice.'),
       C('visuel', 'Unité consignée : contrôler la propreté du condenseur et la rotation libre du ventilateur extérieur.', 'Batterie propre, ventilateur libre.')],
      'Unité consignée : nettoyer la batterie du condenseur (de l’intérieur vers l’extérieur, sans plier les ailettes), remettre en état le ventilateur, puis vérifier que l’intensité absorbée repasse sous la valeur de la plaque. Ne pas remplacer le disjoncteur par un calibre supérieur.',
      { diff: false }),
    H('Manque de fluide frigorigène (fuite)', 'Une charge insuffisante réduit la puissance frigorifique : basse pression faible, surchauffe élevée, givre sur une partie seulement de l’évaporateur, compresseur qui tourne longtemps.',
      ['ne refroidit', 'froid insuffisant', 'pas de froid', 'plus de froid', 'plus froid', 'tiede', 'refroidit mal', 'refroidit moins', '+givre', 'glace', 'fuit', 'bulle', '+basse pression', 'bp', 'ne chauffe', 'huile', 'tourne en continu', 'moins bien'],
      [C('fluide', 'Relever les pressions HP/BP au manifold, calculer surchauffe et sous-refroidissement.', 'Valeurs conformes au constructeur (surchauffe typique 5 à 8 K).',
         'Une surchauffe élevée avec un sous-refroidissement faible signe un manque de charge.'),
       C('fluide', 'Rechercher une fuite (détecteur électronique, bulles, traces d’huile aux raccords, dudgeons, vannes et échangeurs).', 'Aucune fuite détectée.',
         'Une charge qui manque est toujours partie quelque part : trouver où avant de recharger.',
         { localize: true, onConform: 'Fuite non trouvée au détecteur : faire un contrôle d’étanchéité sous pression d’azote.' })],
      'Réparer la fuite, contrôler l’étanchéité, tirer au vide, puis recharger à la masse indiquée sur la plaque. Intervention réservée à un opérateur titulaire de l’attestation d’aptitude, avec fiche d’intervention ; aucun appoint sans réparation de la fuite.'),
    H('Filtres ou échangeurs encrassés', 'L’encrassement réduit le débit d’air et l’échange thermique : soufflage faible, givrage de l’évaporateur, odeur, puissance en baisse.',
      ['+debit', 'faible', 'souffle', '+sale', 'poussiere', 'odeur', 'givre', '+encrass', 'haute pression', 'hp', '+filtre', 'peu d air'],
      [C('visuel', 'Contrôler l’état des filtres et des échangeurs (évaporateur / condenseur).', 'Filtres propres, ailettes dégagées.',
         'Le contrôle le plus simple, à faire en premier.')],
      'Unité consignée : nettoyer ou remplacer les filtres, nettoyer les batteries avec un produit adapté, puis contrôler l’écart de température entre reprise et soufflage.'),
    H('Condenseur encrassé ou mal ventilé (haute pression)', 'Une coupure en haute pression par forte chaleur vient d’un condenseur qui n’évacue plus sa chaleur : batterie colmatée (pollen, poussière), ventilateur à l’arrêt, air recyclé.',
      ['+haute pression', '+hp', 'coupe', 'canicule', 'chaleur', 'ete', 'pressostat', 'encrass', 'pollen', 'peuplier', '+condenseur', 'apres midi', 'securite'],
      [C('fluide', 'Relever la haute pression et la température de condensation, et la comparer à la température de l’air extérieur.', 'Écart de l’ordre de 10 à 15 K entre la température de condensation et l’air extérieur.',
         'Un écart trop grand signe un condenseur qui échange mal.'),
       C('visuel', 'Unité consignée : contrôler la batterie du condenseur (colmatage, ailettes couchées), la rotation du ventilateur et le dégagement autour de l’unité.', 'Batterie propre, ventilateur fonctionnel, air libre autour de l’unité.',
         'Constater la cause du mauvais échange.')],
      'Unité consignée : nettoyer la batterie du condenseur, redresser les ailettes, remettre en état le ventilateur et dégager l’unité, puis vérifier la haute pression en fonctionnement.'),
    H('Condensateur de démarrage / permanent défaillant', 'Un condensateur hors tolérance empêche le démarrage du compresseur ou du ventilateur : bourdonnement, puis coupure par la protection interne.',
      ['ne demarre', 'compresseur', 'ventilateur', '+bourdonn', 'ronfl', 'claqu', 'demarre pas', '+condensateur', 'gonfle'],
      [C('hors_tension', 'Décharger puis mesurer la capacité du condensateur (capacimètre).', 'Capacité dans la tolérance (±5 à 10 % de la valeur marquée).',
         'Le condensateur se contrôle en une mesure.')],
      'Unité consignée : remplacer le condensateur par un modèle de même capacité et de tension au moins égale, puis contrôler l’intensité de démarrage et de marche.',
      { diff: false }),
    H('Défaut de sonde ou de régulation', 'Une sonde dérivée ou coupée fausse la régulation ou provoque un code défaut.',
      ['temperature', 'consigne', 'affiche', 'code', 'erreur', 'defaut', '+sonde', 'regul', 'e1', 'e2', 'clignot', 'thermistance'],
      [C('hors_tension', 'Déconnecter la sonde et mesurer sa résistance ; comparer à la table R/T constructeur (ex. CTN 10 kΩ à 25 °C).', 'Valeur conforme à la table R/T à la température mesurée.',
         'Une sonde coupée ou en court-circuit se mesure directement.')],
      'Unité consignée : remplacer la sonde par la référence du constructeur, la positionner et la fixer correctement, effacer le défaut et vérifier la régulation.'),
    H('Moto-ventilateur défectueux', 'Un ventilateur à l’arrêt ou lent provoque haute pression (condenseur) ou givrage (évaporateur).',
      ['+ventilateur', 'bruit', 'vibr', '+ne tourne', 'chauffe', 'haute pression', 'hp', 'helice', 'turbine'],
      [C('sous_tension', 'Vérifier la rotation du ventilateur à la demande et mesurer son intensité absorbée.', 'Rotation franche, intensité ≤ valeur plaque.',
         'Voir si le ventilateur tourne et s’il force.'),
       C('hors_tension', 'Unité consignée : faire tourner l’hélice à la main, mesurer les enroulements du moteur et son condensateur.', 'Rotation libre, enroulements continus et isolés, condensateur dans la tolérance.',
         'Départager roulements, bobinage et condensateur.')],
      'Unité consignée : remplacer le moteur de ventilateur (ou son condensateur), contrôler le sens de rotation et l’équilibrage de l’hélice.'),
    H('Évacuation des condensats obstruée', 'Un bac ou une évacuation bouchée fait déborder l’eau de l’unité intérieure.',
      ['+fuit', '+eau', '+goutt', '+condensat', '+coule', 'debord', 'plafond', 'tache', 'unite interieure', 'bac'],
      [C('visuel', 'Contrôler le bac, le siphon et la pente de l’évacuation des condensats ; verser de l’eau dans le bac pour vérifier l’écoulement.', 'Écoulement libre et rapide.',
         'Voir si l’eau s’évacue.')],
      'Unité consignée : déboucher et nettoyer le bac et l’évacuation (dépôts, algues), vérifier la pente et le siphon, puis faire un essai d’écoulement.'),
    H('Pompe de relevage des condensats défaillante', 'Quand les condensats sont relevés par une pompe, un bac qui déborde ou une unité qui se met en sécurité niveau haut désignent la pompe ou son flotteur.',
      ['+pompe de relevage', 'condensat', 'eau', 'fuit', 'coule', 'bac plein', 'flotteur', 'niveau haut', 'debord'],
      [C('fonctionnel', 'Verser de l’eau dans le bac de la pompe de relevage et observer son démarrage et l’évacuation.', 'La pompe démarre et évacue l’eau.',
         'Essai direct de la pompe.')],
      'Unité consignée : nettoyer le bac et le flotteur de la pompe, déboucher le tube de refoulement ; remplacer la pompe si elle ne démarre pas alors qu’elle est alimentée.'),
    H('Compresseur en défaut (protection thermique / bobinage)', 'Des arrêts répétés ou un compresseur qui ne démarre pas peuvent venir de ses enroulements.',
      ['+compresseur', 's arrete', 'coupe', 'chauffe', 'intermitten', 'disjonct', 'bloqu', 'grille'],
      [C('hors_tension', 'Mesurer les résistances des enroulements (C-S, C-R, S-R) et l’isolement à la masse.', 'R(S-R) = R(C-S) + R(C-R) ; isolement > 1 MΩ.',
         'Vérifier le compresseur lui-même, câblage débranché.')],
      'Compresseur à remplacer par un opérateur attesté : récupération du fluide, remplacement du déshydrateur, contrôle d’acidité de l’huile, tirage au vide et charge ; chercher la cause (manque de fluide, haute pression, tension d’alimentation).'),
    H('Courroie de ventilateur cassée ou détendue', 'Sur une centrale de traitement d’air ou un caisson, le moteur tourne mais l’air ne circule plus : la courroie est cassée, ou elle patine en sifflant.',
      ['+courroie', '+cta', 'centrale', 'debit d air', 'pas de soufflage', 'pressostat d air', 'defaut debit', 'moteur tourne', 'siffl', 'caisson', 'extracteur', 'plus d air'],
      [C('visuel', 'Ventilateur consigné : contrôler la courroie (présence, tension, usure) et l’alignement des poulies.', 'Courroie en place, tendue (flèche conforme), poulies alignées.',
         'Contrôle direct de la transmission.')],
      'Ventilateur consigné : remplacer le jeu complet de courroies, régler la tension et l’alignement des poulies, contrôler les roulements du ventilateur, puis vérifier le débit d’air et le pressostat.'),
    H('Défaut de dégivrage (pompe à chaleur en mode chaud)', 'En hiver, une unité extérieure qui se prend en bloc de glace ne dégivre plus : sonde de dégivrage, carte, ou inversion de cycle.',
      ['+givre', '+glace', '+unite exterieure', 'mode chaud', 'chauffage', 'hiver', 'pac', 'ne chauffe', '+degivrage', 'bloc de glace', 'gel'],
      [C('fonctionnel', 'Lancer ou observer un cycle de dégivrage : inversion de cycle, arrêt du ventilateur extérieur, fonte de la glace.', 'Le cycle se lance et la batterie est entièrement dégivrée en quelques minutes.',
         'Voir si le dégivrage se déclenche et s’il va au bout.'),
       C('hors_tension', 'Unité consignée : mesurer la sonde de dégivrage (batterie extérieure) et la comparer à la table R/T du constructeur.', 'Valeur conforme à la table à la température mesurée, sonde bien fixée sur la batterie.',
         'La sonde de batterie commande le dégivrage.')],
      'Unité consignée : remplacer et refixer la sonde de dégivrage (ou la carte si la sonde est bonne), dégager l’écoulement sous l’unité, puis vérifier un cycle complet.'),
    H('Vanne 4 voies bloquée ou non commandée', 'Une pompe à chaleur qui souffle froid en mode chaud (ou l’inverse) n’inverse plus son cycle : bobine de la vanne 4 voies non alimentée ou coupée, ou tiroir bloqué.',
      ['+vanne 4 voies', '+vanne quatre voies', 'reste en froid', '+souffle froid', 'ne passe pas en chaud', 'inversion', 'mode chaud', 'mauvais mode'],
      [C('sous_tension', 'En demande d’inversion, mesurer la tension aux bornes de la bobine de la vanne 4 voies.', 'Tension de commande présente pendant la demande.',
         'Savoir si la vanne est commandée.',
         { localize: true, onConform: 'Bobine alimentée : la commande est bonne, la vanne ou sa bobine est en cause.' }),
       C('fonctionnel', 'Bobine alimentée : relever la température des tubulures de la vanne et écouter la bascule ; mesurer la résistance de la bobine, unité consignée.', 'Bascule franche, tubulures conformes au mode demandé, bobine continue.',
         'Départager bobine coupée et tiroir bloqué.')],
      'Remplacer la bobine si elle est coupée. Si le tiroir est bloqué, la vanne se remplace par un opérateur attesté (récupération du fluide, brasage sous azote, tirage au vide, charge).'),
    H('Défaut de communication entre unité intérieure et extérieure', 'Un code de communication, surtout après des travaux ou une intervention, vient du câble de liaison : fil desserré, inversé, coupé, ou parasité.',
      ['+communication', '+liaison', 'interconnexion', 'code', 'clignot', 'apres travaux', 'cable', 'ne dialogue', 'bornier'],
      [C('sous_tension', 'Mesurer les tensions sur le bornier de liaison entre unités, des deux côtés, selon la notice.', 'Tensions conformes à la notice, identiques des deux côtés.',
         'Voir si le signal part et arrive.'),
       C('hors_tension', 'Unités consignées : contrôler le serrage, le repérage et la continuité de chaque conducteur du câble de liaison.', 'Conducteurs continus, serrés, raccordés borne à borne.',
         'Trouver le conducteur coupé, desserré ou inversé.')],
      'Unités consignées : refaire le raccordement du câble de liaison (même repérage des deux côtés, câble sans jonction), puis effacer le défaut et vérifier le démarrage.'),
    H('Vase d’expansion dégonflé ou membrane percée', 'Sur un circuit de chauffage, une pression qui monte fort à chaud (soupape qui goutte) puis retombe à froid, avec des appoints d’eau répétés, signe un vase d’expansion qui ne joue plus son rôle.',
      ['+vase', '+soupape', 'pression monte', 'pression chute', 'chaudiere', '+manque d eau', 'appoint', 'goutt', 'rajouter de l eau', 'pression', 'bar'],
      [C('fluide', 'Relever la pression du circuit à froid puis à chaud.', 'Variation limitée (quelques dixièmes de bar) entre froid et chaud.',
         'Une forte variation de pression avec la température désigne le vase.'),
       C('fluide', 'Vase isolé et vidangé côté eau : mesurer sa pression de gonflage à la valve.', 'Pression de gonflage égale à la pression statique de l’installation plus 0,2 à 0,3 bar (de l’air sort, pas de l’eau).',
         'Savoir si le vase est dégonflé ou percé.')],
      'Vase isolé et vidangé : le regonfler à la pression voulue ; si de l’eau sort à la valve, la membrane est percée et le vase se remplace. Remettre le circuit en pression à froid et contrôler la soupape.'),
    H('Brûleur en sécurité : défaut d’allumage ou de détection de flamme', 'Un brûleur qui se met en sécurité après un essai d’allumage a un problème d’étincelle, d’arrivée de combustible ou de détection de flamme (cellule, sonde d’ionisation).',
      ['+bruleur', '+mise en securite', 'flamme', 'allumage', 'rearme', 'electrode', 'ionisation', 'cellule', 'gicleur', 'fioul', 'gaz', 'voyant rouge', 'chaudiere'],
      [C('fonctionnel', 'Réarmer et observer la séquence : préventilation, étincelle, ouverture de la vanne, apparition de la flamme, temps de sécurité.', 'Séquence complète, flamme stable et détectée.',
         'Voir à quelle étape la séquence s’arrête.'),
       C('visuel', 'Brûleur consigné, combustible fermé : contrôler électrodes (écartement, encrassement), sonde d’ionisation ou cellule, gicleur et filtre.', 'Électrodes propres et réglées, détection propre, gicleur et filtre en état.',
         'Trouver l’organe qui empêche l’allumage ou la détection.')],
      'Brûleur consigné : nettoyer et régler les électrodes, nettoyer ou remplacer la cellule ou la sonde, remplacer gicleur et filtre, puis contrôler la combustion à l’analyseur. Intervention gaz réservée à un professionnel qualifié.'),
    H('Pas de demande de la régulation (thermostat, programmation, télécommande)', 'Un appareil qui ne démarre pas sans aucun défaut affiché n’a parfois simplement pas de demande : thermostat mal réglé, programmation horaire, piles de télécommande.',
      ['+thermostat', '+telecommande', 'ne demarre pas', 'aucun defaut', 'piles', 'consigne', 'programmation', 'horloge', 'aucune reaction'],
      [C('fonctionnel', 'Vérifier mode, consigne, programmation horaire et piles ; forcer une demande franche (consigne très éloignée de la température ambiante).', 'L’appareil démarre à la demande.',
         'Écarter un simple problème de commande avant de démonter.')],
      'Remettre en ordre la commande (mode, consigne, programmation, piles) ; remplacer le thermostat ou le récepteur s’il n’envoie pas la demande.'),
    H('Réseau de ventilation encrassé, déboîté ou écrasé', 'Une VMC qui n’aspire plus alors que le caisson tourne a des bouches colmatées, une gaine déboîtée dans les combles ou un conduit écrasé.',
      ['+vmc', '+bouche', 'extraction', 'humidite', 'condensation', 'moisissure', 'n aspire', 'gaine', 'combles'],
      [C('visuel', 'Contrôler l’aspiration aux bouches (feuille de papier ou anémomètre), leur propreté, puis le parcours des gaines jusqu’au caisson.', 'Aspiration nette à chaque bouche, gaines emboîtées et non écrasées.',
         'Trouver où le débit se perd.')],
      'Nettoyer ou remplacer les bouches, remboîter et fixer les gaines, remplacer les tronçons écrasés, puis contrôler le débit à chaque bouche.'),
    H('Dégivrage de l’évaporateur défaillant (chambre froide)', 'Une chambre froide qui remonte en température avec un évaporateur pris dans la glace ne dégivre plus : résistances coupées, horloge ou sonde de fin de dégivrage.',
      ['+chambre froide', 'evaporateur', 'bloc de glace', 'givre', 'glace', '+resistance de degivrage', 'monte en temperature', 'degivrage', 'negative'],
      [C('fonctionnel', 'Lancer un dégivrage manuel et mesurer l’intensité absorbée par les résistances de dégivrage.', 'Les résistances chauffent, intensité conforme à leur puissance.',
         'Voir si le dégivrage se lance et si les résistances chauffent.'),
       C('hors_tension', 'Évaporateur consigné : mesurer chaque résistance de dégivrage et contrôler la sonde ou le thermostat de fin de dégivrage.', 'Résistances continues et isolées, fin de dégivrage fonctionnelle.',
         'Trouver l’élément défaillant.')],
      'Consigné : dégivrer complètement l’évaporateur, remplacer les résistances coupées ou la sonde de fin de dégivrage, vérifier l’écoulement et la résistance du tube d’évacuation, puis contrôler un cycle complet.'),

    H('Fuite sur le circuit de chauffage (purgeur, soupape, raccord)', 'Une pression qui retombe en quelques jours alors que le vase d’expansion est bon signe une perte d’eau : purgeur automatique, soupape, presse-étoupe de vanne, raccord ou radiateur.',
      ['+manque d eau', 'pression', 'remettre de l eau', 'je remets', 'rajouter de l eau', 'appoint', 'retomb', 'tous les', 'jours apres', 'chaudiere', 'bar'],
      [C('visuel', 'Inspecter la chaufferie et le réseau : purgeurs automatiques, soupape de sécurité et son écoulement, presse-étoupes des vannes, raccords, pieds de radiateurs, traces de calcaire ou de rouille.', 'Aucune trace d’eau, soupape sèche.',
         'Une fuite lente laisse presque toujours une trace.')],
      'Circuit isolé et refroidi : remplacer le purgeur, la soupape ou le joint qui fuit, remettre en pression à froid, purger, puis surveiller la pression sur plusieurs jours.'),

    H('Vanne de régulation ou moteur thermique bloqué', 'Un émetteur (ventilo-convecteur, radiateur, batterie) qui souffle ou reste froid alors que les autres chauffent, ventilateur en marche, n’est pas irrigué : vanne de régulation fermée, tête thermique ou servomoteur hors service.',
      ['+ventilo', '+pas chaud', 'souffle froid', 'une seule piece', 'les autres chauffent', 'les autres pieces', 'vanne', 'radiateur froid', 'reste froid', 'batterie'],
      [C('fluide', 'En demande de chaud, relever la température des tuyauteries d’arrivée et de retour de l’émetteur.', 'Arrivée chaude et retour tiède : l’émetteur est irrigué.',
         'Savoir si l’eau circule dans l’émetteur.'),
       C('fonctionnel', 'En demande, contrôler la vanne de régulation : tension de commande présente sur sa tête thermique ou son servomoteur, et déplacement de la tige.', 'Commande présente et vanne qui s’ouvre.',
         'Départager la commande de la vanne elle-même.')],
      'Remplacer la tête thermique ou le servomoteur hors service (ou dégripper et remplacer la vanne), purger l’émetteur, puis vérifier l’écart de température entre arrivée et retour.'),
    H('Débit d’eau insuffisant (filtre à tamis, circulateur, air)', 'Un défaut de débit sur une pompe à chaleur air/eau ou un groupe d’eau glacée vient d’un filtre à tamis colmaté, d’un circulateur à l’arrêt, d’une vanne fermée ou d’air dans le circuit.',
      ['+defaut debit', '+debit d eau', 'controleur de debit', 'flow', 'filtre a tamis', 'eau glacee', 'air eau', 'ecart de temperature'],
      [C('fluide', 'Relever l’écart de température entre départ et retour d’eau et la pression différentielle aux bornes de l’échangeur.', 'Écart de température de l’ordre de 5 K, perte de charge conforme à la notice.',
         'Un écart de température trop grand signe un débit trop faible.'),
       C('visuel', 'Circuit isolé : contrôler le filtre à tamis, la position des vannes, la rotation du circulateur et les points de purge.', 'Filtre propre, vannes ouvertes, circulateur en marche, pas d’air.',
         'Trouver ce qui freine le débit.')],
      'Circuit isolé : nettoyer le filtre à tamis, ouvrir les vannes, purger l’air, remettre en état le circulateur, puis vérifier l’écart de température et le contrôleur de débit.'),

    H('Air dans le circuit de chauffage', 'Des radiateurs froids en partie haute de l’installation avec des bruits d’eau signalent de l’air dans le circuit : purge insuffisante après un remplissage, purgeur automatique bloqué, pression trop basse pour les étages.',
      ['+bruits d eau', '+glouglou', 'dernier etage', 'en haut', 'radiateurs froids', 'radiateur froid', 'froid en haut', 'purge', 'air', 'gargouill'],
      [C('fluide', 'Purger les radiateurs les plus hauts et relever la pression du circuit à froid.', 'Pas d’air à la purge, pression suffisante pour la hauteur du bâtiment (environ 0,1 bar par mètre, plus 0,5 bar).',
         'De l’air à la purge ou une pression trop basse explique des radiateurs hauts froids.')],
      'Purger du bas vers le haut, circulateur arrêté, refaire la pression à froid, vérifier les purgeurs automatiques ; si l’air revient, chercher une entrée d’air ou un vase d’expansion défaillant.',
      { requis: ['radiateur', 'chauffage', 'plancher chauffant'] }),
    H('Carte électronique détruite (surtension, orage)', 'Après un orage ou une surtension, un appareil qui ne démarre plus du tout, ou qui fait déclencher sa protection, a souvent sa carte d’alimentation ou de puissance détruite.',
      ['+orage', '+foudre', '+surtension', 'carte', 'plus rien', 'ne demarre plus', 'eteint', 'depuis l orage'],
      [C('visuel', 'Appareil consigné : inspecter les cartes électroniques (fusible de carte, varistance, composants éclatés ou noircis, pistes brûlées).', 'Fusible de carte bon, aucun composant marqué.',
         'Une carte détruite par une surtension se voit le plus souvent à l’œil.')],
      'Consigné : remplacer la carte par la référence du constructeur, contrôler le compresseur et les ventilateurs avant remise sous tension, et proposer une protection contre les surtensions sur le départ.')
  ]);
})(window.DM);
