/* DIAG-MAINT — base de pannes : sécurité incendie (SSI, détection, mise en sécurité, éclairage de sécurité). */
(function (DM) {
  'use strict';
  const K = DM.kbTools, C = K.C, H = K.H;

  DM.kbRegister('incendie', [
    H('Câble de boucle endommagé ou agressé (défaut terre / court-circuit intermittent)',
      'Un défaut terre fugitif, des courts-circuits ou des pertes de points qui reviennent seuls orientent vers un câble blessé ou qui bouge. ' +
      'Des défauts qui apparaissent à heure fixe (démarrage d’un équipement voisin : CTA, moteur) ou après des travaux signent une agression mécanique du câble (vis, collier, vibration).',
      ['+defaut terre', '+boucle', 'court circuit', 'boucle ouverte', 'isolateur', 'travaux', 'faux plafond', 'intermitten', 'derangement',
        'disparaissent', 'perte des points', 'reviennent', 'cta', 'vibr', 'luminaire'],
      [C('fonctionnel', 'Exploiter l’historique de l’ECS : types de dérangement, nombre, horaires, points et isolateurs concernés.',
          'Défauts sans lien avec un horaire ni une zone (sinon : chercher ce qui se passe à ces heures-là, dans cette zone).',
          'Relier les défauts à un moment ou à un équipement avant toute mesure.',
          { localize: true, onConform: 'Pas de corrélation visible : poursuivre par les mesures.' }),
       C('visuel', 'Relever les isolateurs de court-circuit qui s’ouvrent lors du défaut, pour délimiter le tronçon en cause.',
          'Aucun isolateur ouvert (sinon : le défaut est entre les isolateurs qui s’ouvrent).',
          'Réduire la zone de recherche à quelques points.',
          { localize: true, onConform: 'Aucun isolateur ne s’ouvre : pas de court-circuit franc au moment du relevé.' }),
       C('hors_tension', 'Boucle déconnectée de l’ECS (mise hors service signalée à l’exploitant) : mesurer la résistance de boucle (A+ à B+, A− à B−) et la comparer à la notice.',
          'Valeur conforme à la notice (continuité correcte).',
          'Écarter une coupure franche ou une mauvaise connexion.',
          { localize: true, onConform: 'Continuité correcte : pas de coupure franche, le défaut est un défaut d’isolement ou intermittent.' }),
       C('hors_tension', 'Boucle déconnectée, points retirés : mesurer l’isolement de chaque conducteur par rapport à la terre au mégohmmètre 500 V.',
          'Chaque conducteur > 1 MΩ, valeur stable.',
          'Confirmer le défaut d’isolement et le conducteur touché.'),
       C('hors_tension', 'Mesurer l’isolement tronçon par tronçon, en ouvrant la boucle aux isolateurs ou aux boîtes de dérivation.',
          'Tous les tronçons > 1 MΩ (sinon : le tronçon en défaut est identifié).',
          'Trouver le tronçon précis avant d’ouvrir les faux plafonds.',
          { localize: true, onConform: 'Tous les tronçons sont sains : défaut dans un socle ou un point.' }),
       C('visuel', 'Inspecter le cheminement du câble sur le tronçon en défaut : faux plafonds, fixations, passages près d’équipements qui vibrent ou de travaux récents.',
          'Câble intact, fixé sur un support indépendant, éloigné des sources de vibration.',
          'Constater la cause physique avant de réparer.')],
      'Mise hors service de la boucle signalée à l’exploitant (mesures compensatoires, surveillance renforcée) : remplacer le tronçon de câble blessé (même type de câble, jonctions conformes au SSI), ' +
      'le reposer sur un support indépendant, à l’écart des fixations de luminaires et des gaines qui vibrent ; refaire résistance de boucle et isolement, vérifier l’absence de défaut au démarrage ' +
      'de l’équipement voisin, consigner l’intervention dans le registre de sécurité et informer l’entreprise qui a réalisé les travaux.'),
    H('Défaut logiciel de l’ECS après mise à jour', 'Une mise à jour peut modifier le traitement des défauts ; elle est souvent soupçonnée, mais seule la chronologie permet de la retenir.',
      ['+mise a jour', 'logiciel', 'firmware', 'version'],
      [C('fonctionnel', 'Comparer la date de la mise à jour avec celle des premiers défauts (historique de l’ECS) et demander à l’installateur les notes de version.',
          'Défauts apparus bien après la mise à jour, ou sans rapport avec elle : la mise à jour n’est pas en cause (conforme).',
          'Retenir ou écarter une cause soupçonnée sans preuve.')],
      'Faire reprendre la mise à jour par l’installateur ou le constructeur (version corrigée ou retour à la version précédente), puis refaire les essais fonctionnels et consigner au registre de sécurité.'),
    H('Détecteur encrassé ou défectueux', 'Des alarmes ou dérangements intempestifs qui reviennent toujours sur le même point viennent souvent d’un détecteur sale ou en fin de vie.',
      ['+detecteur', 'feu', 'alarme', '+intempesti', 'derangement', 'poussiere', 'fausse alarme', 'toujours le meme', 'ancien', 'encrass'],
      [C('fonctionnel', 'Identifier dans l’historique de l’ECS le point en alarme ou en dérangement et, sur un système adressable, relever son niveau d’encrassement.', 'Aucun point récurrent, niveau d’encrassement dans la tolérance.',
         'Savoir si c’est toujours le même détecteur.'),
       C('fonctionnel', 'Déposer le détecteur désigné : contrôler l’état de sa chambre (poussière, insectes) et le tester à l’aérosol après remise en place.', 'Chambre propre, réaction à l’essai et retour au repos après réarmement.',
         'Constater l’état du détecteur lui-même.')],
      'Remplacer le détecteur par un modèle identique ou associé au système (un détecteur optique ne se nettoie que selon les prescriptions du constructeur), refaire l’essai fonctionnel et consigner au registre de sécurité.'),
    H('Détecteur inadapté à son environnement (vapeur, cuisson, poussière)', 'Des alarmes intempestives sur un détecteur en bon état, toujours aux mêmes moments, viennent de ce qu’il « voit » : vapeur de douche ou de cuisson, poussière de travaux, fumées de procédé.',
      ['+vapeur', '+cuisine', '+douche', 'cuisson', 'toujours le meme', 'meme heure', 'poussiere', 'travaux', 'four', 'sanitaire', 'intempesti', 'fausse alarme', 'neuf', 'remplace'],
      [C('fonctionnel', 'Relever dans l’historique de l’ECS les heures des alarmes et les rapprocher de l’activité du local.', 'Aucun lien entre les alarmes et une activité (sinon : la source est identifiée).',
         'Un lien avec une activité désigne la cause.',
         { localize: true, onConform: 'Pas de lien avec une activité : contrôler le détecteur lui-même.' }),
       C('visuel', 'Inspecter l’environnement du détecteur : source de vapeur, de fumée de cuisson, de poussière ou courant d’air à proximité.', 'Aucune source de vapeur, de fumée ou de poussière près du détecteur.',
         'Constater ce qui déclenche le détecteur.')],
      'Faire valider par l’installateur et le coordinateur SSI un déplacement du détecteur ou un type mieux adapté (thermovélocimétrique, multicapteur). Jamais de mise hors service permanente d’un point : mesures compensatoires et inscription au registre de sécurité.'),
    H('Ligne de détection en défaut (coupure / court-circuit)', 'Un dérangement de zone sur une ligne conventionnelle évoque une ligne coupée, en court-circuit, un détecteur retiré de son socle ou une résistance de fin de ligne absente.',
      ['derangement', '+ligne', 'zone', 'court', 'coupure', 'defaut', 'fin de ligne', 'rfl', 'conventionnel', 'socle', 'detecteur retire'],
      [C('hors_tension', 'Ligne déconnectée de la centrale (mise hors service signalée à l’exploitant) : mesurer sa résistance avec l’élément de fin de ligne.', 'Valeur égale à l’élément de fin de ligne (ex. 4,7 kΩ) aux tolérances près.',
         'Une valeur infinie signe une coupure, une valeur très faible un court-circuit.'),
       C('visuel', 'Suivre la ligne socle par socle : détecteur absent ou mal verrouillé, borne desserrée, élément de fin de ligne.', 'Tous les détecteurs en place et verrouillés, connexions serrées, fin de ligne présente.',
         'Trouver l’endroit de la coupure ou du court-circuit.')],
      'Remettre en place ou remplacer l’élément en cause (détecteur, socle, câble, fin de ligne), remettre la zone en service, faire un essai et consigner au registre de sécurité.'),
    H('Défaut d’alimentation / batteries', 'Un défaut secteur ou batterie signalé par l’ECS ou l’alimentation électrique de sécurité vient du secteur absent, du chargeur ou de batteries en fin de vie.',
      ['+batterie', '+secteur', 'alimentation', '+aes', 'defaut alim', 'source secondaire', 'chargeur', 'autonomie'],
      [C('sous_tension', 'Mesurer la tension secteur à l’arrivée, la tension de charge et la tension de chaque batterie.', 'Secteur présent ; charge ≈ 27,3 V pour un système 24 V ; batteries équilibrées.',
         'Départager secteur, chargeur et batteries.',
         { localize: true, onConform: 'Secteur et charge corrects : vérifier la tenue des batteries secteur coupé.' }),
       C('fonctionnel', 'Relever la date des batteries et, exploitant prévenu, couper le secteur quelques minutes en mesurant la tension batteries en charge.', 'Batteries de moins de 4 ans ; tension qui se maintient secteur coupé.',
         'Des batteries usées s’écroulent dès qu’elles débitent.',
         { localize: true, onConform: 'Batteries correctes : le défaut vient du secteur ou du chargeur.' })],
      'Remplacer les batteries par paire (même type, même capacité, date notée) ou remettre en état le chargeur ou l’arrivée secteur, puis vérifier la disparition du défaut et consigner au registre de sécurité.'),
    H('Déclencheur manuel défectueux ou actionné', 'Une alarme feu maintenue, impossible à réarmer, vient souvent d’un déclencheur manuel actionné ou endommagé.',
      ['+declencheur', '+dm', 'bris de glace', 'alarme', 'ne se rearme pas', 'reste en alarme', 'boitier rouge'],
      [C('visuel', 'Identifier à l’ECS le point en alarme et contrôler l’état et la position du déclencheur manuel (membrane, réarmement à la clé).', 'Déclencheur au repos, membrane intacte.',
         'Voir si un déclencheur est resté enfoncé.')],
      'Réarmer le déclencheur à la clé ou remplacer la membrane ou le boîtier endommagé, réarmer l’ECS, faire un essai et consigner au registre de sécurité.'),
    H('Contact de position de DAS déréglé (défaut de position)', 'Un défaut de position sur un clapet, un volet ou une porte coupe-feu qui est pourtant dans la bonne position vient du contact de fin de course : déréglé, cassé, ou fil coupé.',
      ['+position', '+defaut position', 'attente', '+clapet', 'volet', '+das', 'cmsi', 'fin de course', 'desenfumage', 'discordance'],
      [C('fonctionnel', 'Exploitant prévenu : commander le DAS et comparer sa position réelle à la position signalée au CMSI.', 'Position réelle et position signalée identiques.',
         'Savoir si le DAS bouge et si l’information est juste.'),
       C('hors_tension', 'Contrôler à l’ohmmètre les contacts de début et de fin de course du DAS, leur réglage et leur câblage.', 'Contacts qui changent franchement d’état en position, câblage continu.',
         'Trouver le contact qui ne donne plus l’information.')],
      'Régler ou remplacer le contact de position, refaire son câblage, puis réaliser un essai complet du DAS depuis le CMSI et consigner au registre de sécurité.'),
    H('Porte coupe-feu : ventouse ou ferme-porte défaillant', 'Une porte coupe-feu qui ne reste plus ouverte a sa ventouse non alimentée ou hors service ; une porte qui ne se referme pas à l’ordre a son ferme-porte ou son sélecteur de fermeture en cause.',
      ['+porte coupe feu', '+ventouse', 'ne reste pas ouverte', 'ne se ferme pas', 'ferme porte', 'se referme', 'compartimentage', 'das', 'cale'],
      [C('sous_tension', 'Mesurer la tension aux bornes de la ventouse de porte, hors alarme.', 'Tension nominale de la ventouse (24 ou 48 V DC).',
         'Savoir si la ventouse est alimentée.',
         { localize: true, onConform: 'Ventouse alimentée : vérifier la fermeture de la porte.' }),
       C('fonctionnel', 'Exploitant prévenu : libérer la porte et observer sa fermeture complète (ferme-porte, sélecteur de fermeture pour deux vantaux, obstacle).', 'Fermeture complète et verrouillage sans aide.',
         'Vérifier la fonction de sécurité elle-même.',
         { localize: true, onConform: 'La porte se ferme seule : c’est le maintien en position ouverte qui est en cause.' })],
      'Remplacer la ventouse ou rétablir son alimentation ; régler ou remplacer le ferme-porte et le sélecteur. Retirer toute cale : une porte coupe-feu ne se bloque jamais. Essai depuis le CMSI et inscription au registre de sécurité.'),
    H('Défaut d’isolement de ligne (défaut terre)', 'Un défaut terre signalé par l’ECS vient d’une ligne humide ou blessée : détecteur en local humide, parking, boîte de dérivation.',
      ['+defaut terre', 'terre', 'isolement', 'humid', 'parking', 'pluie', 'infiltration', 'sous sol'],
      [C('hors_tension', 'Lignes déconnectées de la centrale une à une (mise hors service signalée à l’exploitant) : mesurer l’isolement de chaque ligne par rapport à la terre.', 'Chaque ligne > 1 MΩ.',
         'Trouver la ligne qui porte le défaut terre.'),
       C('visuel', 'Sur la ligne en défaut : inspecter les socles et boîtes exposés à l’humidité ou à des travaux.', 'Socles et boîtes secs, câble intact.',
         'Constater la cause physique.')],
      'Remplacer le socle, la boîte ou le tronçon de câble atteint (matériel adapté au local humide), refaire la mesure d’isolement, remettre en service et consigner au registre de sécurité.'),
    H('Ligne de diffuseurs sonores en défaut', 'Un dérangement sur une ligne de sirènes ou de diffuseurs vient d’une coupure, d’un court-circuit, d’un diffuseur hors service ou de l’élément de fin de ligne.',
      ['+diffuseur', '+sirene', 'evacuation', 'ne sonne pas', 'ligne ds', 'alarme sonore', 'un etage'],
      [C('hors_tension', 'Ligne de diffuseurs déconnectée (exploitant prévenu) : mesurer sa résistance avec l’élément de fin de ligne.', 'Valeur conforme à l’élément de fin de ligne.',
         'Savoir si la ligne est coupée ou en court-circuit.'),
       C('visuel', 'Contrôler les diffuseurs un par un (raccordement, polarité, état) jusqu’à la fin de ligne.', 'Diffuseurs raccordés et en état, fin de ligne présente.',
         'Trouver le diffuseur ou la connexion en cause.')],
      'Remplacer le diffuseur ou refaire la connexion en cause, remettre la ligne en service, faire un essai d’évacuation avec l’exploitant et consigner au registre de sécurité.'),
    H('Bloc autonome d’éclairage de sécurité hors service (batterie ou alimentation)', 'Un bloc de secours qui ne s’allume pas à la coupure, ou qui signale un défaut (voyant jaune ou orange), a sa batterie en fin de vie ; si son voyant de charge est éteint, il n’est plus alimenté (circuit coupé, télécommande restée au repos).',
      ['+baes', '+bloc', 'secours', 'eclairage de securite', 'ne s allume pas', 'autonomie', 'voyant jaune', 'voyant orange', 'issue', 'evacuation'],
      [C('fonctionnel', 'Couper l’alimentation du bloc (ou lancer le test) et observer son allumage et sa durée de fonctionnement.', 'Le bloc s’allume et tient sa durée assignée (1 h pour un bloc d’évacuation).',
         'Essai direct de la fonction de sécurité.'),
       C('sous_tension', 'Mesurer la présence du secteur aux bornes du bloc et l’état de son voyant de charge.', 'Secteur présent, voyant de charge vert.',
         'Départager un bloc non alimenté d’une batterie usée.',
         { localize: true, onConform: 'Bloc alimenté et en charge : c’est la batterie qui est en fin de vie.' })],
      'Si le secteur est absent aux bornes du bloc : rétablir son circuit d’alimentation (protection, connexion, télécommande) puis laisser charger 24 h. Si le bloc est alimenté : remplacer la batterie par le modèle prévu par le constructeur (ou le bloc complet), noter la date. Dans les deux cas, refaire un essai d’autonomie et consigner au registre de sécurité.'),

    DM.kbTools.emergencyExitLock(),

    H('DAS qui ne change pas de position à la commande', 'Un volet, un clapet ou un exutoire qui ne bouge pas à l’ordre a son déclencheur hors service, sa ligne de télécommande coupée, sa réserve d’énergie vide (cartouche de gaz, ressort, vérin) ou son mécanisme grippé.',
      ['+n a pas ouvert', '+ne s ouvre pas', 'ne se ferme pas', 'volet', 'exutoire', 'desenfumage', 'clapet', 'a l essai', 'essai annuel', 'das', 'ne bouge pas'],
      [C('fonctionnel', 'Exploitant prévenu : commander le DAS depuis le CMSI et mesurer l’ordre à ses bornes (tension ou coupure selon le type) au moment de la commande.', 'Ordre présent aux bornes du DAS et changement de position.',
         'Savoir si l’ordre arrive jusqu’au DAS.',
         { localize: true, onConform: 'L’ordre arrive bien : le déclencheur ou le mécanisme du DAS est en cause.' }),
       C('visuel', 'Contrôler le déclencheur du DAS (électromagnétique ou pyrotechnique), sa réserve d’énergie et la liberté du mécanisme.', 'Déclencheur fonctionnel, énergie disponible, mécanisme libre.',
         'Trouver ce qui empêche le DAS de changer de position.')],
      'Remplacer le déclencheur ou la cartouche, dégripper le mécanisme ou refaire la ligne de télécommande, puis réaliser un essai complet depuis le CMSI et l’inscrire au registre de sécurité. Signaler à l’exploitant que la fonction n’est pas assurée tant que l’essai n’est pas concluant.'),
    H('Point adressable absent (détecteur retiré, mal verrouillé, adresse)', 'Un dérangement « point absent » sur un système adressable vient d’un détecteur retiré ou mal verrouillé dans son socle, d’un socle mal raccordé ou d’une erreur d’adresse après un remplacement.',
      ['+point absent', '+absent', 'adressable', 'ne repond pas', 'manquant', 'menage', 'remplace', 'socle'],
      [C('visuel', 'Se rendre au point désigné par l’ECS : présence du détecteur, verrouillage dans son socle, raccordement du socle, adresse du détecteur.', 'Détecteur en place et verrouillé, socle raccordé, adresse conforme au plan.',
         'Le point absent se contrôle sur place.')],
      'Remettre en place et verrouiller le détecteur, refaire le raccordement du socle ou corriger l’adresse, réarmer l’ECS, tester le point et consigner au registre de sécurité.')
  ]);
})(window.DM);
