/* DIAG-MAINT — base de pannes : maintenance industrielle (mécanique, pneumatique, hydraulique, sécurité machine). */
(function (DM) {
  'use strict';
  const K = DM.kbTools, C = K.C, H = K.H;

  DM.kbRegister('industriel', [
    H('Courroie détendue ou usée', 'Un sifflement au démarrage ou en charge, une vitesse irrégulière, une odeur de caoutchouc ou de la poussière noire sous le carter signent une courroie qui patine.',
      ['+courroie', '+patin', '+siffl', 'criss', 'odeur de caoutchouc', 'vitesse irreguliere', 'au demarrage', 'poussiere noire', 'couin'],
      [C('visuel', 'Machine consignée : contrôler la tension de la courroie (flèche), son usure (flancs lustrés, fissures) et l’alignement des poulies.', 'Flèche conforme, flancs sains, poulies alignées et gorges non usées.',
         'Contrôle direct de la transmission.')],
      'Machine consignée : remplacer le jeu complet de courroies, contrôler les gorges des poulies, aligner et tendre selon les préconisations, puis recontrôler la tension après quelques heures de marche.'),
    H('Roulement ou palier usé', 'Un grondement régulier, un palier chaud et des vibrations qui augmentent avec le temps désignent un roulement en fin de vie ou mal graissé.',
      ['+roulement', '+palier', 'bruit', '+grogn', 'grond', 'chauffe', 'vibr', 'jeu', 'ronronn', 'grinc'],
      [C('fonctionnel', 'Machine en marche, depuis une position sûre : écouter chaque palier (stéthoscope) et relever sa température.', 'Bruit régulier, température comparable entre paliers semblables.',
         'Situer le palier en cause.'),
       C('visuel', 'Machine consignée : faire tourner l’arbre à la main, contrôler le jeu et l’état de la graisse.', 'Rotation libre sans point dur, sans jeu, graisse propre.',
         'Confirmer l’usure du roulement.')],
      'Machine consignée : remplacer le roulement (même référence, montage propre, sans choc), contrôler la portée et l’alignement, graisser selon le plan de lubrification.'),
    H('Défaut de lubrification', 'Un manque ou un excès de lubrifiant, ou un lubrifiant pollué, provoque échauffement, grincement et usure prématurée.',
      ['chauffe', 'grinc', 'bruit', '+graiss', '+huile', '+lubrif', 'a sec', 'niveau', 'graisseur'],
      [C('visuel', 'Contrôler les niveaux, l’aspect du lubrifiant et le fonctionnement des points et circuits de lubrification (graisseurs, centrale).', 'Niveaux corrects, lubrifiant propre, tous les points alimentés.',
         'Vérifier que le lubrifiant arrive bien là où il doit.')],
      'Rétablir la lubrification (appoint ou vidange avec le lubrifiant préconisé, graisseur ou conduite bouchée), puis contrôler la température des organes concernés.'),
    H('Pression d’air insuffisante (réseau, filtre-régulateur, fuite)', 'Des vérins lents ou sans force sur toute la machine indiquent un manque de pression en fonctionnement : filtre colmaté, régulateur déréglé, fuite importante, réseau insuffisant.',
      ['+pneumatique', 'verin', '+air', '+pression', 'lent', 'force', 'fuit', 'siffl', 'toute la machine', 'manometre', 'bar', 'chute'],
      [C('fluide', 'Relever la pression au réseau, puis à l’entrée de la machine après le filtre-régulateur, machine en cycle.', 'Pression au moins égale à la valeur requise (ex. 6 bar), sans chute pendant les mouvements.',
         'Une pression qui s’effondre en cycle se voit au manomètre.'),
       C('visuel', 'Contrôler le filtre du groupe de conditionnement (colmatage, purge), le réglage du régulateur et rechercher les fuites (écoute, produit moussant).', 'Filtre propre, régulateur réglé, aucune fuite audible.',
         'Trouver où la pression se perd.',
         { localize: true, onConform: 'Conditionnement d’air correct : le réseau ne fournit pas assez de débit à cet endroit.' })],
      'Circuit isolé et purgé : remplacer la cartouche filtrante, purger, régler le régulateur, réparer les fuites (raccords, tuyaux), puis vérifier la pression en cycle.'),
    H('Vérin : fuite interne ou joints usés', 'Un vérin lent, sans force ou qui ne tient pas sa position, alors que la pression d’alimentation est bonne, laisse passer l’air d’une chambre à l’autre.',
      ['+verin', 'lent', 'sans force', 'ne tient pas', 'descend', 'un seul', 'fuite a l echappement', 'joint'],
      [C('fonctionnel', 'Vérin en bout de course sous pression : écouter et sentir l’échappement de son distributeur.', 'Aucune fuite continue à l’échappement.',
         'Une fuite continue à l’échappement signe une fuite interne du vérin.')],
      'Circuit isolé et purgé : remplacer le vérin ou sa pochette de joints, contrôler l’état de la tige et l’alignement de la charge, puis régler les limiteurs de débit.'),
    H('Distributeur pneumatique bloqué', 'Un mouvement qui ne se fait pas alors que la bobine est commandée et que la pression est présente vient d’un tiroir de distributeur collé (air pollué, eau, huile).',
      ['+distributeur', 'tiroir', 'ne bouge pas', 'commande manuelle', 'colle', 'un seul mouvement', 'eau dans l air'],
      [C('fonctionnel', 'Zone dégagée : actionner la commande manuelle auxiliaire du distributeur.', 'Le mouvement se fait à la commande manuelle.',
         'Si le mouvement ne se fait pas même à la main, le distributeur est bloqué (ou l’air n’arrive pas).')],
      'Circuit isolé et purgé : remplacer le distributeur, traiter la qualité de l’air (purge, filtre, sécheur), puis valider les mouvements.'),
    H('Niveau d’huile hydraulique bas ou aspiration d’air', 'Une pompe hydraulique bruyante, des mouvements saccadés et une huile mousseuse indiquent que la pompe aspire de l’air : niveau bas ou prise d’air à l’aspiration.',
      ['+hydraulique', 'bruit', '+mousse', 'huile', 'niveau', 'saccad', 'groupe', 'laiteu', 'bruyant', 'a coups'],
      [C('visuel', 'Groupe à l’arrêt : contrôler le niveau et l’aspect de l’huile (mousse, couleur laiteuse) et l’étanchéité de la ligne d’aspiration.', 'Niveau entre les repères, huile limpide, aspiration étanche.',
         'Le niveau et l’aspect de l’huile renseignent immédiatement.')],
      'Circuit à l’arrêt et dépressurisé : faire l’appoint avec l’huile préconisée, reprendre l’étanchéité de l’aspiration, chercher la fuite qui a fait baisser le niveau, puis purger l’air.'),
    H('Filtre hydraulique colmaté', 'Des mouvements qui ralentissent et une huile qui chauffe, avec l’indicateur de colmatage au rouge, désignent un filtre saturé.',
      ['+hydraulique', '+colmat', 'filtre', 'lent', 'chauffe', 'indicateur', 'voyant filtre', 'ralenti'],
      [C('visuel', 'Relever l’indicateur de colmatage du filtre, huile à température de service.', 'Indicateur dans la zone normale.',
         'L’indicateur de colmatage est fait pour ça.')],
      'Circuit à l’arrêt et dépressurisé : remplacer l’élément filtrant, contrôler l’état de l’huile (analyse ou vidange si polluée) et la périodicité de remplacement.'),
    H('Pression hydraulique insuffisante (limiteur déréglé, pompe usée)', 'Un manque de force alors que les mouvements se font indique une pression qui ne monte pas : limiteur de pression déréglé ou ouvert, pompe usée, fuite interne.',
      ['+hydraulique', '+pression', '+manque de force', 'ne monte pas', 'presse', 'tonnage', 'ne serre pas', 'force'],
      [C('fluide', 'Relever la pression au manomètre en butée de mouvement et la comparer au schéma hydraulique.', 'Pression égale au tarage du limiteur indiqué sur le schéma.',
         'Savoir si la pression de service est atteinte.'),
       C('fluide', 'Contrôler le tarage du limiteur de pression et, en butée, le débit de retour au réservoir (drain de la pompe, retour du limiteur).', 'Limiteur taré à la valeur du schéma, pas de débit de fuite anormal.',
         'Départager limiteur, pompe et fuite interne.',
         { localize: true, onConform: 'Limiteur et pompe corrects : chercher une fuite interne (vérin, distributeur).' })],
      'Régler ou remplacer le limiteur de pression selon le schéma ; si la pompe est usée (débit de drain élevé), la remplacer et contrôler la propreté de l’huile. Ne jamais dépasser le tarage prévu.'),
    H('Fuite hydraulique externe (flexible, raccord, joint)', 'Une flaque d’huile, un niveau qui baisse ou un organe qui suinte désignent une fuite externe à localiser avant qu’un flexible ne cède.',
      ['+fuite d huile', '+huile gicle', 'gicle', 'pisse', 'huile', 'flaque', '+flexible', 'raccord', 'suint', 'niveau baisse', 'huile au sol', 'hydraulique'],
      [C('visuel', 'Circuit à l’arrêt et dépressurisé : nettoyer la zone, puis inspecter flexibles (craquelures, hernies, frottements), raccords et joints.', 'Flexibles sains, raccords secs.',
         'Localiser la fuite, jamais à la main sur un circuit sous pression.')],
      'Circuit à l’arrêt et dépressurisé : remplacer le flexible ou le joint (même pression de service, même longueur, sans torsion), refaire le niveau, puis contrôler sous pression à distance.'),
    H('Dispositif de sécurité machine actif', 'Une sécurité ouverte ou mal vue (porte, carter, barrière immatérielle) empêche le démarrage ou arrête la machine en cycle.',
      ['+securite', 'capteur', '+carter', 'porte', '+barriere', 'ne demarre', 'bloqu', 'immaterielle', 'relais de securite', 'defaut securite'],
      [C('fonctionnel', 'Relever l’état du module de sécurité et de chaque protecteur : quel canal est ouvert.', 'Tous les canaux fermés, module réarmé.',
         'Savoir quelle sécurité est vue ouverte.',
         { localize: true, onConform: 'Module réarmé, canaux fermés : la sécurité n’est pas en cause.' }),
       C('visuel', 'Machine consignée : contrôler le protecteur désigné (interrupteur de porte et sa clé, alignement et propreté de la barrière immatérielle, fixation).', 'Interrupteur actionné franchement, barrière alignée et propre.',
         'Trouver pourquoi la sécurité est vue ouverte.')],
      'Machine consignée : régler ou remplacer l’interrupteur ou la barrière (matériel de sécurité équivalent), vérifier les deux canaux et faire un essai de chaque protecteur. Ne jamais shunter un dispositif de sécurité.'),
    H('Compresseur d’air qui ne monte plus en pression', 'Un compresseur qui tourne longtemps sans atteindre sa pression d’arrêt perd son air : clapets fatigués, filtre d’aspiration colmaté, électrovanne de mise à vide qui fuit, courroie qui patine.',
      ['compresseur', '+tourne en continu', '+ne monte pas', 'plafonne', 'ne coupe pas', 'pression', 'cuve', 'longtemps', 'ne s arrete plus'],
      [C('fluide', 'Vanne de sortie de cuve fermée : chronométrer la montée en pression de la cuve et la comparer au temps habituel.', 'Montée en pression dans le temps habituel jusqu’à la pression d’arrêt.',
         'Séparer le compresseur du réseau : s’il monte bien cuve isolée, la fuite est sur le réseau.'),
       C('visuel', 'Compresseur consigné et cuve purgée : contrôler le filtre d’aspiration, les clapets, l’électrovanne de mise à vide et la courroie.', 'Filtre propre, clapets étanches, mise à vide fermée en charge, courroie tendue.',
         'Trouver l’organe qui laisse fuir ou qui limite le débit.',
         { localize: true, onConform: 'Organes visibles corrects : usure interne (segments, cylindre) à faire contrôler.' })],
      'Consigné et hors pression : remplacer filtre, clapets ou électrovanne de mise à vide, retendre ou remplacer la courroie, puis vérifier le temps de montée en pression.'),
    H('Réducteur : manque d’huile ou usure', 'Un réducteur bruyant et chaud, avec une fuite au joint d’arbre ou de la limaille au bouchon, manque d’huile ou s’use.',
      ['+reducteur', 'bruit', 'chauffe', 'fuit', 'huile', 'jeu', 'limaille', 'craqu', 'motoreducteur'],
      [C('visuel', 'Machine consignée : contrôler le niveau et l’aspect de l’huile du réducteur (limaille au bouchon magnétique) et l’étanchéité des joints d’arbre.', 'Niveau correct, huile propre, pas de limaille, joints secs.',
         'L’huile raconte l’état du réducteur.')],
      'Machine consignée : remplacer les joints, vidanger et remplir avec l’huile préconisée ; en présence de limaille, prévoir le remplacement ou la révision du réducteur.'),
    H('Bande de convoyeur déportée', 'Une bande qui se déporte et frotte sur le châssis vient d’un tambour ou de rouleaux encrassés, d’un défaut d’équerrage ou d’une tension inégale.',
      ['+bande', '+deport', '+devie', 'frott', 'bord', 'convoyeur', 'tambour', 'rouleau', 'centrage', 's use sur le cote'],
      [C('visuel', 'Convoyeur consigné : contrôler la propreté des tambours et rouleaux, leur équerrage, la tension de la bande et l’état de la jonction.', 'Tambours propres et d’équerre, tension égale des deux côtés, jonction droite.',
         'Trouver ce qui pousse la bande d’un côté.')],
      'Convoyeur consigné : nettoyer tambours et rouleaux, reprendre l’équerrage et la tension, refaire la jonction si elle n’est pas droite, puis régler le centrage par petites corrections, bande en marche et protecteurs en place.'),
    H('Chaîne de transmission détendue ou usée', 'Une chaîne qui claque, saute des dents ou bat signe un allongement ou des pignons usés.',
      ['+chaine', 'saute', 'claqu', '+pignon', 'allonge', 'bat', 'dents'],
      [C('visuel', 'Machine consignée : contrôler la flèche de la chaîne, son allongement et l’usure des dents des pignons.', 'Flèche conforme, allongement inférieur à 2 à 3 %, dents non crochues.',
         'Mesurer l’usure plutôt que retendre encore.')],
      'Machine consignée : remplacer ensemble la chaîne et les pignons usés, aligner, tendre et lubrifier.'),
    H('Usure ou défaut mécanique', 'Bruits, jeux et vibrations orientent vers une pièce mécanique usée ou desserrée.',
      ['bruit', 'vibr', 'jeu', 'claqu', 'grinc', 'usure', 'casse', 'desserre', 'cogn'],
      [C('visuel', 'Machine consignée : contrôler jeux, fixations, accouplements et guidages de l’organe bruyant.', 'Aucun jeu anormal, fixations serrées, éléments en bon état.',
         'Trouver la pièce qui a pris du jeu.')],
      'Machine consignée : remplacer la pièce usée, resserrer au couple, puis contrôler bruit et vibrations à la remise en marche.'),

    H('Vérin hydraulique qui dérive (clapet de maintien, distributeur, joints)', 'Un vérin qui descend ou recule seul quand la commande est relâchée perd son huile par un clapet anti-retour piloté qui fuit, par le distributeur, ou par ses joints de piston.',
      ['+redescend', '+derive', '+tout seul', 'ne tient pas', 'descend', 'verin', 'hydraulique', 'presse', 'recule', 'lache la commande'],
      [C('fonctionnel', 'Charge appuyée, zone dégagée : relâcher la commande et mesurer la dérive du vérin ; refaire l’essai vérin isolé à sa vanne d’isolement.', 'Aucune dérive, vérin isolé ou non.',
         'S’il tient une fois isolé, la fuite est dans le clapet de maintien ou le distributeur ; s’il dérive encore, ce sont ses joints de piston.')],
      'Circuit à l’arrêt, dépressurisé, charge calée : remplacer le clapet anti-retour piloté ou le distributeur qui fuit (ou la pochette de joints du vérin s’il dérive isolé), contrôler la propreté de l’huile, puis vérifier la tenue en position sous charge.'),
    H('Compresseur d’air qui démarre en charge (mise à vide, clapet anti-retour)', 'Un compresseur qui peine ou disjoncte au démarrage, surtout à froid ou cuve déjà sous pression, redémarre contre la pression : l’électrovanne de mise à vide ne décharge pas la tête, ou le clapet anti-retour de cuve fuit.',
      ['compresseur', '+au demarrage', 'disjonct', 'peine', 'froid', 'le matin', 'cuve pleine', 'cale'],
      [C('fonctionnel', 'À l’arrêt du compresseur, écouter la décharge d’air à la tête ; au redémarrage cuve sous pression, observer s’il démarre librement.', 'Décharge nette à l’arrêt, démarrage libre même cuve sous pression.',
         'Savoir si le compresseur démarre contre la pression.'),
       C('visuel', 'Compresseur consigné, cuve purgée : contrôler l’électrovanne ou le clapet de décharge de la tête, le clapet anti-retour de cuve et la viscosité de l’huile.', 'Décharge fonctionnelle, clapet anti-retour étanche, huile adaptée à la température.',
         'Trouver l’organe qui laisse la tête en pression.',
         { localize: true, onConform: 'Organes de décharge corrects : vérifier la tension au démarrage et le réglage de la protection.' })],
      'Consigné et hors pression : remplacer l’électrovanne de mise à vide ou le clapet anti-retour, utiliser une huile adaptée aux basses températures, puis vérifier plusieurs démarrages cuve sous pression.',
      { diff: false }),

    H('Compresseur d’air en surchauffe (refroidisseur, huile, ambiance)', 'Un compresseur qui s’arrête en température haute, plutôt par temps chaud, refroidit mal : radiateur d’huile ou d’air colmaté, niveau d’huile bas, ventilateur à l’arrêt, local mal ventilé.',
      ['compresseur', '+temperature haute', '+surchauffe', 'temperature', 'chaud', 'apres midi', 'ete', 'a vis'],
      [C('visuel', 'Compresseur consigné : contrôler la propreté du refroidisseur (radiateur d’huile et d’air), le niveau d’huile, le ventilateur de refroidissement et la ventilation du local.', 'Refroidisseur propre, niveau d’huile correct, ventilateur en état, local ventilé.',
         'Trouver pourquoi la chaleur ne s’évacue pas.')],
      'Consigné : nettoyer le refroidisseur, refaire le niveau avec l’huile préconisée, remettre en état le ventilateur, améliorer l’arrivée d’air frais du local ; contrôler ensuite la température de refoulement.'),
    H('Vérin pneumatique : amortissement de fin de course déréglé ou usé', 'Un vérin qui tape en fin de course a perdu son amortissement : vis d’amortissement déréglée, joint d’amortisseur usé, ou vitesse trop élevée (limiteur de débit déréglé).',
      ['+tape', '+cogn', 'fin de course', 'choc', 'verin', 'violent', 'trop vite', 'vibr'],
      [C('visuel', 'Zone dégagée : observer la fin de course du vérin, contrôler le réglage des vis d’amortissement et des limiteurs de débit.', 'Ralentissement net sur les derniers millimètres, limiteurs réglés.',
         'Voir si le vérin est freiné avant sa butée.')],
      'Régler les limiteurs de débit à l’échappement et les vis d’amortissement ; si le réglage est sans effet, remplacer les joints d’amortissement ou le vérin, ou ajouter un amortisseur externe.',
      { requis: ['verin'] }),
    H('Huile hydraulique trop froide ou trop chaude (réchauffeur, refroidisseur)', 'Une installation lente à froid et qui s’améliore en chauffant a une huile trop visqueuse (réchauffeur hors service, huile inadaptée) ; l’inverse, lente et bruyante à chaud, signale un refroidisseur inefficace.',
      ['+a froid', '+le matin', 'hydraulique', 'lente', 'lent', 'apres une heure', 'viscosite', 'rechauffeur', 'refroidisseur', 'mieux apres', 'hiver'],
      [C('fluide', 'Relever la température de l’huile au réservoir au démarrage puis en service, et contrôler le réchauffeur et le refroidisseur.', 'Température d’huile dans la plage de service (souvent 30 à 60 °C), réchauffeur et refroidisseur fonctionnels.',
         'La viscosité de l’huile dépend directement de sa température.')],
      'Remettre en état le réchauffeur ou le refroidisseur et son thermostat, utiliser une huile de la viscosité préconisée pour la température d’utilisation, et laisser monter en température avant de charger.',
      { requis: ['hydraulique', 'presse', 'huile'] }),

    H('Compresseur d’air : pressostat qui ne coupe plus', 'Un compresseur qui dépasse sa pression d’arrêt jusqu’à faire cracher la soupape de sécurité a son pressostat hors service : contacts collés, prise de pression bouchée, réglage modifié.',
      ['compresseur', '+soupape', '+crache', 'ne s arrete pas', 'ne coupe pas', 'depasse', 'pression trop haute', 'pressostat'],
      [C('fluide', 'Relever au manomètre la pression à laquelle le compresseur s’arrête et la comparer au réglage du pressostat et au tarage de la soupape.', 'Arrêt à la pression réglée, nettement sous le tarage de la soupape.',
         'Voir si le pressostat coupe bien à sa consigne.'),
       C('hors_tension', 'Compresseur consigné, cuve purgée : contrôler les contacts du pressostat et sa prise de pression.', 'Contacts qui s’ouvrent franchement, prise de pression libre.',
         'Trouver pourquoi le pressostat ne coupe plus.')],
      'Consigné et hors pression : remplacer le pressostat (ou déboucher sa prise de pression), régler les seuils, vérifier la soupape de sécurité sans jamais la brider, puis contrôler plusieurs cycles.',
      { requis: ['compresseur'] }),
    H('Pompe à vide usée ou huile dégradée', 'Une pompe à vide qui tourne sans atteindre son niveau de vide a ses palettes usées, son huile polluée, son filtre d’aspiration colmaté, ou une fuite sur le circuit de vide.',
      ['+pompe a vide', '+vide', 'ne descend plus', 'thermoformeuse', 'ventouse de prehension', 'aspiration'],
      [C('fluide', 'Pompe isolée du circuit (aspiration obturée) : relever le vide limite au vacuomètre et le comparer à la notice.', 'Vide limite conforme à la notice.',
         'Si la pompe seule atteint son vide, la fuite est sur le circuit.',
         { localize: true, onConform: 'Pompe bonne : chercher une fuite sur le circuit de vide (flexibles, ventouses, joints).' }),
       C('visuel', 'Pompe consignée : contrôler le niveau et l’aspect de l’huile, le filtre d’aspiration et l’usure des palettes.', 'Huile claire au niveau, filtre propre, palettes dans leur cote.',
         'Trouver ce qui limite le vide.')],
      'Consigné : vidanger, remplacer filtres et palettes selon la notice, reprendre l’étanchéité du circuit de vide, puis contrôler le vide limite.',
      { requis: ['vide'] })
  ]);
})(window.DM);
