/* DIAG-MAINT — base de pannes : moteurs électriques et variateurs. */
(function (DM) {
  'use strict';
  const K = DM.kbTools, C = K.C, H = K.H, PHASE_CURRENTS = K.PHASE_CURRENTS, DRIVE_CODE = K.DRIVE_CODE;

  const ASSEMBLY_INSULATION = C('hors_tension',
    'Départ consigné, depuis l’armoire : mesurer l’isolement de l’ensemble câble + moteur par rapport à la terre (mégohmmètre 500 V DC).',
    'Isolement > 1 MΩ.',
    'Savoir en une mesure si le défaut est en aval de l’armoire.');

  DM.kbRegister('moteur', [
    K.contactDegrade(),
    K.thermalSetting(),
    H('Échauffement de l’armoire (température ambiante)', 'Le relais thermique est sensible à la température de l’armoire : par forte chaleur il déclenche plus tôt, surtout si le moteur est déjà proche de sa limite.',
      ['apres midi', 'chaleur', 'ete', 'temperature', 'atelier', 'ventilation'],
      [C('fluide', 'Mesurer la température intérieure de l’armoire l’après-midi et contrôler sa ventilation (filtres, ventilateur).', 'Température compatible avec la notice du relais (souvent ≤ 40 °C), ventilation fonctionnelle.',
        'Vérifier si la chaleur aggrave un défaut existant.')],
      'Rétablir la ventilation de l’armoire (filtres, ventilateur, grilles dégagées) ; si la température reste trop élevée, prévoir une ventilation forcée ou un relais compensé en température.',
      { diff: false }),
    H('Défaut d’alimentation (perte de phase)', 'Une phase manquante fait bourdonner le moteur sans démarrer, ou le fait tourner sans force en chauffant : fusible fondu, pôle de sectionneur ou de contacteur, borne desserrée.',
      ['ne demarre', '+bourdonn', '+ronfl', '+grogn', 'chauffe', '+phase', 'lent', 'disjonct', 'fusible', 'sans force', 'ne tourne pas', 'deux phases'],
      [C('sous_tension', 'Mesurer les trois tensions entre phases en aval du départ moteur (bornes de sortie du contacteur ou du relais thermique), à l’ordre de marche.', 'Trois tensions présentes et équilibrées (écart < 2 %).',
         'Une phase absente ou faible se voit immédiatement.'),
       C('hors_tension', 'Départ consigné : contrôler la continuité de chaque phase de l’amont vers l’aval (fusibles, pôles du sectionneur et du contacteur, bornes, câble jusqu’au moteur).', 'Continuité franche sur les trois phases.',
         'Trouver l’endroit précis de la coupure.')],
      'Consigné : remplacer l’élément ouvert (fusible de même calibre et de type aM pour un moteur, pôle, borne), resserrer au couple, chercher la raison de la fusion, puis contrôler les trois tensions et les trois courants en charge.',
      { diff: false }),
    H('Défaut d’isolement du bobinage', 'Un bobinage humide ou dégradé laisse fuir du courant vers la masse : le différentiel déclenche, souvent après un lavage, une pluie ou une longue période d’arrêt.',
      ['disjonct', '+differentiel', 'humid', 'odeur', 'brul', 'declench', 'eau', 'lavage', 'nettoyage', 'pluie', 'arret prolonge', 'karcher'],
      [ASSEMBLY_INSULATION,
       C('hors_tension', 'Moteur déconnecté à sa boîte à bornes (câble débranché, barrettes retirées) : mesurer l’isolement des enroulements par rapport à la masse (mégohmmètre 500 V DC).', '> 1 MΩ (> 100 MΩ pour un moteur sain).',
         'Séparer le moteur de son câble : c’est le moteur seul qui est mesuré.')],
      'Moteur consigné : étuver ou faire rebobiner le moteur (ou le remplacer), traiter l’entrée d’eau (presse-étoupe, joint de boîte à bornes, orientation), puis refaire la mesure d’isolement avant remise sous tension.',
      { diff: true }),
    H('Défaut d’isolement du câble d’alimentation du moteur', 'Si l’ensemble câble + moteur est en défaut mais que le moteur seul est sain, c’est la liaison qui est atteinte : câble blessé, boîte de jonction ou presse-étoupe humide.',
      ['disjonct', '+differentiel', 'humid', 'cable', 'chemin de cable', 'ecrase', 'rongeur', 'eau', 'pluie', 'exterieur'],
      [ASSEMBLY_INSULATION,
       C('hors_tension', 'Câble débranché aux deux extrémités : mesurer l’isolement de chaque conducteur par rapport à la terre et entre conducteurs.', 'Chaque conducteur > 1 MΩ.',
         'Mesurer le câble seul.')],
      'Consigné : remplacer le câble ou refaire la jonction atteinte (boîte et presse-étoupes adaptés à l’environnement), puis refaire la mesure d’isolement de l’ensemble.',
      { diff: true }),
    H('Enroulement coupé ou en court-circuit entre spires', 'Un enroulement défectueux crée un déséquilibre de courant, un échauffement, une odeur de vernis chaud et des déclenchements thermiques ; le déséquilibre suit le moteur, pas l’armoire.',
      ['chauffe', 'bourdonn', 'ne demarre', 'thermique', 'declench', '+odeur', 'vernis', 'desequilibr', 'fume', 'brul'],
      [C('hors_tension', 'Moteur déconnecté : mesurer la résistance de chaque enroulement (U1-U2, V1-V2, W1-W2).', 'Valeurs identiques à ±5 %.',
         'Un enroulement en court-circuit entre spires ou coupé se voit à sa résistance.')],
      'Remplacer le moteur ou le faire rebobiner ; chercher ce qui l’a détruit (surcharge, marche sur deux phases, ventilation, démarrages trop fréquents) et vérifier le réglage de la protection avant remise en service.',
      { diff: false }),
    H('Roulements usés', 'Bruit, vibration et échauffement côté paliers sont typiques d’une usure de roulements.',
      ['+bruit', 'vibr', 'chauffe', '+grinc', '+siffl', 'claqu', '+roulement', 'grogn', 'palier', 'ronronn'],
      [C('fonctionnel', 'Moteur en marche : écouter chaque palier (stéthoscope ou tournevis) et relever sa température.', 'Bruit régulier et doux, température des paliers comparable des deux côtés.',
         'Situer le palier en cause sans rien démonter.'),
       C('visuel', 'Moteur consigné et désaccouplé : tourner l’arbre à la main, contrôler le jeu radial et axial.', 'Rotation libre, sans point dur, sans jeu ni bruit.',
         'Confirmer l’usure du roulement.')],
      'Moteur consigné : remplacer les deux roulements (même type, même jeu, montage à chaud ou à la presse, sans frapper), contrôler les portées, puis vérifier l’alignement de l’accouplement ou la tension de la courroie, causes fréquentes d’usure prématurée.',
      { diff: false }),
    H('Surcharge mécanique', 'Une charge entraînée trop importante ou grippée (bande trop tendue, roulement, réducteur, produit qui bourre) fait monter le courant sur les trois phases à la fois et déclencher le relais thermique.',
      ['thermique', 'declench', 's arrete', 'chauffe', '+force', 'lent', 'bloqu', 'bande', 'retendu', 'roulement', 'reducteur', 'bourrage', '+charge', 'dur'],
      [PHASE_CURRENTS,
       C('visuel', 'Machine consignée : tourner l’arbre à la main, contrôler roulements, tension de bande et réducteur.', 'Rotation libre, sans point dur.',
         'Rechercher une résistance mécanique anormale.')],
      'Machine consignée : supprimer la cause mécanique (organe grippé, tension excessive, bourrage), puis vérifier que les trois courants repassent sous l’intensité nominale. Ne pas relever le réglage du relais thermique.',
      { diff: false }),
    H('Couplage incorrect', 'Après un remplacement, un mauvais couplage étoile/triangle donne un moteur sans couple (étoile à tort) ou qui surchauffe et consomme trop (triangle à tort).',
      ['+apres remplacement', '+neuf', '+couplage', 'lent', 'remplace', 'chauffe', 'barrettes', 'plaque', 'sans couple', 'depuis le remplacement'],
      [C('hors_tension', 'Moteur consigné : relever la position des barrettes de la boîte à bornes et la comparer aux tensions de la plaque et à la tension du réseau.', 'Couplage conforme à la plaque pour la tension du réseau (ex. plaque 230/400 V sur réseau 400 V : étoile).',
         'Un contrôle visuel suffit à trancher.')],
      'Moteur consigné : remettre les barrettes dans le couplage correspondant à la tension du réseau, puis contrôler le courant sur les trois phases et le sens de rotation.',
      { diff: false }),
    H('Sens de rotation inversé', 'Après une intervention sur l’alimentation, deux phases croisées inversent le sens : ventilateur ou pompe sans débit, machine qui tourne à l’envers.',
      ['+sens', '+envers', 'inverse', 'apres intervention', 'apres remplacement', '+depuis le changement', 'depuis le remplacement', 'debit faible', 'ne souffle pas', 'aspire plus', 'n aspire', 'tourne pourtant', 'rotation'],
      [C('fonctionnel', 'Machine dégagée : donner une brève impulsion de marche et observer le sens de rotation par rapport à la flèche.', 'Rotation dans le sens de la flèche.',
         'Vérification immédiate et sans démontage.')],
      'Consigné : croiser deux phases au départ moteur (pas dans le tableau général), puis vérifier le sens et le courant absorbé.'),
    H('Ventilation du moteur insuffisante', 'Un moteur qui chauffe avec un courant normal est souvent mal refroidi : capot ou ailettes colmatés, ventilateur cassé, ou marche prolongée à basse vitesse sur variateur.',
      ['+chauffe', '+brulant', '+capot', 'ailette', 'poussiere', 'encrass', 'basse vitesse', 'courant normal', 'sonde ptc', 'thermistance'],
      [C('visuel', 'Moteur consigné : contrôler le capot de ventilation, le ventilateur en bout d’arbre et la propreté des ailettes.', 'Capot dégagé, ventilateur entier et bien calé, ailettes propres.',
         'Constater l’état du refroidissement.')],
      'Moteur consigné : nettoyer ailettes et capot, remplacer le ventilateur cassé ; pour une marche prolongée à basse vitesse sur variateur, prévoir une ventilation forcée indépendante.',
      { diff: false }),
    H('Désalignement ou accouplement usé', 'Des vibrations et des roulements qui lâchent à répétition viennent souvent d’un défaut d’alignement entre le moteur et la machine entraînée, ou d’un accouplement usé.',
      ['+vibr', '+accouplement', '+alignement', 'roulement remplace', 'a repetition', 'recurrent', 'encore', 'elastomere', 'apres remplacement'],
      [C('visuel', 'Machine consignée : contrôler l’alignement moteur / machine (règle et jeu de cales, comparateur ou laser) et l’état de l’élément élastique de l’accouplement.', 'Écart d’alignement dans la tolérance du constructeur, accouplement en bon état.',
         'Mesurer le défaut d’alignement plutôt que de remplacer encore les roulements.')],
      'Machine consignée : réaligner (calage des pattes, tolérances du constructeur), remplacer l’élément d’accouplement usé, resserrer les fixations au couple et contrôler les vibrations à la remise en service.',
      { diff: false }),
    H('Condensateur de moteur monophasé défaillant', 'Un moteur monophasé qui bourdonne sans partir, ou qui ne part que si on le lance à la main, a très souvent son condensateur hors tolérance.',
      ['+monophase', '+condensateur', 'bourdonn', 'ne demarre', 'lance a la main', 'ronfl', '230'],
      [C('hors_tension', 'Moteur consigné : décharger le condensateur puis mesurer sa capacité (capacimètre).', 'Capacité dans la tolérance (±5 à 10 % de la valeur marquée).',
         'Le condensateur se contrôle en une mesure.')],
      'Consigné : remplacer le condensateur par un modèle de même capacité et de tension au moins égale, puis vérifier le démarrage et l’intensité absorbée.',
      { diff: false }),
    H('Frein électromagnétique qui ne se desserre pas', 'Sur un moteur-frein, un frein qui reste serré fait forcer le moteur : il chauffe, sent le chaud et déclenche. Le frein se desserre quand sa bobine est alimentée.',
      ['+frein', 'moteur frein', 'bloqu', 'chauffe', 'odeur', 'force', 'garniture', 'ne se desserre'],
      [C('sous_tension', 'À l’ordre de marche, mesurer la tension aux bornes de la bobine du frein (en sortie du redresseur).', 'Tension continue nominale de la bobine présente.',
         'Savoir si le frein est commandé.',
         { localize: true, onConform: 'Frein commandé : contrôler sa bobine et son entrefer.' }),
       C('hors_tension', 'Moteur consigné : mesurer la résistance de la bobine du frein et contrôler l’entrefer.', 'Résistance conforme à la plaque, entrefer dans la tolérance.',
         'Départager redresseur, bobine et réglage mécanique.',
         { localize: true, onConform: 'Bobine et entrefer corrects : c’est la commande du frein (redresseur, contact) qui est en cause.' })],
      'Consigné : remplacer le redresseur ou la bobine défaillante, régler l’entrefer selon la notice, puis vérifier le desserrage franc et la tenue à l’arrêt.',
      { diff: false }),

    /* ----- variateurs ----- */
    H('Variateur : surchauffe (ventilation, encrassement)', 'Un défaut de température du variateur, plutôt par forte chaleur ou après un long fonctionnement, vient de son refroidissement : ventilateur arrêté, radiateur ou filtres colmatés, armoire trop chaude.',
      ['+variateur', '+surchauffe', 'temperature', 'chaud', 'ete', 'apres midi', 'ventilateur', 'filtre', 'poussiere', 'chaleur'],
      [DRIVE_CODE,
       C('visuel', 'Variateur consigné (bus continu déchargé) : contrôler son ventilateur, la propreté du radiateur et des filtres d’armoire, et la température dans l’armoire.', 'Ventilateur fonctionnel, radiateur et filtres propres, température d’armoire dans la limite de la notice.',
         'Constater l’état du refroidissement.')],
      'Consigné : nettoyer le radiateur et les filtres, remplacer le ventilateur du variateur, dégager les distances de ventilation ; revoir la ventilation de l’armoire si sa température reste trop élevée.'),
    H('Variateur : surintensité à l’accélération', 'Un défaut de surintensité au démarrage vient d’une rampe d’accélération trop courte pour la charge, d’une charge bloquée, ou d’un défaut du câble ou du moteur.',
      ['+variateur', '+surintensite', 'acceleration', 'rampe', 'au demarrage', 'demarre puis', 'charge', 'bloqu'],
      [DRIVE_CODE,
       C('fonctionnel', 'Relever la rampe d’accélération paramétrée, puis faire un essai moteur désaccouplé de sa charge.', 'Rampe adaptée à l’inertie de la charge ; à vide, démarrage sans défaut.',
         'Départager le réglage ou la charge d’un défaut du moteur ou du câble.')],
      'Allonger la rampe d’accélération ou libérer la charge bloquée ; si le défaut persiste moteur désaccouplé, contrôler l’isolement et les enroulements du moteur et du câble, variateur consigné et câble débranché du variateur.'),
    H('Variateur : surtension du bus à la décélération', 'Un défaut de surtension qui apparaît à l’arrêt ou au ralentissement vient de l’énergie renvoyée par une charge à forte inertie : rampe de décélération trop courte ou freinage insuffisant.',
      ['+variateur', '+surtension', 'deceleration', 'freinage', 'a l arret', 'ralentissement', 'inertie', 'ventilateur', 'centrifugeuse'],
      [DRIVE_CODE,
       C('fonctionnel', 'Relever la rampe de décélération paramétrée et l’état de la résistance de freinage si elle existe.', 'Rampe adaptée à l’inertie, résistance de freinage raccordée et de valeur conforme.',
         'Vérifier que le variateur peut absorber l’énergie de freinage.')],
      'Allonger la rampe de décélération (ou choisir l’arrêt en roue libre si le procédé l’accepte) ; sinon, ajouter ou remplacer la résistance de freinage selon la notice.'),

    H('Variateur : défaut de terre en sortie (câble ou moteur)', 'Un défaut de terre signalé par le variateur au démarrage vient d’un défaut d’isolement en aval : câble moteur blessé ou humide, boîte à bornes, ou bobinage.',
      ['+variateur', '+defaut de terre', '+defaut terre', 'terre', 'isolement', 'ne demarre plus', 'cable'],
      [DRIVE_CODE,
       C('hors_tension', 'Variateur consigné (bus continu déchargé), câble moteur débranché du variateur : mesurer l’isolement de l’ensemble câble + moteur par rapport à la terre. Ne jamais mesurer au mégohmmètre variateur raccordé.', 'Isolement > 1 MΩ.',
         'Savoir si le défaut est en aval du variateur.'),
       C('hors_tension', 'Moteur débranché à sa boîte à bornes : mesurer séparément l’isolement du câble et celui du moteur.', 'Câble et moteur > 1 MΩ chacun.',
         'Départager le câble du moteur.')],
      'Consigné : remplacer le câble moteur blessé (câble blindé adapté aux variateurs) ou remettre en état le moteur, refaire les presse-étoupes, puis contrôler l’isolement avant de rebrancher le variateur.'),
    H('Variateur : sous-tension ou perte de phase du réseau', 'Un défaut de sous-tension ou de perte de phase à l’entrée du variateur vient de son alimentation : fusible fondu, contacteur de ligne, creux de tension du réseau.',
      ['+variateur', '+defaut sous tension', '+sous tension du bus', '+perte de phase', 'tension basse', 'reseau', 'microcoupure', 'orage', 'fusible', 'creux de tension'],
      [DRIVE_CODE,
       C('sous_tension', 'Mesurer les trois tensions entre phases à l’entrée du variateur, en charge.', 'Trois tensions présentes, équilibrées (écart < 2 %) et dans la plage du variateur.',
         'Vérifier ce que reçoit réellement le variateur.')],
      'Consigné : remplacer le fusible ou l’organe de ligne défaillant, resserrer les connexions d’entrée ; si le réseau présente des creux, prévoir le redémarrage automatique ou une inductance de ligne selon la notice.')
  ]);
})(window.DM);
