/* DIAG-MAINT — base de pannes : pompes, surpresseurs, relevage, circulateurs. */
(function (DM) {
  'use strict';
  const K = DM.kbTools, C = K.C, H = K.H;

  DM.kbRegister('pompe', [
    H('Désamorçage / prise d’air à l’aspiration', 'Une entrée d’air ou un niveau trop bas fait chuter le débit : la pompe tourne mais ne refoule plus, ou par à-coups.',
      ['+pas de debit', 'debit faible', '+desamorc', 'prise d air', 'entree d air', 'bruit', 'aspiration', 'tourne mais', 'ne refoule', 'a coups', 'bulles', 'clapet de pied', 'puits'],
      [C('visuel', 'Contrôler le niveau du liquide à l’aspiration, l’immersion de la crépine et le clapet de pied.', 'Niveau suffisant, crépine immergée, clapet de pied étanche (la colonne d’aspiration reste pleine).',
         'Vérifier d’abord que la pompe peut rester amorcée.',
         { localize: true, onConform: 'Niveau et clapet de pied corrects : chercher une entrée d’air sur la conduite d’aspiration.' }),
       C('fluide', 'Pompe remplie et purgée : contrôler l’étanchéité de la conduite d’aspiration (raccords, joints, presse-étoupe) au vacuomètre ou à l’observation des entrées d’air.', 'Dépression stable à l’aspiration, aucune entrée d’air.',
         'Localiser la prise d’air.',
         { localize: true, onConform: 'Conduite étanche : le désamorçage vient du clapet de pied ou du niveau.' })],
      'Pompe consignée : refaire l’étanchéité de l’aspiration (joints, raccords, clapet de pied), remplir et purger le corps de pompe, puis vérifier que l’amorçage tient après un arrêt prolongé.'),
    H('Crépine ou filtre colmaté', 'Un colmatage à l’aspiration limite le débit et fait caviter la pompe : bruit de gravier, vibration, débit en baisse progressive.',
      ['debit', 'faible', 'pression basse', '+colmat', 'bouche', '+crepine', 'filtre', 'progressi', 'gravier', 'cavitation', 'feuilles', 'boue'],
      [C('fluide', 'Mesurer la dépression à l’aspiration, pompe en marche (vacuomètre).', 'Dépression faible et stable, conforme à la hauteur d’aspiration.',
         'Une dépression élevée signe un obstacle à l’aspiration.'),
       C('visuel', 'Pompe consignée et isolée hydrauliquement : déposer et inspecter la crépine et le filtre d’aspiration.', 'Crépine et filtre propres.',
         'Constater le colmatage.')],
      'Pompe consignée et isolée : nettoyer ou remplacer la crépine et le filtre, puis relever la dépression et le débit ; prévoir un nettoyage périodique si le colmatage est récurrent.'),
    H('Cavitation', 'Un bruit de « gravier » et des vibrations indiquent une pression d’aspiration insuffisante par rapport à ce que la pompe exige.',
      ['bruit', '+gravier', 'vibr', '+cavitation', 'crepit', 'eau chaude', 'aspiration'],
      [C('fluide', 'Mesurer la pression à l’aspiration et comparer le NPSH disponible au NPSH requis (courbe du constructeur).', 'NPSH disponible supérieur au NPSH requis, avec marge.',
         'Vérifier que l’installation donne à la pompe la pression d’aspiration dont elle a besoin.')],
      'Augmenter la pression à l’aspiration (niveau plus haut, conduite plus courte ou plus grosse, moins de coudes, liquide moins chaud) ou réduire le débit ; remplacer la roue si elle est érodée.'),
    H('Garniture mécanique usée', 'Une fuite au niveau de l’arbre indique une garniture mécanique usée ou une tresse à resserrer.',
      ['+fuit', 'goutt', 'eau', '+garniture', 'etancheite', '+arbre', 'coule', 'tresse', 'sous la pompe'],
      [C('visuel', 'Inspecter la sortie d’arbre : fuite le long de l’arbre, traces de calcaire ou de rouille sous la garniture.', 'Pas de fuite (ou un goutte-à-goutte admis pour une tresse).',
         'Constater d’où vient l’eau.')],
      'Pompe consignée et isolée : remplacer la garniture mécanique (même matière, faces propres, montage sans graisse sur les faces), contrôler l’état de l’arbre ; chercher la cause d’une usure rapide (marche à sec, liquide chargé, désalignement).'),
    H('Roue usée ou obstruée', 'Une roue usée ou encombrée ne fournit plus la hauteur manométrique nominale : pression et débit en baisse alors que le moteur tourne normalement.',
      ['debit', 'faible', 'pression', 'hauteur', '+usure', 'vibr', 'ancienne', 'progressi', 'ne monte plus'],
      [C('fluide', 'Relever la pression au refoulement vanne fermée (quelques secondes) et en service, puis comparer à la courbe du constructeur.', 'Point de fonctionnement sur la courbe.',
         'Une pompe usée ne tient plus sa courbe.'),
       C('visuel', 'Pompe consignée et isolée : ouvrir le corps et contrôler la roue et les bagues d’usure (érosion, jeu, corps étranger).', 'Roue entière, jeux dans la tolérance.',
         'Constater l’usure.')],
      'Pompe consignée : remplacer la roue et les bagues d’usure (ou la pompe si le corps est atteint), puis vérifier pression et débit sur la courbe.'),
    H('Roue bloquée ou obstruée par un corps étranger', 'Sur une pompe de relevage, lingettes et filasses s’enroulent autour de la roue : le moteur force, bourdonne et déclenche sa protection.',
      ['+filasse', '+lingette', '+bloqu', 'disjonct', 'thermique', '+relevage', 'eaux usees', 'bourdonn', 'surintensit', 'chiffon', 'corps etranger', 'declench'],
      [C('sous_tension', 'Mesurer l’intensité absorbée par la pompe en marche et la comparer à la plaque.', 'Intensité inférieure ou égale à l’intensité nominale.',
         'Un moteur qui force se voit au courant.'),
       C('visuel', 'Pompe consignée et relevée : inspecter la roue et la volute, faire tourner la roue à la main.', 'Roue libre, sans corps étranger.',
         'Constater l’obstruction.')],
      'Pompe consignée et relevée : dégager la roue et la volute, vérifier que rien n’est déformé, puis contrôler l’intensité en marche ; si le problème revient, prévoir une roue dilacératrice ou un panier dégrilleur.',
      { diff: false }),
    H('Sens de rotation inversé', 'Après intervention électrique, une inversion de phases fait tourner la pompe à l’envers : elle débite peu, sans bruit particulier.',
      ['apres intervention', '+sens', 'debit faible', 'neuf', 'inverse', 'remplace', '+envers', 'depuis le remplacement'],
      [C('fonctionnel', 'Vérifier le sens de rotation (flèche sur le corps de pompe) par une brève impulsion.', 'Rotation dans le sens de la flèche.',
         'Vérification immédiate.')],
      'Consigné : croiser deux phases au départ de la pompe, puis vérifier le sens, la pression et l’intensité.'),
    H('Flotteur ou régulateur de niveau bloqué ou défectueux', 'Une pompe de relevage qui ne démarre pas alors que la fosse est pleine, ou qui ne s’arrête plus, a souvent son flotteur coincé (graisses, câble emmêlé) ou hors service.',
      ['+flotteur', '+poire', 'niveau', 'relevage', 'ne demarre', '+debord', 'ne s arrete', 'alarme niveau', 'fosse pleine', 'marche forcee', 'manuel'],
      [C('fonctionnel', 'Basculer le flotteur à la main et contrôler son changement d’état (ohmmètre sur ses fils débranchés, ou démarrage de la pompe).', 'Contact qui change franchement d’état à chaque basculement.',
         'Vérifier directement l’organe de commande.',
         { localize: true, onConform: 'Flotteur bon électriquement : vérifier qu’il n’est pas coincé dans la fosse.' }),
       C('visuel', 'Contrôler la liberté du flotteur dans la fosse (graisses, câble emmêlé, position des butées).', 'Flotteur libre sur toute sa course.',
         'Un flotteur bon électriquement peut rester coincé.',
         { localize: true, onConform: 'Flotteur libre : le défaut est électrique (contact, câble, coffret).' })],
      'Pompe consignée : nettoyer la fosse, libérer ou remplacer le flotteur, régler sa course (niveaux de marche et d’arrêt), puis faire un essai en remplissant la fosse.'),
    H('Pressostat déréglé ou défectueux', 'Une pompe qui ne s’arrête plus, ne démarre plus, ou s’enclenche à de mauvaises pressions a son pressostat déréglé, ses contacts usés ou sa prise de pression bouchée.',
      ['+pressostat', 'ne s arrete', 'ne demarre', 'pression', 'enclenche', 'continu', 'tourne sans arret', 'reglage'],
      [C('fluide', 'Relever au manomètre les pressions réelles d’enclenchement et de déclenchement et les comparer aux réglages.', 'Enclenchement et déclenchement aux pressions réglées.',
         'Voir si le pressostat fait ce pour quoi il est réglé.'),
       C('hors_tension', 'Pompe consignée, pression purgée : contrôler les contacts du pressostat et sa prise de pression (tube ou orifice bouché).', 'Contacts propres, prise de pression libre.',
         'Trouver pourquoi le pressostat ne réagit pas.')],
      'Consigné et hors pression : déboucher la prise de pression, remplacer le pressostat si ses contacts sont brûlés, régler les seuils, puis vérifier plusieurs cycles.'),
    H('Réservoir à vessie dégonflé ou vessie percée', 'Sur un surpresseur, des démarrages très rapprochés à chaque puisage (courts cycles) signent un réservoir qui ne joue plus son rôle : pression de gonflage perdue ou vessie percée.',
      ['+surpresseur', '+demarrages frequents', '+court cycle', '+courts cycles', 'demarre et s arrete', 'toutes les', '+ballon', '+vessie', 'reservoir', 'a chaque puisage', 'coups de belier', 'manometre oscille', 'robinet'],
      [C('fluide', 'Pompe arrêtée, réservoir isolé et vidangé côté eau : mesurer la pression de gonflage à la valve.', 'Environ 0,2 bar sous la pression d’enclenchement de la pompe.',
         'Un réservoir dégonflé ne stocke plus d’eau sous pression.'),
       C('visuel', 'Appuyer brièvement sur la valve de gonflage.', 'Il sort de l’air sec (si de l’eau sort : la vessie est percée).',
         'Savoir s’il suffit de regonfler ou s’il faut remplacer la vessie.',
         { localize: true, onConform: 'Vessie intacte : un regonflage suffit.' })],
      'Réservoir isolé et vidangé : regonfler à la pression d’enclenchement moins 0,2 bar ; si la vessie est percée, la remplacer (ou le réservoir). Vérifier ensuite que la pompe ne démarre plus à chaque petit puisage.'),
    H('Clapet anti-retour non étanche', 'Une pompe qui redémarre seule sans aucun puisage, une pression qui retombe à l’arrêt ou une pompe qui se désamorce pointent vers un clapet anti-retour qui fuit.',
      ['+redemarre seule', '+sans puisage', '+clapet', 'pression chute', 'retomb', 'se vide', 'a l envers a l arret', 'la nuit', 'sans consommation'],
      [C('fluide', 'Pompe arrêtée, vanne de refoulement vers le réseau fermée : observer la pression en amont du clapet pendant quelques minutes.', 'Pression stable.',
         'Séparer une fuite du réseau d’un retour par le clapet.'),
       C('visuel', 'Pompe consignée et isolée : démonter et inspecter le clapet anti-retour (siège, ressort, corps étranger).', 'Clapet propre, siège intact, fermeture franche.',
         'Constater le défaut d’étanchéité.')],
      'Pompe consignée et isolée : nettoyer ou remplacer le clapet anti-retour, puis vérifier que la pression tient à l’arrêt.'),
    H('Marche à sec / manque d’eau', 'Une pompe qui a tourné sans eau chauffe, détruit sa garniture et se met en sécurité : niveau de la réserve trop bas ou sécurité manque d’eau inopérante.',
      ['+marche a sec', '+manque d eau', '+plus d eau', '+forage', 'nappe', 'amperage faible', 'intensite faible', 'niveau bas', 'cuve vide', 'bache', 'chauffe', 'securite', 'citerne', 'reserve'],
      [C('visuel', 'Contrôler le niveau de la réserve et le fonctionnement de la sécurité manque d’eau (sonde, flotteur ou pressostat à l’aspiration).', 'Niveau suffisant, sécurité qui arrête la pompe avant le désamorçage.',
         'Vérifier la cause avant de remettre en eau.')],
      'Rétablir l’alimentation en eau, remettre en état la sécurité manque d’eau, contrôler la garniture mécanique (souvent détruite par la marche à sec) avant de redémarrer.'),
    H('Circulateur bloqué (gommé) ou désamorcé par l’air', 'Après un long arrêt, le rotor d’un circulateur de chauffage reste collé par les dépôts : il bourdonne, chauffe et ne tourne pas. De l’air dans le corps donne le même résultat, avec des bruits d’eau.',
      ['+circulateur', 'chauffage', 'radiateurs froids', 'bloqu', 'apres l ete', 'bourdonn', 'ne tourne pas', 'remise en chauffe', 'depart chaud', 'retour froid'],
      [C('fonctionnel', 'Circulateur consigné : dévisser le bouchon de dégommage et faire tourner l’arbre au tournevis ; purger l’air.', 'Arbre libre, pas d’air à la purge.',
         'Un rotor collé se sent immédiatement au tournevis.')],
      'Consigné : dégommer le rotor, purger, remettre en marche et vérifier l’écart de température départ / retour ; remplacer le circulateur s’il se rebloque ou si son intensité reste anormale.'),

    H('Fuite sur le réseau en aval (la pompe compense)', 'Une pompe de maintien en pression qui redémarre à intervalles réguliers sans puisage, alors que son clapet et son réservoir sont bons, compense une fuite sur le réseau : robinet, chasse d’eau, soupape, canalisation.',
      ['+sans puisage', '+redemarre seule', 'toutes les', 'jockey', 'la nuit', 'sans que personne', 'sans consommation', 'compteur tourne', 'ria', 'surpresseur'],
      [C('fluide', 'Pompe arrêtée : fermer les vannes de sectionnement du réseau une à une et observer, à chaque fois, si la pression continue de chuter.', 'La pression chute de la même façon quel que soit le tronçon isolé.',
         'Le tronçon dont l’isolement arrête la chute de pression porte la fuite.'),
       C('visuel', 'Sur le tronçon désigné : inspecter les points de puisage, soupapes, purgeurs et canalisations apparentes.', 'Aucun écoulement, aucune trace d’humidité.',
         'Trouver la fuite.')],
      'Réparer la fuite (robinet, soupape, joint, canalisation), puis vérifier que la pompe ne redémarre plus sans puisage.'),

    H('Refoulement obstrué ou vanne fermée', 'Une pompe qui tourne, monte en pression mais ne débite pas (ou très peu) refoule contre un obstacle : vanne restée fermée après des travaux, clapet bloqué fermé, conduite bouchée ou gelée.',
      ['+pas de debit', '+ne debite pas', 'pression monte', 'vanne', 'apres travaux', 'apres intervention', 'gel', 'bouche', 'tourne mais'],
      [C('fluide', 'Relever la pression au refoulement en marche et la comparer à la pression à débit nul de la courbe.', 'Pression nettement inférieure à la pression à débit nul : la pompe débite.',
         'Une pression égale à celle du débit nul signe un refoulement fermé.'),
       C('visuel', 'Suivre le refoulement : position de chaque vanne, sens et liberté du clapet anti-retour, point bas gelé ou bouché.', 'Vannes ouvertes, clapet libre, conduite dégagée.',
         'Trouver l’obstacle.')],
      'Ouvrir la vanne, débloquer ou remplacer le clapet, dégager la conduite, puis vérifier débit et pression ; une pompe ne doit pas tourner longtemps à débit nul.')
  ]);
})(window.DM);
